/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.shop.model.domain.SEntity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurrCourse generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "currencyid" 
})
@Entity
@Table(name="curr_course")
public class CurrCourse extends SEntity  {

	private static final long serialVersionUID = 8195369832511993L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("course") private Integer course;
	@JsonProperty("currency") private Integer currencyid;
	@JsonProperty("datecourse") private Date datecourse;

	public CurrCourse() {
	}

	public CurrCourse(int id) {
		this.id = id;
	}

	public CurrCourse(int id,

			Integer course, Integer currencyid, Date datecourse) {
		this.id = id;
		this.course = course;
		this.currencyid = currencyid;
		this.datecourse = datecourse;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_CURRCOURSE")
	@SequenceGenerator(name = "SQ_CURRCOURSE", sequenceName = "SQ_CURRCOURSE", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	

	

	

	

	@Column(name="course")
	public Integer getCourse() {
		return this.course;
	}

	public void setCourse(Integer course) {
		this.course = course;
	}

	@Column(name="currencyid")
	public Integer getCurrencyid() {
		return this.currencyid;
	}

	public void setCurrencyid(Integer currencyid) {
		this.currencyid = currencyid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="datecourse", length = 29)
	public Date getDatecourse() {
		return this.datecourse;
	}

	public void setDatecourse(Date datecourse) {
		this.datecourse = datecourse;
	}

	
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {

	}
	
	public CurrCourse specialInit() {
	
		
		return this;
	}
	
	public CurrCourse init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public CurrCourse preInitList() {

		return this;
	}
	
	public CurrCourse initList() {

		return this;
	}
	
	public CurrCourse initDicts() {

		return this;
	}
	
	
}