/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.persistence.PreRemove;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import javax.persistence.CascadeType;
import org.test.shop.model.domain.SEntity;

import java.util.LinkedList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * InfoPermission generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="info_permission")
public class InfoPermission extends SEntity  {

	private static final long serialVersionUID = 6157387773493892L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("docdocuments") private DocDocuments docDocuments;
	@JsonProperty("descr") private String descr;
	private List<RelShopPermission> relShopPermissions = new LinkedList<RelShopPermission>();

	public InfoPermission() {
	}

	public InfoPermission(int id) {
		this.id = id;
	}

	public InfoPermission(int id, DocDocuments docDocuments, String descr,



			List<RelShopPermission> relShopPermissions) {
		this.id = id;
		this.docDocuments = docDocuments;
		this.descr = descr;
		this.relShopPermissions = relShopPermissions;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_INFOPERMISSION")
	@SequenceGenerator(name = "SQ_INFOPERMISSION", sequenceName = "SQ_INFOPERMISSION", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="doc_document_id")
	public DocDocuments getDocDocuments() {
		return this.docDocuments;
	}

	public void setDocDocuments(DocDocuments docDocuments) {
		this.docDocuments = docDocuments;
	}

	@Column(name="descr", length=2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	

	

	

	

	

	

	@OneToMany(fetch=FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy="infoPermission")
	public List<RelShopPermission> getRelShopPermissions() {
		return this.relShopPermissions;
	}

	public void setRelShopPermissions(List<RelShopPermission> relShopPermissions) {
		this.relShopPermissions = relShopPermissions;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		docDocuments = null;

	}
	
	public InfoPermission specialInit() {
	
		
		return this;
	}
	
	public InfoPermission init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public InfoPermission preInitList() {
		if(getRelShopPermissions() == null) setRelShopPermissions(new LinkedList());
		getRelShopPermissions().parallelStream().forEach(it -> it.setInfoPermission(this));

		return this;
	}
	
	public InfoPermission initList() {
		initLists(relShopPermissions);

		return this;
	}
	
	public InfoPermission initDicts() {
		initSentity(getDocDocuments());

		return this;
	}
	
	
}