/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.shop.model.domain.SEntity;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * PaymentPriceShop generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="payment_price_shop")
public class PaymentPriceShop extends SEntity  {

	private static final long serialVersionUID = 9439298612637652L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("paymenttariffshop") private PaymentTariffShop paymentTariffShop;
	@JsonProperty("humannumber") private Integer humannumber;
	@JsonProperty("price") private BigDecimal price;

	public PaymentPriceShop() {
	}

	public PaymentPriceShop(int id) {
		this.id = id;
	}

	public PaymentPriceShop(int id, PaymentTariffShop paymentTariffShop,


			Integer humannumber) {
		this.id = id;
		this.paymentTariffShop = paymentTariffShop;
		this.humannumber = humannumber;
		this.price = price;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_PAYMENTPRICESHOP")
	@SequenceGenerator(name = "SQ_PAYMENTPRICESHOP", sequenceName = "SQ_PAYMENTPRICESHOP", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="payment_tariff_shop_id")
	public PaymentTariffShop getPaymentTariffShop() {
		return this.paymentTariffShop;
	}

	public void setPaymentTariffShop(PaymentTariffShop paymentTariffShop) {
		this.paymentTariffShop = paymentTariffShop;
	}

	

	

	

	

	@Column(name="humannumber")
	public Integer getHumannumber() {
		return this.humannumber;
	}

	public void setHumannumber(Integer humannumber) {
		this.humannumber = humannumber;
	}

	@Column(name="price", precision = 131089, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		paymentTariffShop = null;

	}
	
	public PaymentPriceShop specialInit() {
	
		
		return this;
	}
	
	public PaymentPriceShop init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public PaymentPriceShop preInitList() {

		return this;
	}
	
	public PaymentPriceShop initList() {

		return this;
	}
	
	public PaymentPriceShop initDicts() {
		initSentity(getPaymentTariffShop());

		return this;
	}
	
	
}