/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.BatchSize;
import org.test.shop.model.domain.SRel;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelServHotelDocDocuments generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="rel_serv_hotel_doc_documents")
public class RelServHotelDocDocuments extends SRel  {

	private static final long serialVersionUID = 1866828375197894L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("docdocuments") private DocDocuments docDocuments;
	@JsonProperty("servhotel") private ServHotel servHotel;

	public RelServHotelDocDocuments() {
	}

	public RelServHotelDocDocuments(int id) {
		this.id = id;
	}

	public RelServHotelDocDocuments(int id, DocDocuments docDocuments,
			ServHotel servHotel) {
		this.id = id;
		this.docDocuments = docDocuments;
		this.servHotel = servHotel;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_RELSERVHOTELDOCDOCUMENTS")
	@SequenceGenerator(name = "SQ_RELSERVHOTELDOCDOCUMENTS", sequenceName = "SQ_RELSERVHOTELDOCDOCUMENTS", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="doc_documents_id")
	public DocDocuments getDocDocuments() {
		return this.docDocuments;
	}

	public void setDocDocuments(DocDocuments docDocuments) {
		this.docDocuments = docDocuments;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="serv_hotel_id")
	public ServHotel getServHotel() {
		return this.servHotel;
	}

	public void setServHotel(ServHotel servHotel) {
		this.servHotel = servHotel;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		docDocuments = null;
		servHotel = null;

	}
	
	public RelServHotelDocDocuments specialInit() {
	
		
		return this;
	}
	
	public RelServHotelDocDocuments init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServHotelDocDocuments preInitList() {

		return this;
	}
	
	public RelServHotelDocDocuments initList() {

		return this;
	}
	
	public RelServHotelDocDocuments initDicts() {
		initSentity(getDocDocuments());
		initSentity(getServHotel());

		return this;
	}
	
	
}