/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.BatchSize;
import org.test.shop.model.domain.SRel;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelServHotelImage generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="rel_serv_hotel_image")
public class RelServHotelImage extends SRel  {

	private static final long serialVersionUID = 3918336275154466L;

	private Integer id;
	private ServHotel servHotel;
	@JsonProperty("image") private TmImage tmImage;

	public RelServHotelImage() {
	}

	public RelServHotelImage(int id) {
		this.id = id;
	}

	public RelServHotelImage(int id, ServHotel servHotel, TmImage tmImage) {
		this.id = id;
		this.servHotel = servHotel;
		this.tmImage = tmImage;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_RELSERVHOTELIMAGE")
	@SequenceGenerator(name = "SQ_RELSERVHOTELIMAGE", sequenceName = "SQ_RELSERVHOTELIMAGE", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="serv_hotel_id")
	public ServHotel getServHotel() {
		return this.servHotel;
	}

	public void setServHotel(ServHotel servHotel) {
		this.servHotel = servHotel;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="image_id")
	public TmImage getTmImage() {
		return this.tmImage;
	}

	public void setTmImage(TmImage tmImage) {
		this.tmImage = tmImage;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		servHotel = null;
		tmImage = null;

	}
	
	public RelServHotelImage specialInit() {
	
		
		return this;
	}
	
	public RelServHotelImage init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServHotelImage preInitList() {

		return this;
	}
	
	public RelServHotelImage initList() {

		return this;
	}
	
	public RelServHotelImage initDicts() {
		initSentity(getServHotel());
		initSentity(getTmImage());

		return this;
	}
	
	
}