/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.BatchSize;
import org.test.shop.model.domain.SRel;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelServTransferTmContact generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="rel_serv_transfer_tm_contact")
public class RelServTransferTmContact extends SRel  {

	private static final long serialVersionUID = 5777921122476182L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("servtransfer") private ServTransfer servTransfer;
	@JsonProperty("tmcontact") private TmContact tmContact;

	public RelServTransferTmContact() {
	}

	public RelServTransferTmContact(int id) {
		this.id = id;
	}

	public RelServTransferTmContact(int id, ServTransfer servTransfer,
			TmContact tmContact) {
		this.id = id;
		this.servTransfer = servTransfer;
		this.tmContact = tmContact;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_RELSERVTRANSFERTMCONTACT")
	@SequenceGenerator(name = "SQ_RELSERVTRANSFERTMCONTACT", sequenceName = "SQ_RELSERVTRANSFERTMCONTACT", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="serv_transfers_id")
	public ServTransfer getServTransfer() {
		return this.servTransfer;
	}

	public void setServTransfer(ServTransfer servTransfer) {
		this.servTransfer = servTransfer;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="tm_contact_id")
	public TmContact getTmContact() {
		return this.tmContact;
	}

	public void setTmContact(TmContact tmContact) {
		this.tmContact = tmContact;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		servTransfer = null;
		tmContact = null;

	}
	
	public RelServTransferTmContact specialInit() {
	
		
		return this;
	}
	
	public RelServTransferTmContact init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServTransferTmContact preInitList() {

		return this;
	}
	
	public RelServTransferTmContact initList() {

		return this;
	}
	
	public RelServTransferTmContact initDicts() {
		initSentity(getServTransfer());
		initSentity(getTmContact());

		return this;
	}
	
	
}