/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.BatchSize;
import org.test.shop.model.domain.SRel;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelUserDetails generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="rel_user_details")
public class RelUserDetails extends SRel  {

	private static final long serialVersionUID = 7411155284786336L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("userdetail") private UserDetail userDetail;
	@JsonProperty("users") private Users users;

	public RelUserDetails() {
	}

	public RelUserDetails(int id) {
		this.id = id;
	}

	public RelUserDetails(int id, UserDetail userDetail, Users users) {
		this.id = id;
		this.userDetail = userDetail;
		this.users = users;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_RELUSERDETAILS")
	@SequenceGenerator(name = "SQ_RELUSERDETAILS", sequenceName = "SQ_RELUSERDETAILS", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="user_details_id")
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="users_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		userDetail = null;
		users = null;

	}
	
	public RelUserDetails specialInit() {
	
		
		return this;
	}
	
	public RelUserDetails init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelUserDetails preInitList() {

		return this;
	}
	
	public RelUserDetails initList() {

		return this;
	}
	
	public RelUserDetails initDicts() {
		initSentity(getUserDetail());
		initSentity(getUsers());

		return this;
	}
	
	
}