/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.shop.model.domain.SEntity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServTransferRoutePoint generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="serv_transfer_route_point")
public class ServTransferRoutePoint extends SEntity  {

	private static final long serialVersionUID = 7128239334821132L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("servtransferroute") private ServTransferRoute servTransferRoute;
	@JsonProperty("fixedallowance") private BigDecimal fixedAllowance;
	@JsonProperty("free") private Boolean free;
	@JsonProperty("percentageofallowances") private BigDecimal percentageOfAllowances;
	@JsonProperty("pointfrom") private String pointFrom;
	@JsonProperty("pointto") private String pointTo;
	@JsonProperty("starton") private Date startOn;
	@JsonProperty("sum") private Integer sum;

	public ServTransferRoutePoint() {
	}

	public ServTransferRoutePoint(int id) {
		this.id = id;
	}

	public ServTransferRoutePoint(int id, ServTransferRoute servTransferRoute,


 BigDecimal fixedAllowance, Boolean free,
			BigDecimal percentageOfAllowances, String pointFrom,
			String pointTo) {
		this.id = id;
		this.servTransferRoute = servTransferRoute;
		this.fixedAllowance = fixedAllowance;
		this.free = free;
		this.percentageOfAllowances = percentageOfAllowances;
		this.pointFrom = pointFrom;
		this.pointTo = pointTo;
		this.startOn = startOn;
		this.sum = sum;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_SERVTRANSFERROUTEPOINT")
	@SequenceGenerator(name = "SQ_SERVTRANSFERROUTEPOINT", sequenceName = "SQ_SERVTRANSFERROUTEPOINT", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="transfer_route_id")
	public ServTransferRoute getServTransferRoute() {
		return this.servTransferRoute;
	}

	public void setServTransferRoute(ServTransferRoute servTransferRoute) {
		this.servTransferRoute = servTransferRoute;
	}

	

	

	

	

	

	@Column(name="fixed_allowance", precision = 17, scale = 3)
	public BigDecimal getFixedAllowance() {
		return this.fixedAllowance;
	}

	public void setFixedAllowance(BigDecimal fixedAllowance) {
		this.fixedAllowance = fixedAllowance;
	}

	@Column(name="free")
	public Boolean getFree() {
		return this.free;
	}

	public void setFree(Boolean free) {
		this.free = free;
	}

	@Column(name="percentage_of_allowances", precision = 17, scale = 3)
	public BigDecimal getPercentageOfAllowances() {
		return this.percentageOfAllowances;
	}

	public void setPercentageOfAllowances(BigDecimal percentageOfAllowances) {
		this.percentageOfAllowances = percentageOfAllowances;
	}

	@Column(name="point_from")
	public String getPointFrom() {
		return this.pointFrom;
	}

	public void setPointFrom(String pointFrom) {
		this.pointFrom = pointFrom;
	}

	@Column(name="point_to")
	public String getPointTo() {
		return this.pointTo;
	}

	public void setPointTo(String pointTo) {
		this.pointTo = pointTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="start_on", length = 29)
	public Date getStartOn() {
		return this.startOn;
	}

	public void setStartOn(Date startOn) {
		this.startOn = startOn;
	}

	@Column(name="sum")
	public Integer getSum() {
		return this.sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		servTransferRoute = null;

	}
	
	public ServTransferRoutePoint specialInit() {
	
		
		return this;
	}
	
	public ServTransferRoutePoint init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ServTransferRoutePoint preInitList() {

		return this;
	}
	
	public ServTransferRoutePoint initList() {

		return this;
	}
	
	public ServTransferRoutePoint initDicts() {
		initSentity(getServTransferRoute());

		return this;
	}
	
	
}