/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.shop.model.domain.SEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * ShopUser generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "createon"
			, "modifyon"
			, "popularity" 
})
@Entity
@Table(name="shop_user")
public class ShopUser extends SEntity  {

	private static final long serialVersionUID = 3195875879638492L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("activated") private Boolean activated;
	@JsonProperty("activationkey") private String activationkey;
	@JsonProperty("email") private String email;
	@JsonProperty("enabled") private Boolean enabled;
	@JsonProperty("firstname") private String firstname;
	@JsonProperty("lastname") private String lastname;
	@JsonProperty("password") private String password;
	@JsonProperty("username") private String username;
	@JsonProperty("image") private Integer imageId;
	@JsonProperty("token") private String token;
	@JsonProperty("phonenumber") private String phonenumber;
	@JsonProperty("shoppermission") private Integer shopPermissionId;

	public ShopUser() {
	}

	public ShopUser(int id, String username) {
		this.id = id;
		this.username=username;
	}

	public ShopUser(int id,

			Boolean activated, String activationkey, String email,
			Boolean enabled, String firstname, String lastname,
			String password, String username, Integer imageId, String token,
			String phonenumber, Integer shopPermissionId) {
		this.id = id;
		this.activated = activated;
		this.activationkey = activationkey;
		this.email = email;
		this.enabled = enabled;
		this.firstname=firstname;
		this.lastname=lastname;
		this.password = password;
		this.username=username;
		this.imageId = imageId;
		this.token = token;
		this.phonenumber = phonenumber;
		this.shopPermissionId = shopPermissionId;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_SHOPUSER")
	@SequenceGenerator(name = "SQ_SHOPUSER", sequenceName = "SQ_SHOPUSER", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	

	

	

	

	@Column(name="activated")
	public Boolean getActivated() {
		return this.activated;
	}

	public void setActivated(Boolean activated) {
		this.activated = activated;
	}

	@Column(name="activationkey")
	public String getActivationkey() {
		return this.activationkey;
	}

	public void setActivationkey(String activationkey) {
		this.activationkey = activationkey;
	}

	@Column(name="email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name="enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name="firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname=firstname;
	}

	@Column(name="lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname=lastname;
	}

	@Column(name="password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name="username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username=username;
	}

	@Column(name="image_id")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@Column(name="token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name="phonenumber")
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	

	@Column(name="shop_permission_id")
	public Integer getShopPermissionId() {
		return this.shopPermissionId;
	}

	public void setShopPermissionId(Integer shopPermissionId) {
		this.shopPermissionId = shopPermissionId;
	}

	
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {

	}
	
	public ShopUser specialInit() {
	
		
		return this;
	}
	
	public ShopUser init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ShopUser preInitList() {

		return this;
	}
	
	public ShopUser initList() {

		return this;
	}
	
	public ShopUser initDicts() {

		return this;
	}
	
	
}