/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.shop.model.domain.SEntity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmFirms generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "accountid" 
})
@Entity
@Table(name="tm_firms")
public class TmFirms extends SEntity  {

	private static final long serialVersionUID = 8631636996887519L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("account") private Integer accountid;
	@JsonProperty("active") private String active;
	@JsonProperty("firmname") private String firmName;
	@JsonProperty("lastpay") private Date lastpay;
	@JsonProperty("mounthcount") private Integer mounthcount;

	public TmFirms() {
	}

	public TmFirms(int id, String firmName) {
		this.id = id;
		this.firmName = firmName;
	}

	public TmFirms(int id,

 Integer accountid, String active, String firmName,
			Date lastpay) {
		this.id = id;
		this.accountid = accountid;
		this.active = active;
		this.firmName = firmName;
		this.lastpay = lastpay;
		this.mounthcount = mounthcount;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_TMFIRMS")
	@SequenceGenerator(name = "SQ_TMFIRMS", sequenceName = "SQ_TMFIRMS", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	

	

	

	

	

	@Column(name="accountid")
	public Integer getAccountid() {
		return this.accountid;
	}

	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	@Column(name="active")
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name="firm_name", nullable = false)
	public String getFirmName() {
		return this.firmName;
	}

	public void setFirmName(String firmName) {
		this.firmName = firmName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="lastpay", length = 29)
	public Date getLastpay() {
		return this.lastpay;
	}

	public void setLastpay(Date lastpay) {
		this.lastpay = lastpay;
	}

	@Column(name="mounthcount")
	public Integer getMounthcount() {
		return this.mounthcount;
	}

	public void setMounthcount(Integer mounthcount) {
		this.mounthcount = mounthcount;
	}

	
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {

	}
	
	public TmFirms specialInit() {
	
		
		return this;
	}
	
	public TmFirms init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmFirms preInitList() {

		return this;
	}
	
	public TmFirms initList() {

		return this;
	}
	
	public TmFirms initDicts() {

		return this;
	}
	
	
}