/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.shop.model.domain.SEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * TmFirmSettings generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="tm_firm_settings")
public class TmFirmSettings extends SEntity  {

	private static final long serialVersionUID = 5969358884217149L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("docdocuments") private DocDocuments docDocuments;
	@JsonProperty("logo") private Integer logoId;
	@JsonProperty("brand") private String brand;

	public TmFirmSettings() {
	}

	public TmFirmSettings(int id) {
		this.id = id;
	}

	public TmFirmSettings(int id, DocDocuments docDocuments, Integer logoId,
			String brand) {
		this.id = id;
		this.docDocuments = docDocuments;
		this.logoId = logoId;
		this.brand = brand;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_TMFIRMSETTINGS")
	@SequenceGenerator(name = "SQ_TMFIRMSETTINGS", sequenceName = "SQ_TMFIRMSETTINGS", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="doc_documents_id")
	public DocDocuments getDocDocuments() {
		return this.docDocuments;
	}

	public void setDocDocuments(DocDocuments docDocuments) {
		this.docDocuments = docDocuments;
	}

	@Column(name="logo_id")
	public Integer getLogoId() {
		return this.logoId;
	}

	public void setLogoId(Integer logoId) {
		this.logoId = logoId;
	}

	@Column(name="brand")
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	

	

	

	

	
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		docDocuments = null;

	}
	
	public TmFirmSettings specialInit() {
	
		
		return this;
	}
	
	public TmFirmSettings init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmFirmSettings preInitList() {

		return this;
	}
	
	public TmFirmSettings initList() {

		return this;
	}
	
	public TmFirmSettings initDicts() {
		initSentity(getDocDocuments());

		return this;
	}
	
	
}