/* #UPDATED */
/* #CLEARED */
package org.test.shop.model.domain.entity;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.persistence.PreRemove;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import javax.persistence.CascadeType;
import org.test.shop.model.domain.SEntity;

import java.util.LinkedList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * TmMailNewsletter generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="tm_mail_newsletter")
public class TmMailNewsletter extends SEntity  {

	private static final long serialVersionUID = 1984847147857816L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("subject") private String subject;
	@JsonProperty("content") private String content;
	@JsonProperty("backgroundcolor") private String backgroundColor;
	@JsonProperty("badge") private String badge;
	@JsonProperty("badgetype") private String badgeType;
	private List<RelMailNewsletterGroup> relMailNewsletterGroups = new LinkedList<RelMailNewsletterGroup>();

	public TmMailNewsletter() {
	}

	public TmMailNewsletter(int id) {
		this.id = id;
	}

	public TmMailNewsletter(int id, String subject, String content,
			String backgroundColor, String badge, String badgeType,



			List<RelMailNewsletterGroup> relMailNewsletterGroups) {
		this.id = id;
		this.subject = subject;
		this.content = content;
		this.backgroundColor = backgroundColor;
		this.badge = badge;
		this.badgeType = badgeType;
		this.relMailNewsletterGroups = relMailNewsletterGroups;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_TMMAILNEWSLETTER")
	@SequenceGenerator(name = "SQ_TMMAILNEWSLETTER", sequenceName = "SQ_TMMAILNEWSLETTER", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name="subject")
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name="content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name="background_color")
	public String getBackgroundColor() {
		return this.backgroundColor;
	}

	public void setBackgroundColor(String backgroundColor) {
		this.backgroundColor = backgroundColor;
	}

	@Column(name="badge")
	public String getBadge() {
		return this.badge;
	}

	public void setBadge(String badge) {
		this.badge = badge;
	}

	@Column(name="badge_type")
	public String getBadgeType() {
		return this.badgeType;
	}

	public void setBadgeType(String badgeType) {
		this.badgeType = badgeType;
	}

	

	

	

	

	

	

	@OneToMany(fetch=FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy="tmMailNewsletter")
	public List<RelMailNewsletterGroup> getRelMailNewsletterGroups() {
		return this.relMailNewsletterGroups;
	}

	public void setRelMailNewsletterGroups(List<RelMailNewsletterGroup> relMailNewsletterGroups) {
		this.relMailNewsletterGroups = relMailNewsletterGroups;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {

	}
	
	public TmMailNewsletter specialInit() {
	
		
		return this;
	}
	
	public TmMailNewsletter init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmMailNewsletter preInitList() {
		if(getRelMailNewsletterGroups() == null) setRelMailNewsletterGroups(new LinkedList());
		getRelMailNewsletterGroups().parallelStream().forEach(it -> it.setTmMailNewsletter(this));

		return this;
	}
	
	public TmMailNewsletter initList() {
		initLists(relMailNewsletterGroups);

		return this;
	}
	
	public TmMailNewsletter initDicts() {

		return this;
	}
	
	
}