/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * LocationCitiesView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "locationcountriesid" 
})
@Entity
@Table(name="location_cities_view")
public class LocationCitiesView extends SView  {

	private static final long serialVersionUID = 1163872492479175L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String cityname;
	private String descr;
	private Integer popularity;
	private String locationcountries;
	private Integer locationcountriesid;

	private List<ServTransferView> servTransfers = new LinkedList<ServTransferView>();
	private List<ServHotelView> servHotels = new LinkedList<ServHotelView>();
	
	public LocationCitiesView() {
	}

	public LocationCitiesView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String cityname, String descr,
			Integer popularity, String locationcountries,
			Integer locationcountriesid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.cityname=cityname;
		this.descr = descr;
		this.popularity = popularity;
		this.locationcountries = locationcountries;
		this.locationcountriesid = locationcountriesid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="cityname")
	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname=cityname;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="locationcountries")
	public String getLocationcountries() {
		return this.locationcountries;
	}

	public void setLocationcountries(String locationcountries) {
		this.locationcountries = locationcountries;
	}

	@Column(name="locationcountriesid")
	public Integer getLocationcountriesid() {
		return this.locationcountriesid;
	}

	public void setLocationcountriesid(Integer locationcountriesid) {
		this.locationcountriesid = locationcountriesid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="locationcitiesid")
	public List<ServTransferView> getServTransfers() {
		return this.servTransfers;
	}

	public void setServTransfers(List<ServTransferView> servTransfers) {
		this.servTransfers = servTransfers;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="locationcitiesid")
	public List<ServHotelView> getServHotels() {
		return this.servHotels;
	}

	public void setServHotels(List<ServHotelView> servHotels) {
		this.servHotels = servHotels;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationCitiesView))
			return false;
		LocationCitiesView castOther = (LocationCitiesView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getCityname() == castOther.getCityname()) || (this
						.getCityname() != null
						&& castOther.getCityname() != null && this
						.getCityname().equals(castOther.getCityname())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getLocationcountries() == castOther
						.getLocationcountries()) || (this
						.getLocationcountries() != null
						&& castOther.getLocationcountries() != null && this
						.getLocationcountries().equals(
								castOther.getLocationcountries())))
				&& ((this.getLocationcountriesid() == castOther
						.getLocationcountriesid()) || (this
						.getLocationcountriesid() != null
						&& castOther.getLocationcountriesid() != null && this
						.getLocationcountriesid().equals(
								castOther.getLocationcountriesid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getCityname() == null ? 0 : this.getCityname().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getLocationcountries() == null ? 0 : this
						.getLocationcountries().hashCode());
		result = 37
				* result
				+ (getLocationcountriesid() == null ? 0 : this
						.getLocationcountriesid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public LocationCitiesView specialInit() {
	
		
		return this;
	}
	public LocationCitiesView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public LocationCitiesView customInitList(List<String> list) {
		if (list.contains("servTransfers")) {
			initLists(servTransfers);
		}
		if (list.contains("servHotels")) {
			initLists(servHotels);
		}
		return this;
	}
	
	public LocationCitiesView initList() {

		return this;
	}
	
	public LocationCitiesView initDicts() {
		return this;
	}
	
	
}