/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * PaymentTariffView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="payment_tariff_view")
public class PaymentTariffView extends SView  {

	private static final long serialVersionUID = 6964653957712261L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private Integer popularity;

	private List<ServHotelRoomView> servHotelRoomsForCostTarriffId = new LinkedList<ServHotelRoomView>();
	private List<ServHotelRoomView> servHotelRoomsForRrTarriffId = new LinkedList<ServHotelRoomView>();
	private List<ReqServHotelView> reqServHotels = new LinkedList<ReqServHotelView>();
	private List<PaymentPriceView> paymentPrices = new LinkedList<PaymentPriceView>();
	
	public PaymentTariffView() {
	}

	public PaymentTariffView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, Integer popularity) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.popularity = popularity;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="paymenttariffbycosttarriffid")
	public List<ServHotelRoomView> getServHotelRoomsForCostTarriffId() {
		return this.servHotelRoomsForCostTarriffId;
	}

	public void setServHotelRoomsForCostTarriffId(List<ServHotelRoomView> servHotelRoomsForCostTarriffId) {
		this.servHotelRoomsForCostTarriffId = servHotelRoomsForCostTarriffId;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="paymenttariffbyrrtarriffid")
	public List<ServHotelRoomView> getServHotelRoomsForRrTarriffId() {
		return this.servHotelRoomsForRrTarriffId;
	}

	public void setServHotelRoomsForRrTarriffId(List<ServHotelRoomView> servHotelRoomsForRrTarriffId) {
		this.servHotelRoomsForRrTarriffId = servHotelRoomsForRrTarriffId;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="paymenttariffid")
	public List<ReqServHotelView> getReqServHotels() {
		return this.reqServHotels;
	}

	public void setReqServHotels(List<ReqServHotelView> reqServHotels) {
		this.reqServHotels = reqServHotels;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="paymenttariffid")
	public List<PaymentPriceView> getPaymentPrices() {
		return this.paymentPrices;
	}

	public void setPaymentPrices(List<PaymentPriceView> paymentPrices) {
		this.paymentPrices = paymentPrices;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentTariffView))
			return false;
		PaymentTariffView castOther = (PaymentTariffView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public PaymentTariffView specialInit() {
	
		
		return this;
	}
	public PaymentTariffView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public PaymentTariffView customInitList(List<String> list) {
		if (list.contains("servHotelRoomsForCostTarriffId")) {
			initLists(servHotelRoomsForCostTarriffId);
		}
		if (list.contains("servHotelRoomsForRrTarriffId")) {
			initLists(servHotelRoomsForRrTarriffId);
		}
		if (list.contains("reqServHotels")) {
			initLists(reqServHotels);
		}
		if (list.contains("paymentPrices")) {
			initLists(paymentPrices);
		}
		return this;
	}
	
	public PaymentTariffView initList() {
		initLists(servHotelRoomsForCostTarriffId);
		initLists(servHotelRoomsForRrTarriffId);
		initLists(reqServHotels);
		initLists(paymentPrices);

		return this;
	}
	
	public PaymentTariffView initDicts() {
		return this;
	}
	
	
}