/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelMailNewsletterGroupView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "tmmailnewsletterid"
			, "tmmailnewslettergroupid" 
})
@Entity
@Table(name="rel_mail_newsletter_group_view")
public class RelMailNewsletterGroupView extends SView  {

	private static final long serialVersionUID = 1312887156781181L;

	private Integer id;
	private String tmmailnewsletter;
	private Integer tmmailnewsletterid;
	private String tmmailnewslettergroup;
	private Integer tmmailnewslettergroupid;

	public RelMailNewsletterGroupView() {
	}

	public RelMailNewsletterGroupView(Integer id, String tmmailnewsletter,
			Integer tmmailnewsletterid, String tmmailnewslettergroup,
			Integer tmmailnewslettergroupid) {
		this.id = id;
		this.tmmailnewsletter = tmmailnewsletter;
		this.tmmailnewsletterid = tmmailnewsletterid;
		this.tmmailnewslettergroup = tmmailnewslettergroup;
		this.tmmailnewslettergroupid = tmmailnewslettergroupid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="tmmailnewsletter")
	public String getTmmailnewsletter() {
		return this.tmmailnewsletter;
	}

	public void setTmmailnewsletter(String tmmailnewsletter) {
		this.tmmailnewsletter = tmmailnewsletter;
	}

	@Column(name="tmmailnewsletterid")
	public Integer getTmmailnewsletterid() {
		return this.tmmailnewsletterid;
	}

	public void setTmmailnewsletterid(Integer tmmailnewsletterid) {
		this.tmmailnewsletterid = tmmailnewsletterid;
	}

	@Column(name="tmmailnewslettergroup")
	public String getTmmailnewslettergroup() {
		return this.tmmailnewslettergroup;
	}

	public void setTmmailnewslettergroup(String tmmailnewslettergroup) {
		this.tmmailnewslettergroup = tmmailnewslettergroup;
	}

	@Column(name="tmmailnewslettergroupid")
	public Integer getTmmailnewslettergroupid() {
		return this.tmmailnewslettergroupid;
	}

	public void setTmmailnewslettergroupid(Integer tmmailnewslettergroupid) {
		this.tmmailnewslettergroupid = tmmailnewslettergroupid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelMailNewsletterGroupView))
			return false;
		RelMailNewsletterGroupView castOther = (RelMailNewsletterGroupView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getTmmailnewsletter() == castOther
						.getTmmailnewsletter()) || (this.getTmmailnewsletter() != null
						&& castOther.getTmmailnewsletter() != null && this
						.getTmmailnewsletter().equals(
								castOther.getTmmailnewsletter())))
				&& ((this.getTmmailnewsletterid() == castOther
						.getTmmailnewsletterid()) || (this
						.getTmmailnewsletterid() != null
						&& castOther.getTmmailnewsletterid() != null && this
						.getTmmailnewsletterid().equals(
								castOther.getTmmailnewsletterid())))
				&& ((this.getTmmailnewslettergroup() == castOther
						.getTmmailnewslettergroup()) || (this
						.getTmmailnewslettergroup() != null
						&& castOther.getTmmailnewslettergroup() != null && this
						.getTmmailnewslettergroup().equals(
								castOther.getTmmailnewslettergroup())))
				&& ((this.getTmmailnewslettergroupid() == castOther
						.getTmmailnewslettergroupid()) || (this
						.getTmmailnewslettergroupid() != null
						&& castOther.getTmmailnewslettergroupid() != null && this
						.getTmmailnewslettergroupid().equals(
								castOther.getTmmailnewslettergroupid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getTmmailnewsletter() == null ? 0 : this
						.getTmmailnewsletter().hashCode());
		result = 37
				* result
				+ (getTmmailnewsletterid() == null ? 0 : this
						.getTmmailnewsletterid().hashCode());
		result = 37
				* result
				+ (getTmmailnewslettergroup() == null ? 0 : this
						.getTmmailnewslettergroup().hashCode());
		result = 37
				* result
				+ (getTmmailnewslettergroupid() == null ? 0 : this
						.getTmmailnewslettergroupid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelMailNewsletterGroupView specialInit() {
	
		
		return this;
	}
	public RelMailNewsletterGroupView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelMailNewsletterGroupView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelMailNewsletterGroupView initList() {

		return this;
	}
	
	public RelMailNewsletterGroupView initDicts() {
		return this;
	}
	
	
}