/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelServHotelRoomImageView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "servhotelroomid"
			, "tmimageid" 
})
@Entity
@Table(name="rel_serv_hotel_room_image_view")
public class RelServHotelRoomImageView extends SView  {

	private static final long serialVersionUID = 2222193468149823L;

	private Integer id;
	private String servhotelroom;
	private Integer servhotelroomid;
	@JsonProperty("image") private String tmimage;
	private Integer tmimageid;

	public RelServHotelRoomImageView() {
	}

	public RelServHotelRoomImageView(Integer id, String servhotelroom,
			Integer servhotelroomid, String tmimage, Integer tmimageid) {
		this.id = id;
		this.servhotelroom = servhotelroom;
		this.servhotelroomid = servhotelroomid;
		this.tmimage = tmimage;
		this.tmimageid = tmimageid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="servhotelroom")
	public String getServhotelroom() {
		return this.servhotelroom;
	}

	public void setServhotelroom(String servhotelroom) {
		this.servhotelroom = servhotelroom;
	}

	@Column(name="servhotelroomid")
	public Integer getServhotelroomid() {
		return this.servhotelroomid;
	}

	public void setServhotelroomid(Integer servhotelroomid) {
		this.servhotelroomid = servhotelroomid;
	}

	@Column(name="tmimage")
	public String getTmimage() {
		return this.tmimage;
	}

	public void setTmimage(String tmimage) {
		this.tmimage = tmimage;
	}

	@Column(name="tmimageid")
	public Integer getTmimageid() {
		return this.tmimageid;
	}

	public void setTmimageid(Integer tmimageid) {
		this.tmimageid = tmimageid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelServHotelRoomImageView))
			return false;
		RelServHotelRoomImageView castOther = (RelServHotelRoomImageView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getServhotelroom() == castOther.getServhotelroom()) || (this
						.getServhotelroom() != null
						&& castOther.getServhotelroom() != null && this
						.getServhotelroom()
						.equals(castOther.getServhotelroom())))
				&& ((this.getServhotelroomid() == castOther
						.getServhotelroomid()) || (this.getServhotelroomid() != null
						&& castOther.getServhotelroomid() != null && this
						.getServhotelroomid().equals(
								castOther.getServhotelroomid())))
				&& ((this.getTmimage() == castOther.getTmimage()) || (this
						.getTmimage() != null && castOther.getTmimage() != null && this
						.getTmimage().equals(castOther.getTmimage())))
				&& ((this.getTmimageid() == castOther.getTmimageid()) || (this
						.getTmimageid() != null
						&& castOther.getTmimageid() != null && this
						.getTmimageid().equals(castOther.getTmimageid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getServhotelroom() == null ? 0 : this.getServhotelroom()
						.hashCode());
		result = 37
				* result
				+ (getServhotelroomid() == null ? 0 : this.getServhotelroomid()
						.hashCode());
		result = 37 * result
				+ (getTmimage() == null ? 0 : this.getTmimage().hashCode());
		result = 37 * result
				+ (getTmimageid() == null ? 0 : this.getTmimageid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelServHotelRoomImageView specialInit() {
	
		
		return this;
	}
	public RelServHotelRoomImageView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServHotelRoomImageView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelServHotelRoomImageView initList() {

		return this;
	}
	
	public RelServHotelRoomImageView initDicts() {
		return this;
	}
	
	
}