/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelServHotelDocDocumentsView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "docdocumentsid"
			, "servhotelid" 
})
@Entity
@Table(name="rel_serv_hotel_doc_documents_view")
public class RelServHotelDocDocumentsView extends SView  {

	private static final long serialVersionUID = 4123591683159885L;

	private Integer id;
	private String docdocuments;
	private Integer docdocumentsid;
	private String servhotel;
	private Integer servhotelid;

	public RelServHotelDocDocumentsView() {
	}

	public RelServHotelDocDocumentsView(Integer id, String docdocuments,
			Integer docdocumentsid, String servhotel, Integer servhotelid) {
		this.id = id;
		this.docdocuments = docdocuments;
		this.docdocumentsid = docdocumentsid;
		this.servhotel = servhotel;
		this.servhotelid = servhotelid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="docdocuments")
	public String getDocdocuments() {
		return this.docdocuments;
	}

	public void setDocdocuments(String docdocuments) {
		this.docdocuments = docdocuments;
	}

	@Column(name="docdocumentsid")
	public Integer getDocdocumentsid() {
		return this.docdocumentsid;
	}

	public void setDocdocumentsid(Integer docdocumentsid) {
		this.docdocumentsid = docdocumentsid;
	}

	@Column(name="servhotel")
	public String getServhotel() {
		return this.servhotel;
	}

	public void setServhotel(String servhotel) {
		this.servhotel = servhotel;
	}

	@Column(name="servhotelid")
	public Integer getServhotelid() {
		return this.servhotelid;
	}

	public void setServhotelid(Integer servhotelid) {
		this.servhotelid = servhotelid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelServHotelDocDocumentsView))
			return false;
		RelServHotelDocDocumentsView castOther = (RelServHotelDocDocumentsView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDocdocuments() == castOther.getDocdocuments()) || (this
						.getDocdocuments() != null
						&& castOther.getDocdocuments() != null && this
						.getDocdocuments().equals(castOther.getDocdocuments())))
				&& ((this.getDocdocumentsid() == castOther.getDocdocumentsid()) || (this
						.getDocdocumentsid() != null
						&& castOther.getDocdocumentsid() != null && this
						.getDocdocumentsid().equals(
								castOther.getDocdocumentsid())))
				&& ((this.getServhotel() == castOther.getServhotel()) || (this
						.getServhotel() != null
						&& castOther.getServhotel() != null && this
						.getServhotel().equals(castOther.getServhotel())))
				&& ((this.getServhotelid() == castOther.getServhotelid()) || (this
						.getServhotelid() != null
						&& castOther.getServhotelid() != null && this
						.getServhotelid().equals(castOther.getServhotelid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getDocdocuments() == null ? 0 : this.getDocdocuments()
						.hashCode());
		result = 37
				* result
				+ (getDocdocumentsid() == null ? 0 : this.getDocdocumentsid()
						.hashCode());
		result = 37 * result
				+ (getServhotel() == null ? 0 : this.getServhotel().hashCode());
		result = 37
				* result
				+ (getServhotelid() == null ? 0 : this.getServhotelid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelServHotelDocDocumentsView specialInit() {
	
		
		return this;
	}
	public RelServHotelDocDocumentsView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServHotelDocDocumentsView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelServHotelDocDocumentsView initList() {

		return this;
	}
	
	public RelServHotelDocDocumentsView initDicts() {
		return this;
	}
	
	
}