/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelShopPermissionView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "infopermissionid"
			, "shoppermissionid" 
})
@Entity
@Table(name="rel_shop_permission_view")
public class RelShopPermissionView extends SView  {

	private static final long serialVersionUID = 3887957447453119L;

	private Integer id;
	private String infopermission;
	private Integer infopermissionid;
	private String shoppermission;
	private Integer shoppermissionid;

	public RelShopPermissionView() {
	}

	public RelShopPermissionView(Integer id, String infopermission,
			Integer infopermissionid, String shoppermission,
			Integer shoppermissionid) {
		this.id = id;
		this.infopermission = infopermission;
		this.infopermissionid = infopermissionid;
		this.shoppermission = shoppermission;
		this.shoppermissionid = shoppermissionid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="infopermission")
	public String getInfopermission() {
		return this.infopermission;
	}

	public void setInfopermission(String infopermission) {
		this.infopermission = infopermission;
	}

	@Column(name="infopermissionid")
	public Integer getInfopermissionid() {
		return this.infopermissionid;
	}

	public void setInfopermissionid(Integer infopermissionid) {
		this.infopermissionid = infopermissionid;
	}

	@Column(name="shoppermission")
	public String getShoppermission() {
		return this.shoppermission;
	}

	public void setShoppermission(String shoppermission) {
		this.shoppermission = shoppermission;
	}

	@Column(name="shoppermissionid")
	public Integer getShoppermissionid() {
		return this.shoppermissionid;
	}

	public void setShoppermissionid(Integer shoppermissionid) {
		this.shoppermissionid = shoppermissionid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelShopPermissionView))
			return false;
		RelShopPermissionView castOther = (RelShopPermissionView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getInfopermission() == castOther.getInfopermission()) || (this
						.getInfopermission() != null
						&& castOther.getInfopermission() != null && this
						.getInfopermission().equals(
								castOther.getInfopermission())))
				&& ((this.getInfopermissionid() == castOther
						.getInfopermissionid()) || (this.getInfopermissionid() != null
						&& castOther.getInfopermissionid() != null && this
						.getInfopermissionid().equals(
								castOther.getInfopermissionid())))
				&& ((this.getShoppermission() == castOther.getShoppermission()) || (this
						.getShoppermission() != null
						&& castOther.getShoppermission() != null && this
						.getShoppermission().equals(
								castOther.getShoppermission())))
				&& ((this.getShoppermissionid() == castOther
						.getShoppermissionid()) || (this.getShoppermissionid() != null
						&& castOther.getShoppermissionid() != null && this
						.getShoppermissionid().equals(
								castOther.getShoppermissionid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getInfopermission() == null ? 0 : this.getInfopermission()
						.hashCode());
		result = 37
				* result
				+ (getInfopermissionid() == null ? 0 : this
						.getInfopermissionid().hashCode());
		result = 37
				* result
				+ (getShoppermission() == null ? 0 : this.getShoppermission()
						.hashCode());
		result = 37
				* result
				+ (getShoppermissionid() == null ? 0 : this
						.getShoppermissionid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelShopPermissionView specialInit() {
	
		
		return this;
	}
	public RelShopPermissionView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelShopPermissionView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelShopPermissionView initList() {

		return this;
	}
	
	public RelShopPermissionView initDicts() {
		return this;
	}
	
	
}