/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelServHotelImageView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "servhotelid"
			, "tmimageid" 
})
@Entity
@Table(name="rel_serv_hotel_image_view")
public class RelServHotelImageView extends SView  {

	private static final long serialVersionUID = 2711592384799389L;

	private Integer id;
	private String servhotel;
	private Integer servhotelid;
	@JsonProperty("image") private String tmimage;
	private Integer tmimageid;

	public RelServHotelImageView() {
	}

	public RelServHotelImageView(Integer id, String servhotel,
			Integer servhotelid, String tmimage, Integer tmimageid) {
		this.id = id;
		this.servhotel = servhotel;
		this.servhotelid = servhotelid;
		this.tmimage = tmimage;
		this.tmimageid = tmimageid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="servhotel")
	public String getServhotel() {
		return this.servhotel;
	}

	public void setServhotel(String servhotel) {
		this.servhotel = servhotel;
	}

	@Column(name="servhotelid")
	public Integer getServhotelid() {
		return this.servhotelid;
	}

	public void setServhotelid(Integer servhotelid) {
		this.servhotelid = servhotelid;
	}

	@Column(name="tmimage")
	public String getTmimage() {
		return this.tmimage;
	}

	public void setTmimage(String tmimage) {
		this.tmimage = tmimage;
	}

	@Column(name="tmimageid")
	public Integer getTmimageid() {
		return this.tmimageid;
	}

	public void setTmimageid(Integer tmimageid) {
		this.tmimageid = tmimageid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelServHotelImageView))
			return false;
		RelServHotelImageView castOther = (RelServHotelImageView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getServhotel() == castOther.getServhotel()) || (this
						.getServhotel() != null
						&& castOther.getServhotel() != null && this
						.getServhotel().equals(castOther.getServhotel())))
				&& ((this.getServhotelid() == castOther.getServhotelid()) || (this
						.getServhotelid() != null
						&& castOther.getServhotelid() != null && this
						.getServhotelid().equals(castOther.getServhotelid())))
				&& ((this.getTmimage() == castOther.getTmimage()) || (this
						.getTmimage() != null && castOther.getTmimage() != null && this
						.getTmimage().equals(castOther.getTmimage())))
				&& ((this.getTmimageid() == castOther.getTmimageid()) || (this
						.getTmimageid() != null
						&& castOther.getTmimageid() != null && this
						.getTmimageid().equals(castOther.getTmimageid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getServhotel() == null ? 0 : this.getServhotel().hashCode());
		result = 37
				* result
				+ (getServhotelid() == null ? 0 : this.getServhotelid()
						.hashCode());
		result = 37 * result
				+ (getTmimage() == null ? 0 : this.getTmimage().hashCode());
		result = 37 * result
				+ (getTmimageid() == null ? 0 : this.getTmimageid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelServHotelImageView specialInit() {
	
		
		return this;
	}
	public RelServHotelImageView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServHotelImageView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelServHotelImageView initList() {

		return this;
	}
	
	public RelServHotelImageView initDicts() {
		return this;
	}
	
	
}