/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelServTransferTmContactView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "servtransferid"
			, "tmcontactid" 
})
@Entity
@Table(name="rel_serv_transfer_tm_contact_view")
public class RelServTransferTmContactView extends SView  {

	private static final long serialVersionUID = 4587433563186482L;

	private Integer id;
	private String servtransfer;
	private Integer servtransferid;
	private String tmcontact;
	private Integer tmcontactid;

	public RelServTransferTmContactView() {
	}

	public RelServTransferTmContactView(Integer id, String servtransfer,
			Integer servtransferid, String tmcontact, Integer tmcontactid) {
		this.id = id;
		this.servtransfer = servtransfer;
		this.servtransferid = servtransferid;
		this.tmcontact = tmcontact;
		this.tmcontactid = tmcontactid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="servtransfer")
	public String getServtransfer() {
		return this.servtransfer;
	}

	public void setServtransfer(String servtransfer) {
		this.servtransfer = servtransfer;
	}

	@Column(name="servtransferid")
	public Integer getServtransferid() {
		return this.servtransferid;
	}

	public void setServtransferid(Integer servtransferid) {
		this.servtransferid = servtransferid;
	}

	@Column(name="tmcontact")
	public String getTmcontact() {
		return this.tmcontact;
	}

	public void setTmcontact(String tmcontact) {
		this.tmcontact = tmcontact;
	}

	@Column(name="tmcontactid")
	public Integer getTmcontactid() {
		return this.tmcontactid;
	}

	public void setTmcontactid(Integer tmcontactid) {
		this.tmcontactid = tmcontactid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelServTransferTmContactView))
			return false;
		RelServTransferTmContactView castOther = (RelServTransferTmContactView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getServtransfer() == castOther.getServtransfer()) || (this
						.getServtransfer() != null
						&& castOther.getServtransfer() != null && this
						.getServtransfer().equals(castOther.getServtransfer())))
				&& ((this.getServtransferid() == castOther.getServtransferid()) || (this
						.getServtransferid() != null
						&& castOther.getServtransferid() != null && this
						.getServtransferid().equals(
								castOther.getServtransferid())))
				&& ((this.getTmcontact() == castOther.getTmcontact()) || (this
						.getTmcontact() != null
						&& castOther.getTmcontact() != null && this
						.getTmcontact().equals(castOther.getTmcontact())))
				&& ((this.getTmcontactid() == castOther.getTmcontactid()) || (this
						.getTmcontactid() != null
						&& castOther.getTmcontactid() != null && this
						.getTmcontactid().equals(castOther.getTmcontactid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getServtransfer() == null ? 0 : this.getServtransfer()
						.hashCode());
		result = 37
				* result
				+ (getServtransferid() == null ? 0 : this.getServtransferid()
						.hashCode());
		result = 37 * result
				+ (getTmcontact() == null ? 0 : this.getTmcontact().hashCode());
		result = 37
				* result
				+ (getTmcontactid() == null ? 0 : this.getTmcontactid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelServTransferTmContactView specialInit() {
	
		
		return this;
	}
	public RelServTransferTmContactView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelServTransferTmContactView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelServTransferTmContactView initList() {

		return this;
	}
	
	public RelServTransferTmContactView initDicts() {
		return this;
	}
	
	
}