/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * RelUserDetailsView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "userdetailid"
			, "usersid" 
})
@Entity
@Table(name="rel_user_details_view")
public class RelUserDetailsView extends SView  {

	private static final long serialVersionUID = 3787316297457327L;

	private Integer id;
	private String userdetail;
	private Integer userdetailid;
	private String users;
	private Integer usersid;
	private String usersusercolor;

	public RelUserDetailsView() {
	}

	public RelUserDetailsView(Integer id, String userdetail,
			Integer userdetailid, String users, Integer usersid,
			String usersusercolor) {
		this.id = id;
		this.userdetail = userdetail;
		this.userdetailid = userdetailid;
		this.users = users;
		this.usersid = usersid;
		this.usersusercolor = usersusercolor;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="userdetail")
	public String getUserdetail() {
		return this.userdetail;
	}

	public void setUserdetail(String userdetail) {
		this.userdetail = userdetail;
	}

	@Column(name="userdetailid")
	public Integer getUserdetailid() {
		return this.userdetailid;
	}

	public void setUserdetailid(Integer userdetailid) {
		this.userdetailid = userdetailid;
	}

	@Column(name="users")
	public String getUsers() {
		return this.users;
	}

	public void setUsers(String users) {
		this.users = users;
	}

	@Column(name="usersid")
	public Integer getUsersid() {
		return this.usersid;
	}

	public void setUsersid(Integer usersid) {
		this.usersid = usersid;
	}

	@Column(name="usersusercolor")
	public String getUsersusercolor() {
		return this.usersusercolor;
	}

	public void setUsersusercolor(String usersusercolor) {
		this.usersusercolor = usersusercolor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelUserDetailsView))
			return false;
		RelUserDetailsView castOther = (RelUserDetailsView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getUserdetail() == castOther.getUserdetail()) || (this
						.getUserdetail() != null
						&& castOther.getUserdetail() != null && this
						.getUserdetail().equals(castOther.getUserdetail())))
				&& ((this.getUserdetailid() == castOther.getUserdetailid()) || (this
						.getUserdetailid() != null
						&& castOther.getUserdetailid() != null && this
						.getUserdetailid().equals(castOther.getUserdetailid())))
				&& ((this.getUsers() == castOther.getUsers()) || (this
						.getUsers() != null && castOther.getUsers() != null && this
						.getUsers().equals(castOther.getUsers())))
				&& ((this.getUsersid() == castOther.getUsersid()) || (this
						.getUsersid() != null && castOther.getUsersid() != null && this
						.getUsersid().equals(castOther.getUsersid())))
				&& ((this.getUsersusercolor() == castOther.getUsersusercolor()) || (this
						.getUsersusercolor() != null
						&& castOther.getUsersusercolor() != null && this
						.getUsersusercolor().equals(
								castOther.getUsersusercolor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getUserdetail() == null ? 0 : this.getUserdetail()
						.hashCode());
		result = 37
				* result
				+ (getUserdetailid() == null ? 0 : this.getUserdetailid()
						.hashCode());
		result = 37 * result
				+ (getUsers() == null ? 0 : this.getUsers().hashCode());
		result = 37 * result
				+ (getUsersid() == null ? 0 : this.getUsersid().hashCode());
		result = 37
				* result
				+ (getUsersusercolor() == null ? 0 : this.getUsersusercolor()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelUserDetailsView specialInit() {
	
		
		return this;
	}
	public RelUserDetailsView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelUserDetailsView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelUserDetailsView initList() {

		return this;
	}
	
	public RelUserDetailsView initDicts() {
		return this;
	}
	
	
}