/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ReqServHotelProcessedView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "docdocumentsbydocumentforuserid"
			, "docdocumentsbydocumentforhotelid"
			, "paymentpriceid"
			, "paymenttariffid"
			, "servhotelid"
			, "servhotelroomid"
			, "usersbyrequestuserid"
			, "usersbyresponseuserid" 
})
@Entity
@Table(name="req_serv_hotel_processed_view")
public class ReqServHotelProcessedView extends SView  {

	private static final long serialVersionUID = 8766495121632632L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private Boolean accept;
	private String datedifference;
	private Boolean decline;
	private Date departure;
	private String descr;
	private Boolean paymenttype;
	private BigDecimal price;
	private Integer progress;
	private Date race;
	private Integer roomcount;
	private Integer singleprice;
	private String tariffcurrency;
	private String requestnumber;
	private Boolean cancel;
	private Boolean confirm;
	private Boolean archived;
	private Integer popularity;
	private String docdocumentsbydocumentforuser;
	private Integer docdocumentsbydocumentforuserid;
	private String docdocumentsbydocumentforhotel;
	private Integer docdocumentsbydocumentforhotelid;
	private String paymentprice;
	private Integer paymentpriceid;
	private String paymenttariff;
	private Integer paymenttariffid;
	private String servhotel;
	private Integer servhotelid;
	private String servhotelroom;
	private Integer servhotelroomid;
	private String usersbyrequestuser;
	private Integer usersbyrequestuserid;
	private String usersbyrequestuserusercolor;
	private String usersbyresponseuser;
	private Integer usersbyresponseuserid;
	private String usersbyresponseuserusercolor;

	public ReqServHotelProcessedView() {
	}

	public ReqServHotelProcessedView(Integer id, Integer version,
			String createdby, Date createon, Integer firm,
			String lastmodifiedby, Date modifyon, String serieskey,
			String label, Boolean accept, String datedifference,
			Boolean decline, Date departure, String descr, Boolean paymenttype,
			BigDecimal price, Integer progress, Date race, Integer roomcount,
			Integer singleprice, String tariffcurrency, String requestnumber,
			Boolean cancel, Boolean confirm, Boolean archived,
			Integer popularity, String docdocumentsbydocumentforuser,
			Integer docdocumentsbydocumentforuserid,
			String docdocumentsbydocumentforhotel,
			Integer docdocumentsbydocumentforhotelid, String paymentprice,
			Integer paymentpriceid, String paymenttariff,
			Integer paymenttariffid, String servhotel, Integer servhotelid,
			String servhotelroom, Integer servhotelroomid,
			String usersbyrequestuser, Integer usersbyrequestuserid,
			String usersbyrequestuserusercolor, String usersbyresponseuser,
			Integer usersbyresponseuserid, String usersbyresponseuserusercolor) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.accept = accept;
		this.datedifference = datedifference;
		this.decline = decline;
		this.departure = departure;
		this.descr = descr;
		this.paymenttype = paymenttype;
		this.price = price;
		this.progress = progress;
		this.race = race;
		this.roomcount = roomcount;
		this.singleprice = singleprice;
		this.tariffcurrency = tariffcurrency;
		this.requestnumber = requestnumber;
		this.cancel = cancel;
		this.confirm = confirm;
		this.archived = archived;
		this.popularity = popularity;
		this.docdocumentsbydocumentforuser = docdocumentsbydocumentforuser;
		this.docdocumentsbydocumentforuserid = docdocumentsbydocumentforuserid;
		this.docdocumentsbydocumentforhotel = docdocumentsbydocumentforhotel;
		this.docdocumentsbydocumentforhotelid = docdocumentsbydocumentforhotelid;
		this.paymentprice = paymentprice;
		this.paymentpriceid = paymentpriceid;
		this.paymenttariff = paymenttariff;
		this.paymenttariffid = paymenttariffid;
		this.servhotel = servhotel;
		this.servhotelid = servhotelid;
		this.servhotelroom = servhotelroom;
		this.servhotelroomid = servhotelroomid;
		this.usersbyrequestuser = usersbyrequestuser;
		this.usersbyrequestuserid = usersbyrequestuserid;
		this.usersbyrequestuserusercolor = usersbyrequestuserusercolor;
		this.usersbyresponseuser = usersbyresponseuser;
		this.usersbyresponseuserid = usersbyresponseuserid;
		this.usersbyresponseuserusercolor = usersbyresponseuserusercolor;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="accept")
	public Boolean getAccept() {
		return this.accept;
	}

	public void setAccept(Boolean accept) {
		this.accept = accept;
	}

	@Column(name="datedifference")
	public String getDatedifference() {
		return this.datedifference;
	}

	public void setDatedifference(String datedifference) {
		this.datedifference = datedifference;
	}

	@Column(name="decline")
	public Boolean getDecline() {
		return this.decline;
	}

	public void setDecline(Boolean decline) {
		this.decline = decline;
	}

	@Column(name="departure", length = 29)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="paymenttype")
	public Boolean getPaymenttype() {
		return this.paymenttype;
	}

	public void setPaymenttype(Boolean paymenttype) {
		this.paymenttype = paymenttype;
	}

	@Column(name="price", precision = 17, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name="progress")
	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

	@Column(name="race", length = 29)
	public Date getRace() {
		return this.race;
	}

	public void setRace(Date race) {
		this.race = race;
	}

	@Column(name="roomcount")
	public Integer getRoomcount() {
		return this.roomcount;
	}

	public void setRoomcount(Integer roomcount) {
		this.roomcount = roomcount;
	}

	@Column(name="singleprice")
	public Integer getSingleprice() {
		return this.singleprice;
	}

	public void setSingleprice(Integer singleprice) {
		this.singleprice = singleprice;
	}

	@Column(name="tariffcurrency")
	public String getTariffcurrency() {
		return this.tariffcurrency;
	}

	public void setTariffcurrency(String tariffcurrency) {
		this.tariffcurrency = tariffcurrency;
	}

	@Column(name="requestnumber")
	public String getRequestnumber() {
		return this.requestnumber;
	}

	public void setRequestnumber(String requestnumber) {
		this.requestnumber = requestnumber;
	}

	@Column(name="cancel")
	public Boolean getCancel() {
		return this.cancel;
	}

	public void setCancel(Boolean cancel) {
		this.cancel = cancel;
	}

	@Column(name="confirm")
	public Boolean getConfirm() {
		return this.confirm;
	}

	public void setConfirm(Boolean confirm) {
		this.confirm = confirm;
	}

	@Column(name="archived")
	public Boolean getArchived() {
		return this.archived;
	}

	public void setArchived(Boolean archived) {
		this.archived = archived;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="docdocumentsbydocumentforuser")
	public String getDocdocumentsbydocumentforuser() {
		return this.docdocumentsbydocumentforuser;
	}

	public void setDocdocumentsbydocumentforuser(
			String docdocumentsbydocumentforuser) {
		this.docdocumentsbydocumentforuser = docdocumentsbydocumentforuser;
	}

	@Column(name="docdocumentsbydocumentforuserid")
	public Integer getDocdocumentsbydocumentforuserid() {
		return this.docdocumentsbydocumentforuserid;
	}

	public void setDocdocumentsbydocumentforuserid(
			Integer docdocumentsbydocumentforuserid) {
		this.docdocumentsbydocumentforuserid = docdocumentsbydocumentforuserid;
	}

	@Column(name="docdocumentsbydocumentforhotel")
	public String getDocdocumentsbydocumentforhotel() {
		return this.docdocumentsbydocumentforhotel;
	}

	public void setDocdocumentsbydocumentforhotel(
			String docdocumentsbydocumentforhotel) {
		this.docdocumentsbydocumentforhotel = docdocumentsbydocumentforhotel;
	}

	@Column(name="docdocumentsbydocumentforhotelid")
	public Integer getDocdocumentsbydocumentforhotelid() {
		return this.docdocumentsbydocumentforhotelid;
	}

	public void setDocdocumentsbydocumentforhotelid(
			Integer docdocumentsbydocumentforhotelid) {
		this.docdocumentsbydocumentforhotelid = docdocumentsbydocumentforhotelid;
	}

	@Column(name="paymentprice")
	public String getPaymentprice() {
		return this.paymentprice;
	}

	public void setPaymentprice(String paymentprice) {
		this.paymentprice = paymentprice;
	}

	@Column(name="paymentpriceid")
	public Integer getPaymentpriceid() {
		return this.paymentpriceid;
	}

	public void setPaymentpriceid(Integer paymentpriceid) {
		this.paymentpriceid = paymentpriceid;
	}

	@Column(name="paymenttariff")
	public String getPaymenttariff() {
		return this.paymenttariff;
	}

	public void setPaymenttariff(String paymenttariff) {
		this.paymenttariff = paymenttariff;
	}

	@Column(name="paymenttariffid")
	public Integer getPaymenttariffid() {
		return this.paymenttariffid;
	}

	public void setPaymenttariffid(Integer paymenttariffid) {
		this.paymenttariffid = paymenttariffid;
	}

	@Column(name="servhotel")
	public String getServhotel() {
		return this.servhotel;
	}

	public void setServhotel(String servhotel) {
		this.servhotel = servhotel;
	}

	@Column(name="servhotelid")
	public Integer getServhotelid() {
		return this.servhotelid;
	}

	public void setServhotelid(Integer servhotelid) {
		this.servhotelid = servhotelid;
	}

	@Column(name="servhotelroom")
	public String getServhotelroom() {
		return this.servhotelroom;
	}

	public void setServhotelroom(String servhotelroom) {
		this.servhotelroom = servhotelroom;
	}

	@Column(name="servhotelroomid")
	public Integer getServhotelroomid() {
		return this.servhotelroomid;
	}

	public void setServhotelroomid(Integer servhotelroomid) {
		this.servhotelroomid = servhotelroomid;
	}

	@Column(name="usersbyrequestuser")
	public String getUsersbyrequestuser() {
		return this.usersbyrequestuser;
	}

	public void setUsersbyrequestuser(String usersbyrequestuser) {
		this.usersbyrequestuser = usersbyrequestuser;
	}

	@Column(name="usersbyrequestuserid")
	public Integer getUsersbyrequestuserid() {
		return this.usersbyrequestuserid;
	}

	public void setUsersbyrequestuserid(Integer usersbyrequestuserid) {
		this.usersbyrequestuserid = usersbyrequestuserid;
	}

	@Column(name="usersbyrequestuserusercolor")
	public String getUsersbyrequestuserusercolor() {
		return this.usersbyrequestuserusercolor;
	}

	public void setUsersbyrequestuserusercolor(
			String usersbyrequestuserusercolor) {
		this.usersbyrequestuserusercolor = usersbyrequestuserusercolor;
	}

	@Column(name="usersbyresponseuser")
	public String getUsersbyresponseuser() {
		return this.usersbyresponseuser;
	}

	public void setUsersbyresponseuser(String usersbyresponseuser) {
		this.usersbyresponseuser = usersbyresponseuser;
	}

	@Column(name="usersbyresponseuserid")
	public Integer getUsersbyresponseuserid() {
		return this.usersbyresponseuserid;
	}

	public void setUsersbyresponseuserid(Integer usersbyresponseuserid) {
		this.usersbyresponseuserid = usersbyresponseuserid;
	}

	@Column(name="usersbyresponseuserusercolor")
	public String getUsersbyresponseuserusercolor() {
		return this.usersbyresponseuserusercolor;
	}

	public void setUsersbyresponseuserusercolor(
			String usersbyresponseuserusercolor) {
		this.usersbyresponseuserusercolor = usersbyresponseuserusercolor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReqServHotelProcessedView))
			return false;
		ReqServHotelProcessedView castOther = (ReqServHotelProcessedView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getAccept() == castOther.getAccept()) || (this
						.getAccept() != null && castOther.getAccept() != null && this
						.getAccept().equals(castOther.getAccept())))
				&& ((this.getDatedifference() == castOther.getDatedifference()) || (this
						.getDatedifference() != null
						&& castOther.getDatedifference() != null && this
						.getDatedifference().equals(
								castOther.getDatedifference())))
				&& ((this.getDecline() == castOther.getDecline()) || (this
						.getDecline() != null && castOther.getDecline() != null && this
						.getDecline().equals(castOther.getDecline())))
				&& ((this.getDeparture() == castOther.getDeparture()) || (this
						.getDeparture() != null
						&& castOther.getDeparture() != null && this
						.getDeparture().equals(castOther.getDeparture())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getPaymenttype() == castOther.getPaymenttype()) || (this
						.getPaymenttype() != null
						&& castOther.getPaymenttype() != null && this
						.getPaymenttype().equals(castOther.getPaymenttype())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getProgress() == castOther.getProgress()) || (this
						.getProgress() != null
						&& castOther.getProgress() != null && this
						.getProgress().equals(castOther.getProgress())))
				&& ((this.getRace() == castOther.getRace()) || (this.getRace() != null
						&& castOther.getRace() != null && this.getRace()
						.equals(castOther.getRace())))
				&& ((this.getRoomcount() == castOther.getRoomcount()) || (this
						.getRoomcount() != null
						&& castOther.getRoomcount() != null && this
						.getRoomcount().equals(castOther.getRoomcount())))
				&& ((this.getSingleprice() == castOther.getSingleprice()) || (this
						.getSingleprice() != null
						&& castOther.getSingleprice() != null && this
						.getSingleprice().equals(castOther.getSingleprice())))
				&& ((this.getTariffcurrency() == castOther.getTariffcurrency()) || (this
						.getTariffcurrency() != null
						&& castOther.getTariffcurrency() != null && this
						.getTariffcurrency().equals(
								castOther.getTariffcurrency())))
				&& ((this.getRequestnumber() == castOther.getRequestnumber()) || (this
						.getRequestnumber() != null
						&& castOther.getRequestnumber() != null && this
						.getRequestnumber()
						.equals(castOther.getRequestnumber())))
				&& ((this.getCancel() == castOther.getCancel()) || (this
						.getCancel() != null && castOther.getCancel() != null && this
						.getCancel().equals(castOther.getCancel())))
				&& ((this.getConfirm() == castOther.getConfirm()) || (this
						.getConfirm() != null && castOther.getConfirm() != null && this
						.getConfirm().equals(castOther.getConfirm())))
				&& ((this.getArchived() == castOther.getArchived()) || (this
						.getArchived() != null
						&& castOther.getArchived() != null && this
						.getArchived().equals(castOther.getArchived())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getDocdocumentsbydocumentforuser() == castOther
						.getDocdocumentsbydocumentforuser()) || (this
						.getDocdocumentsbydocumentforuser() != null
						&& castOther.getDocdocumentsbydocumentforuser() != null && this
						.getDocdocumentsbydocumentforuser().equals(
								castOther.getDocdocumentsbydocumentforuser())))
				&& ((this.getDocdocumentsbydocumentforuserid() == castOther
						.getDocdocumentsbydocumentforuserid()) || (this
						.getDocdocumentsbydocumentforuserid() != null
						&& castOther.getDocdocumentsbydocumentforuserid() != null && this
						.getDocdocumentsbydocumentforuserid().equals(
								castOther.getDocdocumentsbydocumentforuserid())))
				&& ((this.getDocdocumentsbydocumentforhotel() == castOther
						.getDocdocumentsbydocumentforhotel()) || (this
						.getDocdocumentsbydocumentforhotel() != null
						&& castOther.getDocdocumentsbydocumentforhotel() != null && this
						.getDocdocumentsbydocumentforhotel().equals(
								castOther.getDocdocumentsbydocumentforhotel())))
				&& ((this.getDocdocumentsbydocumentforhotelid() == castOther
						.getDocdocumentsbydocumentforhotelid()) || (this
						.getDocdocumentsbydocumentforhotelid() != null
						&& castOther.getDocdocumentsbydocumentforhotelid() != null && this
						.getDocdocumentsbydocumentforhotelid()
						.equals(castOther.getDocdocumentsbydocumentforhotelid())))
				&& ((this.getPaymentprice() == castOther.getPaymentprice()) || (this
						.getPaymentprice() != null
						&& castOther.getPaymentprice() != null && this
						.getPaymentprice().equals(castOther.getPaymentprice())))
				&& ((this.getPaymentpriceid() == castOther.getPaymentpriceid()) || (this
						.getPaymentpriceid() != null
						&& castOther.getPaymentpriceid() != null && this
						.getPaymentpriceid().equals(
								castOther.getPaymentpriceid())))
				&& ((this.getPaymenttariff() == castOther.getPaymenttariff()) || (this
						.getPaymenttariff() != null
						&& castOther.getPaymenttariff() != null && this
						.getPaymenttariff()
						.equals(castOther.getPaymenttariff())))
				&& ((this.getPaymenttariffid() == castOther
						.getPaymenttariffid()) || (this.getPaymenttariffid() != null
						&& castOther.getPaymenttariffid() != null && this
						.getPaymenttariffid().equals(
								castOther.getPaymenttariffid())))
				&& ((this.getServhotel() == castOther.getServhotel()) || (this
						.getServhotel() != null
						&& castOther.getServhotel() != null && this
						.getServhotel().equals(castOther.getServhotel())))
				&& ((this.getServhotelid() == castOther.getServhotelid()) || (this
						.getServhotelid() != null
						&& castOther.getServhotelid() != null && this
						.getServhotelid().equals(castOther.getServhotelid())))
				&& ((this.getServhotelroom() == castOther.getServhotelroom()) || (this
						.getServhotelroom() != null
						&& castOther.getServhotelroom() != null && this
						.getServhotelroom()
						.equals(castOther.getServhotelroom())))
				&& ((this.getServhotelroomid() == castOther
						.getServhotelroomid()) || (this.getServhotelroomid() != null
						&& castOther.getServhotelroomid() != null && this
						.getServhotelroomid().equals(
								castOther.getServhotelroomid())))
				&& ((this.getUsersbyrequestuser() == castOther
						.getUsersbyrequestuser()) || (this
						.getUsersbyrequestuser() != null
						&& castOther.getUsersbyrequestuser() != null && this
						.getUsersbyrequestuser().equals(
								castOther.getUsersbyrequestuser())))
				&& ((this.getUsersbyrequestuserid() == castOther
						.getUsersbyrequestuserid()) || (this
						.getUsersbyrequestuserid() != null
						&& castOther.getUsersbyrequestuserid() != null && this
						.getUsersbyrequestuserid().equals(
								castOther.getUsersbyrequestuserid())))
				&& ((this.getUsersbyrequestuserusercolor() == castOther
						.getUsersbyrequestuserusercolor()) || (this
						.getUsersbyrequestuserusercolor() != null
						&& castOther.getUsersbyrequestuserusercolor() != null && this
						.getUsersbyrequestuserusercolor().equals(
								castOther.getUsersbyrequestuserusercolor())))
				&& ((this.getUsersbyresponseuser() == castOther
						.getUsersbyresponseuser()) || (this
						.getUsersbyresponseuser() != null
						&& castOther.getUsersbyresponseuser() != null && this
						.getUsersbyresponseuser().equals(
								castOther.getUsersbyresponseuser())))
				&& ((this.getUsersbyresponseuserid() == castOther
						.getUsersbyresponseuserid()) || (this
						.getUsersbyresponseuserid() != null
						&& castOther.getUsersbyresponseuserid() != null && this
						.getUsersbyresponseuserid().equals(
								castOther.getUsersbyresponseuserid())))
				&& ((this.getUsersbyresponseuserusercolor() == castOther
						.getUsersbyresponseuserusercolor()) || (this
						.getUsersbyresponseuserusercolor() != null
						&& castOther.getUsersbyresponseuserusercolor() != null && this
						.getUsersbyresponseuserusercolor().equals(
								castOther.getUsersbyresponseuserusercolor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getAccept() == null ? 0 : this.getAccept().hashCode());
		result = 37
				* result
				+ (getDatedifference() == null ? 0 : this.getDatedifference()
						.hashCode());
		result = 37 * result
				+ (getDecline() == null ? 0 : this.getDecline().hashCode());
		result = 37 * result
				+ (getDeparture() == null ? 0 : this.getDeparture().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getPaymenttype() == null ? 0 : this.getPaymenttype()
						.hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result
				+ (getProgress() == null ? 0 : this.getProgress().hashCode());
		result = 37 * result
				+ (getRace() == null ? 0 : this.getRace().hashCode());
		result = 37 * result
				+ (getRoomcount() == null ? 0 : this.getRoomcount().hashCode());
		result = 37
				* result
				+ (getSingleprice() == null ? 0 : this.getSingleprice()
						.hashCode());
		result = 37
				* result
				+ (getTariffcurrency() == null ? 0 : this.getTariffcurrency()
						.hashCode());
		result = 37
				* result
				+ (getRequestnumber() == null ? 0 : this.getRequestnumber()
						.hashCode());
		result = 37 * result
				+ (getCancel() == null ? 0 : this.getCancel().hashCode());
		result = 37 * result
				+ (getConfirm() == null ? 0 : this.getConfirm().hashCode());
		result = 37 * result
				+ (getArchived() == null ? 0 : this.getArchived().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getDocdocumentsbydocumentforuser() == null ? 0 : this
						.getDocdocumentsbydocumentforuser().hashCode());
		result = 37
				* result
				+ (getDocdocumentsbydocumentforuserid() == null ? 0 : this
						.getDocdocumentsbydocumentforuserid().hashCode());
		result = 37
				* result
				+ (getDocdocumentsbydocumentforhotel() == null ? 0 : this
						.getDocdocumentsbydocumentforhotel().hashCode());
		result = 37
				* result
				+ (getDocdocumentsbydocumentforhotelid() == null ? 0 : this
						.getDocdocumentsbydocumentforhotelid().hashCode());
		result = 37
				* result
				+ (getPaymentprice() == null ? 0 : this.getPaymentprice()
						.hashCode());
		result = 37
				* result
				+ (getPaymentpriceid() == null ? 0 : this.getPaymentpriceid()
						.hashCode());
		result = 37
				* result
				+ (getPaymenttariff() == null ? 0 : this.getPaymenttariff()
						.hashCode());
		result = 37
				* result
				+ (getPaymenttariffid() == null ? 0 : this.getPaymenttariffid()
						.hashCode());
		result = 37 * result
				+ (getServhotel() == null ? 0 : this.getServhotel().hashCode());
		result = 37
				* result
				+ (getServhotelid() == null ? 0 : this.getServhotelid()
						.hashCode());
		result = 37
				* result
				+ (getServhotelroom() == null ? 0 : this.getServhotelroom()
						.hashCode());
		result = 37
				* result
				+ (getServhotelroomid() == null ? 0 : this.getServhotelroomid()
						.hashCode());
		result = 37
				* result
				+ (getUsersbyrequestuser() == null ? 0 : this
						.getUsersbyrequestuser().hashCode());
		result = 37
				* result
				+ (getUsersbyrequestuserid() == null ? 0 : this
						.getUsersbyrequestuserid().hashCode());
		result = 37
				* result
				+ (getUsersbyrequestuserusercolor() == null ? 0 : this
						.getUsersbyrequestuserusercolor().hashCode());
		result = 37
				* result
				+ (getUsersbyresponseuser() == null ? 0 : this
						.getUsersbyresponseuser().hashCode());
		result = 37
				* result
				+ (getUsersbyresponseuserid() == null ? 0 : this
						.getUsersbyresponseuserid().hashCode());
		result = 37
				* result
				+ (getUsersbyresponseuserusercolor() == null ? 0 : this
						.getUsersbyresponseuserusercolor().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ReqServHotelProcessedView specialInit() {
	
		
		return this;
	}
	public ReqServHotelProcessedView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ReqServHotelProcessedView customInitList(List<String> list) {
		
		return this;
	}
	
	public ReqServHotelProcessedView initList() {

		return this;
	}
	
	public ReqServHotelProcessedView initDicts() {
		return this;
	}
	
	
}