/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ServHotelView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "infocontactinformationid"
			, "locationaddressid"
			, "locationcitiesid"
			, "locationcountriesid"
			, "paymentdetailsid" 
})
@Entity
@Table(name="serv_hotel_view")
public class ServHotelView extends SView  {

	private static final long serialVersionUID = 1332355113219268L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private Boolean blacklist;
	private String conditiontext;
	private String descr;
	private String descrinternal;
	private Boolean favorite;
	private Boolean freesale;
	private Boolean problem;
	private Boolean showonline;
	private Integer starcount;
	private String synopsis;
	private String timedeparture;
	private String timeearlyrace;
	private String timelatedeparture;
	private String timerace;
	private String whereroomsarebooked;
	private Integer popularity;
	private String infocontactinformation;
	private Integer infocontactinformationid;
	private String locationaddress;
	private Integer locationaddressid;
	private String locationcities;
	private Integer locationcitiesid;
	private String locationcountries;
	private Integer locationcountriesid;
	private String paymentdetails;
	private Integer paymentdetailsid;

	private List<RelServHotelImageView> relServHotelImages = new LinkedList<RelServHotelImageView>();
	private List<RelServHotelDocDocumentsView> relServHotelDocDocumentses = new LinkedList<RelServHotelDocDocumentsView>();
	private List<ReqServHotelView> reqServHotels = new LinkedList<ReqServHotelView>();
	private List<ServHotelRoomView> servHotelRooms = new LinkedList<ServHotelRoomView>();
	
	public ServHotelView() {
	}

	public ServHotelView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String label, Boolean blacklist,
			String conditiontext, String descr, String descrinternal,
			Boolean favorite, Boolean freesale, Boolean problem,
			Boolean showonline, Integer starcount, String synopsis,
			String timedeparture, String timeearlyrace,
			String timelatedeparture, String timerace,
			String whereroomsarebooked, Integer popularity,
			String infocontactinformation, Integer infocontactinformationid,
			String locationaddress, Integer locationaddressid,
			String locationcities, Integer locationcitiesid,
			String locationcountries, Integer locationcountriesid,
			String paymentdetails, Integer paymentdetailsid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.blacklist = blacklist;
		this.conditiontext = conditiontext;
		this.descr = descr;
		this.descrinternal = descrinternal;
		this.favorite = favorite;
		this.freesale = freesale;
		this.problem = problem;
		this.showonline = showonline;
		this.starcount = starcount;
		this.synopsis = synopsis;
		this.timedeparture = timedeparture;
		this.timeearlyrace = timeearlyrace;
		this.timelatedeparture = timelatedeparture;
		this.timerace = timerace;
		this.whereroomsarebooked = whereroomsarebooked;
		this.popularity = popularity;
		this.infocontactinformation = infocontactinformation;
		this.infocontactinformationid = infocontactinformationid;
		this.locationaddress = locationaddress;
		this.locationaddressid = locationaddressid;
		this.locationcities = locationcities;
		this.locationcitiesid = locationcitiesid;
		this.locationcountries = locationcountries;
		this.locationcountriesid = locationcountriesid;
		this.paymentdetails = paymentdetails;
		this.paymentdetailsid = paymentdetailsid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="blacklist")
	public Boolean getBlacklist() {
		return this.blacklist;
	}

	public void setBlacklist(Boolean blacklist) {
		this.blacklist = blacklist;
	}

	@Column(name="conditiontext", length = 2000)
	public String getConditiontext() {
		return this.conditiontext;
	}

	public void setConditiontext(String conditiontext) {
		this.conditiontext = conditiontext;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="descrinternal", length = 2000)
	public String getDescrinternal() {
		return this.descrinternal;
	}

	public void setDescrinternal(String descrinternal) {
		this.descrinternal = descrinternal;
	}

	@Column(name="favorite")
	public Boolean getFavorite() {
		return this.favorite;
	}

	public void setFavorite(Boolean favorite) {
		this.favorite = favorite;
	}

	@Column(name="freesale")
	public Boolean getFreesale() {
		return this.freesale;
	}

	public void setFreesale(Boolean freesale) {
		this.freesale = freesale;
	}

	@Column(name="problem")
	public Boolean getProblem() {
		return this.problem;
	}

	public void setProblem(Boolean problem) {
		this.problem = problem;
	}

	@Column(name="showonline")
	public Boolean getShowonline() {
		return this.showonline;
	}

	public void setShowonline(Boolean showonline) {
		this.showonline = showonline;
	}

	@Column(name="starcount")
	public Integer getStarcount() {
		return this.starcount;
	}

	public void setStarcount(Integer starcount) {
		this.starcount = starcount;
	}

	@Column(name="synopsis", length = 500)
	public String getSynopsis() {
		return this.synopsis;
	}

	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}

	@Column(name="timedeparture")
	public String getTimedeparture() {
		return this.timedeparture;
	}

	public void setTimedeparture(String timedeparture) {
		this.timedeparture = timedeparture;
	}

	@Column(name="timeearlyrace")
	public String getTimeearlyrace() {
		return this.timeearlyrace;
	}

	public void setTimeearlyrace(String timeearlyrace) {
		this.timeearlyrace = timeearlyrace;
	}

	@Column(name="timelatedeparture")
	public String getTimelatedeparture() {
		return this.timelatedeparture;
	}

	public void setTimelatedeparture(String timelatedeparture) {
		this.timelatedeparture = timelatedeparture;
	}

	@Column(name="timerace")
	public String getTimerace() {
		return this.timerace;
	}

	public void setTimerace(String timerace) {
		this.timerace = timerace;
	}

	@Column(name="whereroomsarebooked")
	public String getWhereroomsarebooked() {
		return this.whereroomsarebooked;
	}

	public void setWhereroomsarebooked(String whereroomsarebooked) {
		this.whereroomsarebooked = whereroomsarebooked;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="infocontactinformation")
	public String getInfocontactinformation() {
		return this.infocontactinformation;
	}

	public void setInfocontactinformation(String infocontactinformation) {
		this.infocontactinformation = infocontactinformation;
	}

	@Column(name="infocontactinformationid")
	public Integer getInfocontactinformationid() {
		return this.infocontactinformationid;
	}

	public void setInfocontactinformationid(Integer infocontactinformationid) {
		this.infocontactinformationid = infocontactinformationid;
	}

	@Column(name="locationaddress")
	public String getLocationaddress() {
		return this.locationaddress;
	}

	public void setLocationaddress(String locationaddress) {
		this.locationaddress = locationaddress;
	}

	@Column(name="locationaddressid")
	public Integer getLocationaddressid() {
		return this.locationaddressid;
	}

	public void setLocationaddressid(Integer locationaddressid) {
		this.locationaddressid = locationaddressid;
	}

	@Column(name="locationcities")
	public String getLocationcities() {
		return this.locationcities;
	}

	public void setLocationcities(String locationcities) {
		this.locationcities = locationcities;
	}

	@Column(name="locationcitiesid")
	public Integer getLocationcitiesid() {
		return this.locationcitiesid;
	}

	public void setLocationcitiesid(Integer locationcitiesid) {
		this.locationcitiesid = locationcitiesid;
	}

	@Column(name="locationcountries")
	public String getLocationcountries() {
		return this.locationcountries;
	}

	public void setLocationcountries(String locationcountries) {
		this.locationcountries = locationcountries;
	}

	@Column(name="locationcountriesid")
	public Integer getLocationcountriesid() {
		return this.locationcountriesid;
	}

	public void setLocationcountriesid(Integer locationcountriesid) {
		this.locationcountriesid = locationcountriesid;
	}

	@Column(name="paymentdetails")
	public String getPaymentdetails() {
		return this.paymentdetails;
	}

	public void setPaymentdetails(String paymentdetails) {
		this.paymentdetails = paymentdetails;
	}

	@Column(name="paymentdetailsid")
	public Integer getPaymentdetailsid() {
		return this.paymentdetailsid;
	}

	public void setPaymentdetailsid(Integer paymentdetailsid) {
		this.paymentdetailsid = paymentdetailsid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelid")
	public List<RelServHotelImageView> getRelServHotelImages() {
		return this.relServHotelImages;
	}

	public void setRelServHotelImages(List<RelServHotelImageView> relServHotelImages) {
		this.relServHotelImages = relServHotelImages;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelid")
	public List<RelServHotelDocDocumentsView> getRelServHotelDocDocumentses() {
		return this.relServHotelDocDocumentses;
	}

	public void setRelServHotelDocDocumentses(List<RelServHotelDocDocumentsView> relServHotelDocDocumentses) {
		this.relServHotelDocDocumentses = relServHotelDocDocumentses;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelid")
	public List<ReqServHotelView> getReqServHotels() {
		return this.reqServHotels;
	}

	public void setReqServHotels(List<ReqServHotelView> reqServHotels) {
		this.reqServHotels = reqServHotels;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelid")
	public List<ServHotelRoomView> getServHotelRooms() {
		return this.servHotelRooms;
	}

	public void setServHotelRooms(List<ServHotelRoomView> servHotelRooms) {
		this.servHotelRooms = servHotelRooms;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServHotelView))
			return false;
		ServHotelView castOther = (ServHotelView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getBlacklist() == castOther.getBlacklist()) || (this
						.getBlacklist() != null
						&& castOther.getBlacklist() != null && this
						.getBlacklist().equals(castOther.getBlacklist())))
				&& ((this.getConditiontext() == castOther.getConditiontext()) || (this
						.getConditiontext() != null
						&& castOther.getConditiontext() != null && this
						.getConditiontext()
						.equals(castOther.getConditiontext())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getDescrinternal() == castOther.getDescrinternal()) || (this
						.getDescrinternal() != null
						&& castOther.getDescrinternal() != null && this
						.getDescrinternal()
						.equals(castOther.getDescrinternal())))
				&& ((this.getFavorite() == castOther.getFavorite()) || (this
						.getFavorite() != null
						&& castOther.getFavorite() != null && this
						.getFavorite().equals(castOther.getFavorite())))
				&& ((this.getFreesale() == castOther.getFreesale()) || (this
						.getFreesale() != null
						&& castOther.getFreesale() != null && this
						.getFreesale().equals(castOther.getFreesale())))
				&& ((this.getProblem() == castOther.getProblem()) || (this
						.getProblem() != null && castOther.getProblem() != null && this
						.getProblem().equals(castOther.getProblem())))
				&& ((this.getShowonline() == castOther.getShowonline()) || (this
						.getShowonline() != null
						&& castOther.getShowonline() != null && this
						.getShowonline().equals(castOther.getShowonline())))
				&& ((this.getStarcount() == castOther.getStarcount()) || (this
						.getStarcount() != null
						&& castOther.getStarcount() != null && this
						.getStarcount().equals(castOther.getStarcount())))
				&& ((this.getSynopsis() == castOther.getSynopsis()) || (this
						.getSynopsis() != null
						&& castOther.getSynopsis() != null && this
						.getSynopsis().equals(castOther.getSynopsis())))
				&& ((this.getTimedeparture() == castOther.getTimedeparture()) || (this
						.getTimedeparture() != null
						&& castOther.getTimedeparture() != null && this
						.getTimedeparture()
						.equals(castOther.getTimedeparture())))
				&& ((this.getTimeearlyrace() == castOther.getTimeearlyrace()) || (this
						.getTimeearlyrace() != null
						&& castOther.getTimeearlyrace() != null && this
						.getTimeearlyrace()
						.equals(castOther.getTimeearlyrace())))
				&& ((this.getTimelatedeparture() == castOther
						.getTimelatedeparture()) || (this
						.getTimelatedeparture() != null
						&& castOther.getTimelatedeparture() != null && this
						.getTimelatedeparture().equals(
								castOther.getTimelatedeparture())))
				&& ((this.getTimerace() == castOther.getTimerace()) || (this
						.getTimerace() != null
						&& castOther.getTimerace() != null && this
						.getTimerace().equals(castOther.getTimerace())))
				&& ((this.getWhereroomsarebooked() == castOther
						.getWhereroomsarebooked()) || (this
						.getWhereroomsarebooked() != null
						&& castOther.getWhereroomsarebooked() != null && this
						.getWhereroomsarebooked().equals(
								castOther.getWhereroomsarebooked())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getInfocontactinformation() == castOther
						.getInfocontactinformation()) || (this
						.getInfocontactinformation() != null
						&& castOther.getInfocontactinformation() != null && this
						.getInfocontactinformation().equals(
								castOther.getInfocontactinformation())))
				&& ((this.getInfocontactinformationid() == castOther
						.getInfocontactinformationid()) || (this
						.getInfocontactinformationid() != null
						&& castOther.getInfocontactinformationid() != null && this
						.getInfocontactinformationid().equals(
								castOther.getInfocontactinformationid())))
				&& ((this.getLocationaddress() == castOther
						.getLocationaddress()) || (this.getLocationaddress() != null
						&& castOther.getLocationaddress() != null && this
						.getLocationaddress().equals(
								castOther.getLocationaddress())))
				&& ((this.getLocationaddressid() == castOther
						.getLocationaddressid()) || (this
						.getLocationaddressid() != null
						&& castOther.getLocationaddressid() != null && this
						.getLocationaddressid().equals(
								castOther.getLocationaddressid())))
				&& ((this.getLocationcities() == castOther.getLocationcities()) || (this
						.getLocationcities() != null
						&& castOther.getLocationcities() != null && this
						.getLocationcities().equals(
								castOther.getLocationcities())))
				&& ((this.getLocationcitiesid() == castOther
						.getLocationcitiesid()) || (this.getLocationcitiesid() != null
						&& castOther.getLocationcitiesid() != null && this
						.getLocationcitiesid().equals(
								castOther.getLocationcitiesid())))
				&& ((this.getLocationcountries() == castOther
						.getLocationcountries()) || (this
						.getLocationcountries() != null
						&& castOther.getLocationcountries() != null && this
						.getLocationcountries().equals(
								castOther.getLocationcountries())))
				&& ((this.getLocationcountriesid() == castOther
						.getLocationcountriesid()) || (this
						.getLocationcountriesid() != null
						&& castOther.getLocationcountriesid() != null && this
						.getLocationcountriesid().equals(
								castOther.getLocationcountriesid())))
				&& ((this.getPaymentdetails() == castOther.getPaymentdetails()) || (this
						.getPaymentdetails() != null
						&& castOther.getPaymentdetails() != null && this
						.getPaymentdetails().equals(
								castOther.getPaymentdetails())))
				&& ((this.getPaymentdetailsid() == castOther
						.getPaymentdetailsid()) || (this.getPaymentdetailsid() != null
						&& castOther.getPaymentdetailsid() != null && this
						.getPaymentdetailsid().equals(
								castOther.getPaymentdetailsid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getBlacklist() == null ? 0 : this.getBlacklist().hashCode());
		result = 37
				* result
				+ (getConditiontext() == null ? 0 : this.getConditiontext()
						.hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getDescrinternal() == null ? 0 : this.getDescrinternal()
						.hashCode());
		result = 37 * result
				+ (getFavorite() == null ? 0 : this.getFavorite().hashCode());
		result = 37 * result
				+ (getFreesale() == null ? 0 : this.getFreesale().hashCode());
		result = 37 * result
				+ (getProblem() == null ? 0 : this.getProblem().hashCode());
		result = 37
				* result
				+ (getShowonline() == null ? 0 : this.getShowonline()
						.hashCode());
		result = 37 * result
				+ (getStarcount() == null ? 0 : this.getStarcount().hashCode());
		result = 37 * result
				+ (getSynopsis() == null ? 0 : this.getSynopsis().hashCode());
		result = 37
				* result
				+ (getTimedeparture() == null ? 0 : this.getTimedeparture()
						.hashCode());
		result = 37
				* result
				+ (getTimeearlyrace() == null ? 0 : this.getTimeearlyrace()
						.hashCode());
		result = 37
				* result
				+ (getTimelatedeparture() == null ? 0 : this
						.getTimelatedeparture().hashCode());
		result = 37 * result
				+ (getTimerace() == null ? 0 : this.getTimerace().hashCode());
		result = 37
				* result
				+ (getWhereroomsarebooked() == null ? 0 : this
						.getWhereroomsarebooked().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getInfocontactinformation() == null ? 0 : this
						.getInfocontactinformation().hashCode());
		result = 37
				* result
				+ (getInfocontactinformationid() == null ? 0 : this
						.getInfocontactinformationid().hashCode());
		result = 37
				* result
				+ (getLocationaddress() == null ? 0 : this.getLocationaddress()
						.hashCode());
		result = 37
				* result
				+ (getLocationaddressid() == null ? 0 : this
						.getLocationaddressid().hashCode());
		result = 37
				* result
				+ (getLocationcities() == null ? 0 : this.getLocationcities()
						.hashCode());
		result = 37
				* result
				+ (getLocationcitiesid() == null ? 0 : this
						.getLocationcitiesid().hashCode());
		result = 37
				* result
				+ (getLocationcountries() == null ? 0 : this
						.getLocationcountries().hashCode());
		result = 37
				* result
				+ (getLocationcountriesid() == null ? 0 : this
						.getLocationcountriesid().hashCode());
		result = 37
				* result
				+ (getPaymentdetails() == null ? 0 : this.getPaymentdetails()
						.hashCode());
		result = 37
				* result
				+ (getPaymentdetailsid() == null ? 0 : this
						.getPaymentdetailsid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ServHotelView specialInit() {
	
		
		return this;
	}
	public ServHotelView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ServHotelView customInitList(List<String> list) {
		if (list.contains("relServHotelImages")) {
			initLists(relServHotelImages);
		}
		if (list.contains("relServHotelDocDocumentses")) {
			initLists(relServHotelDocDocumentses);
		}
		if (list.contains("reqServHotels")) {
			initLists(reqServHotels);
		}
		if (list.contains("servHotelRooms")) {
			initLists(servHotelRooms);
		}
		return this;
	}
	
	public ServHotelView initList() {
		initLists(relServHotelImages);
		initLists(relServHotelDocDocumentses);
		initLists(reqServHotels);
		initLists(servHotelRooms);

		return this;
	}
	
	public ServHotelView initDicts() {
		return this;
	}
	
	
}