/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ServHotelRoomView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "dictglobalid"
			, "paymenttariffbycosttarriffid"
			, "paymenttariffbyrrtarriffid"
			, "paymenttariffshopid"
			, "servhotelid" 
})
@Entity
@Table(name="serv_hotel_room_view")
public class ServHotelRoomView extends SView  {

	private static final long serialVersionUID = 2358717176813342L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private Boolean breakfast;
	private String descr;
	private Integer guestnumber;
	private Integer roomnumber;
	private Boolean dinner;
	private Boolean lunch;
	private Integer discount;
	private Boolean isdiscount;
	private Integer commission;
	private Integer fresale;
	private Integer fresaletoday;
	private Boolean fresaleenabled;
	private Date fresalestart;
	private Date fresaleend;
	private Boolean iscommission;
	private Integer popularity;
	private String dictglobal;
	private Integer dictglobalid;
	private String paymenttariffbycosttarriff;
	private Integer paymenttariffbycosttarriffid;
	private String paymenttariffbyrrtarriff;
	private Integer paymenttariffbyrrtarriffid;
	private String paymenttariffshop;
	private Integer paymenttariffshopid;
	private String servhotel;
	private Integer servhotelid;

	private List<ReqServHotelView> reqServHotels = new LinkedList<ReqServHotelView>();
	private List<RelServHotelRoomImageView> relServHotelRoomImages = new LinkedList<RelServHotelRoomImageView>();
	
	public ServHotelRoomView() {
	}

	public ServHotelRoomView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String label, Boolean breakfast, String descr,
			Integer guestnumber, Integer roomnumber, Boolean dinner,
			Boolean lunch, Integer discount, Boolean isdiscount,
			Integer commission, Integer fresale, Integer fresaletoday,
			Boolean fresaleenabled, Date fresalestart, Date fresaleend,
			Boolean iscommission, Integer popularity, String dictglobal,
			Integer dictglobalid, String paymenttariffbycosttarriff,
			Integer paymenttariffbycosttarriffid,
			String paymenttariffbyrrtarriff,
			Integer paymenttariffbyrrtarriffid, String paymenttariffshop,
			Integer paymenttariffshopid, String servhotel, Integer servhotelid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.breakfast = breakfast;
		this.descr = descr;
		this.guestnumber = guestnumber;
		this.roomnumber = roomnumber;
		this.dinner = dinner;
		this.lunch = lunch;
		this.discount = discount;
		this.isdiscount = isdiscount;
		this.commission = commission;
		this.fresale = fresale;
		this.fresaletoday = fresaletoday;
		this.fresaleenabled = fresaleenabled;
		this.fresalestart = fresalestart;
		this.fresaleend = fresaleend;
		this.iscommission = iscommission;
		this.popularity = popularity;
		this.dictglobal = dictglobal;
		this.dictglobalid = dictglobalid;
		this.paymenttariffbycosttarriff = paymenttariffbycosttarriff;
		this.paymenttariffbycosttarriffid = paymenttariffbycosttarriffid;
		this.paymenttariffbyrrtarriff = paymenttariffbyrrtarriff;
		this.paymenttariffbyrrtarriffid = paymenttariffbyrrtarriffid;
		this.paymenttariffshop = paymenttariffshop;
		this.paymenttariffshopid = paymenttariffshopid;
		this.servhotel = servhotel;
		this.servhotelid = servhotelid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="breakfast")
	public Boolean getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(Boolean breakfast) {
		this.breakfast = breakfast;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="guestnumber")
	public Integer getGuestnumber() {
		return this.guestnumber;
	}

	public void setGuestnumber(Integer guestnumber) {
		this.guestnumber = guestnumber;
	}

	@Column(name="roomnumber")
	public Integer getRoomnumber() {
		return this.roomnumber;
	}

	public void setRoomnumber(Integer roomnumber) {
		this.roomnumber = roomnumber;
	}

	@Column(name="dinner")
	public Boolean getDinner() {
		return this.dinner;
	}

	public void setDinner(Boolean dinner) {
		this.dinner = dinner;
	}

	@Column(name="lunch")
	public Boolean getLunch() {
		return this.lunch;
	}

	public void setLunch(Boolean lunch) {
		this.lunch = lunch;
	}

	@Column(name="discount")
	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@Column(name="isdiscount")
	public Boolean getIsdiscount() {
		return this.isdiscount;
	}

	public void setIsdiscount(Boolean isdiscount) {
		this.isdiscount = isdiscount;
	}

	@Column(name="commission")
	public Integer getCommission() {
		return this.commission;
	}

	public void setCommission(Integer commission) {
		this.commission = commission;
	}

	@Column(name="fresale")
	public Integer getFresale() {
		return this.fresale;
	}

	public void setFresale(Integer fresale) {
		this.fresale = fresale;
	}

	@Column(name="fresaletoday")
	public Integer getFresaletoday() {
		return this.fresaletoday;
	}

	public void setFresaletoday(Integer fresaletoday) {
		this.fresaletoday = fresaletoday;
	}

	@Column(name="fresaleenabled")
	public Boolean getFresaleenabled() {
		return this.fresaleenabled;
	}

	public void setFresaleenabled(Boolean fresaleenabled) {
		this.fresaleenabled = fresaleenabled;
	}

	@Column(name="fresalestart", length = 29)
	public Date getFresalestart() {
		return this.fresalestart;
	}

	public void setFresalestart(Date fresalestart) {
		this.fresalestart = fresalestart;
	}

	@Column(name="fresaleend", length = 29)
	public Date getFresaleend() {
		return this.fresaleend;
	}

	public void setFresaleend(Date fresaleend) {
		this.fresaleend = fresaleend;
	}

	@Column(name="iscommission")
	public Boolean getIscommission() {
		return this.iscommission;
	}

	public void setIscommission(Boolean iscommission) {
		this.iscommission = iscommission;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="dictglobal")
	public String getDictglobal() {
		return this.dictglobal;
	}

	public void setDictglobal(String dictglobal) {
		this.dictglobal = dictglobal;
	}

	@Column(name="dictglobalid")
	public Integer getDictglobalid() {
		return this.dictglobalid;
	}

	public void setDictglobalid(Integer dictglobalid) {
		this.dictglobalid = dictglobalid;
	}

	@Column(name="paymenttariffbycosttarriff")
	public String getPaymenttariffbycosttarriff() {
		return this.paymenttariffbycosttarriff;
	}

	public void setPaymenttariffbycosttarriff(String paymenttariffbycosttarriff) {
		this.paymenttariffbycosttarriff = paymenttariffbycosttarriff;
	}

	@Column(name="paymenttariffbycosttarriffid")
	public Integer getPaymenttariffbycosttarriffid() {
		return this.paymenttariffbycosttarriffid;
	}

	public void setPaymenttariffbycosttarriffid(
			Integer paymenttariffbycosttarriffid) {
		this.paymenttariffbycosttarriffid = paymenttariffbycosttarriffid;
	}

	@Column(name="paymenttariffbyrrtarriff")
	public String getPaymenttariffbyrrtarriff() {
		return this.paymenttariffbyrrtarriff;
	}

	public void setPaymenttariffbyrrtarriff(String paymenttariffbyrrtarriff) {
		this.paymenttariffbyrrtarriff = paymenttariffbyrrtarriff;
	}

	@Column(name="paymenttariffbyrrtarriffid")
	public Integer getPaymenttariffbyrrtarriffid() {
		return this.paymenttariffbyrrtarriffid;
	}

	public void setPaymenttariffbyrrtarriffid(Integer paymenttariffbyrrtarriffid) {
		this.paymenttariffbyrrtarriffid = paymenttariffbyrrtarriffid;
	}

	@Column(name="paymenttariffshop")
	public String getPaymenttariffshop() {
		return this.paymenttariffshop;
	}

	public void setPaymenttariffshop(String paymenttariffshop) {
		this.paymenttariffshop = paymenttariffshop;
	}

	@Column(name="paymenttariffshopid")
	public Integer getPaymenttariffshopid() {
		return this.paymenttariffshopid;
	}

	public void setPaymenttariffshopid(Integer paymenttariffshopid) {
		this.paymenttariffshopid = paymenttariffshopid;
	}

	@Column(name="servhotel")
	public String getServhotel() {
		return this.servhotel;
	}

	public void setServhotel(String servhotel) {
		this.servhotel = servhotel;
	}

	@Column(name="servhotelid")
	public Integer getServhotelid() {
		return this.servhotelid;
	}

	public void setServhotelid(Integer servhotelid) {
		this.servhotelid = servhotelid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelroomid")
	public List<ReqServHotelView> getReqServHotels() {
		return this.reqServHotels;
	}

	public void setReqServHotels(List<ReqServHotelView> reqServHotels) {
		this.reqServHotels = reqServHotels;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelroomid")
	public List<RelServHotelRoomImageView> getRelServHotelRoomImages() {
		return this.relServHotelRoomImages;
	}

	public void setRelServHotelRoomImages(List<RelServHotelRoomImageView> relServHotelRoomImages) {
		this.relServHotelRoomImages = relServHotelRoomImages;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServHotelRoomView))
			return false;
		ServHotelRoomView castOther = (ServHotelRoomView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getBreakfast() == castOther.getBreakfast()) || (this
						.getBreakfast() != null
						&& castOther.getBreakfast() != null && this
						.getBreakfast().equals(castOther.getBreakfast())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getGuestnumber() == castOther.getGuestnumber()) || (this
						.getGuestnumber() != null
						&& castOther.getGuestnumber() != null && this
						.getGuestnumber().equals(castOther.getGuestnumber())))
				&& ((this.getRoomnumber() == castOther.getRoomnumber()) || (this
						.getRoomnumber() != null
						&& castOther.getRoomnumber() != null && this
						.getRoomnumber().equals(castOther.getRoomnumber())))
				&& ((this.getDinner() == castOther.getDinner()) || (this
						.getDinner() != null && castOther.getDinner() != null && this
						.getDinner().equals(castOther.getDinner())))
				&& ((this.getLunch() == castOther.getLunch()) || (this
						.getLunch() != null && castOther.getLunch() != null && this
						.getLunch().equals(castOther.getLunch())))
				&& ((this.getDiscount() == castOther.getDiscount()) || (this
						.getDiscount() != null
						&& castOther.getDiscount() != null && this
						.getDiscount().equals(castOther.getDiscount())))
				&& ((this.getIsdiscount() == castOther.getIsdiscount()) || (this
						.getIsdiscount() != null
						&& castOther.getIsdiscount() != null && this
						.getIsdiscount().equals(castOther.getIsdiscount())))
				&& ((this.getCommission() == castOther.getCommission()) || (this
						.getCommission() != null
						&& castOther.getCommission() != null && this
						.getCommission().equals(castOther.getCommission())))
				&& ((this.getFresale() == castOther.getFresale()) || (this
						.getFresale() != null && castOther.getFresale() != null && this
						.getFresale().equals(castOther.getFresale())))
				&& ((this.getFresaletoday() == castOther.getFresaletoday()) || (this
						.getFresaletoday() != null
						&& castOther.getFresaletoday() != null && this
						.getFresaletoday().equals(castOther.getFresaletoday())))
				&& ((this.getFresaleenabled() == castOther.getFresaleenabled()) || (this
						.getFresaleenabled() != null
						&& castOther.getFresaleenabled() != null && this
						.getFresaleenabled().equals(
								castOther.getFresaleenabled())))
				&& ((this.getFresalestart() == castOther.getFresalestart()) || (this
						.getFresalestart() != null
						&& castOther.getFresalestart() != null && this
						.getFresalestart().equals(castOther.getFresalestart())))
				&& ((this.getFresaleend() == castOther.getFresaleend()) || (this
						.getFresaleend() != null
						&& castOther.getFresaleend() != null && this
						.getFresaleend().equals(castOther.getFresaleend())))
				&& ((this.getIscommission() == castOther.getIscommission()) || (this
						.getIscommission() != null
						&& castOther.getIscommission() != null && this
						.getIscommission().equals(castOther.getIscommission())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getDictglobal() == castOther.getDictglobal()) || (this
						.getDictglobal() != null
						&& castOther.getDictglobal() != null && this
						.getDictglobal().equals(castOther.getDictglobal())))
				&& ((this.getDictglobalid() == castOther.getDictglobalid()) || (this
						.getDictglobalid() != null
						&& castOther.getDictglobalid() != null && this
						.getDictglobalid().equals(castOther.getDictglobalid())))
				&& ((this.getPaymenttariffbycosttarriff() == castOther
						.getPaymenttariffbycosttarriff()) || (this
						.getPaymenttariffbycosttarriff() != null
						&& castOther.getPaymenttariffbycosttarriff() != null && this
						.getPaymenttariffbycosttarriff().equals(
								castOther.getPaymenttariffbycosttarriff())))
				&& ((this.getPaymenttariffbycosttarriffid() == castOther
						.getPaymenttariffbycosttarriffid()) || (this
						.getPaymenttariffbycosttarriffid() != null
						&& castOther.getPaymenttariffbycosttarriffid() != null && this
						.getPaymenttariffbycosttarriffid().equals(
								castOther.getPaymenttariffbycosttarriffid())))
				&& ((this.getPaymenttariffbyrrtarriff() == castOther
						.getPaymenttariffbyrrtarriff()) || (this
						.getPaymenttariffbyrrtarriff() != null
						&& castOther.getPaymenttariffbyrrtarriff() != null && this
						.getPaymenttariffbyrrtarriff().equals(
								castOther.getPaymenttariffbyrrtarriff())))
				&& ((this.getPaymenttariffbyrrtarriffid() == castOther
						.getPaymenttariffbyrrtarriffid()) || (this
						.getPaymenttariffbyrrtarriffid() != null
						&& castOther.getPaymenttariffbyrrtarriffid() != null && this
						.getPaymenttariffbyrrtarriffid().equals(
								castOther.getPaymenttariffbyrrtarriffid())))
				&& ((this.getPaymenttariffshop() == castOther
						.getPaymenttariffshop()) || (this
						.getPaymenttariffshop() != null
						&& castOther.getPaymenttariffshop() != null && this
						.getPaymenttariffshop().equals(
								castOther.getPaymenttariffshop())))
				&& ((this.getPaymenttariffshopid() == castOther
						.getPaymenttariffshopid()) || (this
						.getPaymenttariffshopid() != null
						&& castOther.getPaymenttariffshopid() != null && this
						.getPaymenttariffshopid().equals(
								castOther.getPaymenttariffshopid())))
				&& ((this.getServhotel() == castOther.getServhotel()) || (this
						.getServhotel() != null
						&& castOther.getServhotel() != null && this
						.getServhotel().equals(castOther.getServhotel())))
				&& ((this.getServhotelid() == castOther.getServhotelid()) || (this
						.getServhotelid() != null
						&& castOther.getServhotelid() != null && this
						.getServhotelid().equals(castOther.getServhotelid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getBreakfast() == null ? 0 : this.getBreakfast().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getGuestnumber() == null ? 0 : this.getGuestnumber()
						.hashCode());
		result = 37
				* result
				+ (getRoomnumber() == null ? 0 : this.getRoomnumber()
						.hashCode());
		result = 37 * result
				+ (getDinner() == null ? 0 : this.getDinner().hashCode());
		result = 37 * result
				+ (getLunch() == null ? 0 : this.getLunch().hashCode());
		result = 37 * result
				+ (getDiscount() == null ? 0 : this.getDiscount().hashCode());
		result = 37
				* result
				+ (getIsdiscount() == null ? 0 : this.getIsdiscount()
						.hashCode());
		result = 37
				* result
				+ (getCommission() == null ? 0 : this.getCommission()
						.hashCode());
		result = 37 * result
				+ (getFresale() == null ? 0 : this.getFresale().hashCode());
		result = 37
				* result
				+ (getFresaletoday() == null ? 0 : this.getFresaletoday()
						.hashCode());
		result = 37
				* result
				+ (getFresaleenabled() == null ? 0 : this.getFresaleenabled()
						.hashCode());
		result = 37
				* result
				+ (getFresalestart() == null ? 0 : this.getFresalestart()
						.hashCode());
		result = 37
				* result
				+ (getFresaleend() == null ? 0 : this.getFresaleend()
						.hashCode());
		result = 37
				* result
				+ (getIscommission() == null ? 0 : this.getIscommission()
						.hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getDictglobal() == null ? 0 : this.getDictglobal()
						.hashCode());
		result = 37
				* result
				+ (getDictglobalid() == null ? 0 : this.getDictglobalid()
						.hashCode());
		result = 37
				* result
				+ (getPaymenttariffbycosttarriff() == null ? 0 : this
						.getPaymenttariffbycosttarriff().hashCode());
		result = 37
				* result
				+ (getPaymenttariffbycosttarriffid() == null ? 0 : this
						.getPaymenttariffbycosttarriffid().hashCode());
		result = 37
				* result
				+ (getPaymenttariffbyrrtarriff() == null ? 0 : this
						.getPaymenttariffbyrrtarriff().hashCode());
		result = 37
				* result
				+ (getPaymenttariffbyrrtarriffid() == null ? 0 : this
						.getPaymenttariffbyrrtarriffid().hashCode());
		result = 37
				* result
				+ (getPaymenttariffshop() == null ? 0 : this
						.getPaymenttariffshop().hashCode());
		result = 37
				* result
				+ (getPaymenttariffshopid() == null ? 0 : this
						.getPaymenttariffshopid().hashCode());
		result = 37 * result
				+ (getServhotel() == null ? 0 : this.getServhotel().hashCode());
		result = 37
				* result
				+ (getServhotelid() == null ? 0 : this.getServhotelid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ServHotelRoomView specialInit() {
	
		
		return this;
	}
	public ServHotelRoomView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ServHotelRoomView customInitList(List<String> list) {
		if (list.contains("reqServHotels")) {
			initLists(reqServHotels);
		}
		if (list.contains("relServHotelRoomImages")) {
			initLists(relServHotelRoomImages);
		}
		return this;
	}
	
	public ServHotelRoomView initList() {
		initLists(reqServHotels);
		initLists(relServHotelRoomImages);

		return this;
	}
	
	public ServHotelRoomView initDicts() {
		return this;
	}
	
	
}