/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ServTransferView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "currcurrencyid"
			, "dictglobalbypaymenttypeid"
			, "dictglobalbytypetransferid"
			, "dictglobalbytransportid"
			, "locationcitiesid"
			, "locationcountriesid"
			, "tmaccountid" 
})
@Entity
@Table(name="serv_transfer_view")
public class ServTransferView extends SView  {

	private static final long serialVersionUID = 4959814649676566L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private Date datefrom;
	private Date dateto;
	private String descr;
	private String passengersphones;
	private BigDecimal price;
	private String transfername;
	private String visittable;
	private Integer popularity;
	private String currcurrency;
	private Integer currcurrencyid;
	private String dictglobalbypaymenttype;
	private Integer dictglobalbypaymenttypeid;
	private String dictglobalbytypetransfer;
	private Integer dictglobalbytypetransferid;
	private String dictglobalbytransport;
	private Integer dictglobalbytransportid;
	private String locationcities;
	private Integer locationcitiesid;
	private String locationcountries;
	private Integer locationcountriesid;
	private String tmaccount;
	private Integer tmaccountid;

	private List<RelServTransferTmContactView> relServTransferTmContacts = new LinkedList<RelServTransferTmContactView>();
	private List<ServTransferRouteView> servTransferRoutes = new LinkedList<ServTransferRouteView>();
	
	public ServTransferView() {
	}

	public ServTransferView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String label, Date datefrom, Date dateto,
			String descr, String passengersphones, BigDecimal price,
			String transfername, String visittable, Integer popularity,
			String currcurrency, Integer currcurrencyid,
			String dictglobalbypaymenttype, Integer dictglobalbypaymenttypeid,
			String dictglobalbytypetransfer,
			Integer dictglobalbytypetransferid, String dictglobalbytransport,
			Integer dictglobalbytransportid, String locationcities,
			Integer locationcitiesid, String locationcountries,
			Integer locationcountriesid, String tmaccount, Integer tmaccountid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.datefrom = datefrom;
		this.dateto = dateto;
		this.descr = descr;
		this.passengersphones = passengersphones;
		this.price = price;
		this.transfername=transfername;
		this.visittable = visittable;
		this.popularity = popularity;
		this.currcurrency = currcurrency;
		this.currcurrencyid = currcurrencyid;
		this.dictglobalbypaymenttype = dictglobalbypaymenttype;
		this.dictglobalbypaymenttypeid = dictglobalbypaymenttypeid;
		this.dictglobalbytypetransfer = dictglobalbytypetransfer;
		this.dictglobalbytypetransferid = dictglobalbytypetransferid;
		this.dictglobalbytransport = dictglobalbytransport;
		this.dictglobalbytransportid = dictglobalbytransportid;
		this.locationcities = locationcities;
		this.locationcitiesid = locationcitiesid;
		this.locationcountries = locationcountries;
		this.locationcountriesid = locationcountriesid;
		this.tmaccount = tmaccount;
		this.tmaccountid = tmaccountid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="datefrom", length = 29)
	public Date getDatefrom() {
		return this.datefrom;
	}

	public void setDatefrom(Date datefrom) {
		this.datefrom = datefrom;
	}

	@Column(name="dateto", length = 29)
	public Date getDateto() {
		return this.dateto;
	}

	public void setDateto(Date dateto) {
		this.dateto = dateto;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="passengersphones")
	public String getPassengersphones() {
		return this.passengersphones;
	}

	public void setPassengersphones(String passengersphones) {
		this.passengersphones = passengersphones;
	}

	@Column(name="price", precision = 17, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name="transfername")
	public String getTransfername() {
		return this.transfername;
	}

	public void setTransfername(String transfername) {
		this.transfername=transfername;
	}

	@Column(name="visittable")
	public String getVisittable() {
		return this.visittable;
	}

	public void setVisittable(String visittable) {
		this.visittable = visittable;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="currcurrency")
	public String getCurrcurrency() {
		return this.currcurrency;
	}

	public void setCurrcurrency(String currcurrency) {
		this.currcurrency = currcurrency;
	}

	@Column(name="currcurrencyid")
	public Integer getCurrcurrencyid() {
		return this.currcurrencyid;
	}

	public void setCurrcurrencyid(Integer currcurrencyid) {
		this.currcurrencyid = currcurrencyid;
	}

	@Column(name="dictglobalbypaymenttype")
	public String getDictglobalbypaymenttype() {
		return this.dictglobalbypaymenttype;
	}

	public void setDictglobalbypaymenttype(String dictglobalbypaymenttype) {
		this.dictglobalbypaymenttype = dictglobalbypaymenttype;
	}

	@Column(name="dictglobalbypaymenttypeid")
	public Integer getDictglobalbypaymenttypeid() {
		return this.dictglobalbypaymenttypeid;
	}

	public void setDictglobalbypaymenttypeid(Integer dictglobalbypaymenttypeid) {
		this.dictglobalbypaymenttypeid = dictglobalbypaymenttypeid;
	}

	@Column(name="dictglobalbytypetransfer")
	public String getDictglobalbytypetransfer() {
		return this.dictglobalbytypetransfer;
	}

	public void setDictglobalbytypetransfer(String dictglobalbytypetransfer) {
		this.dictglobalbytypetransfer = dictglobalbytypetransfer;
	}

	@Column(name="dictglobalbytypetransferid")
	public Integer getDictglobalbytypetransferid() {
		return this.dictglobalbytypetransferid;
	}

	public void setDictglobalbytypetransferid(Integer dictglobalbytypetransferid) {
		this.dictglobalbytypetransferid = dictglobalbytypetransferid;
	}

	@Column(name="dictglobalbytransport")
	public String getDictglobalbytransport() {
		return this.dictglobalbytransport;
	}

	public void setDictglobalbytransport(String dictglobalbytransport) {
		this.dictglobalbytransport = dictglobalbytransport;
	}

	@Column(name="dictglobalbytransportid")
	public Integer getDictglobalbytransportid() {
		return this.dictglobalbytransportid;
	}

	public void setDictglobalbytransportid(Integer dictglobalbytransportid) {
		this.dictglobalbytransportid = dictglobalbytransportid;
	}

	@Column(name="locationcities")
	public String getLocationcities() {
		return this.locationcities;
	}

	public void setLocationcities(String locationcities) {
		this.locationcities = locationcities;
	}

	@Column(name="locationcitiesid")
	public Integer getLocationcitiesid() {
		return this.locationcitiesid;
	}

	public void setLocationcitiesid(Integer locationcitiesid) {
		this.locationcitiesid = locationcitiesid;
	}

	@Column(name="locationcountries")
	public String getLocationcountries() {
		return this.locationcountries;
	}

	public void setLocationcountries(String locationcountries) {
		this.locationcountries = locationcountries;
	}

	@Column(name="locationcountriesid")
	public Integer getLocationcountriesid() {
		return this.locationcountriesid;
	}

	public void setLocationcountriesid(Integer locationcountriesid) {
		this.locationcountriesid = locationcountriesid;
	}

	@Column(name="tmaccount")
	public String getTmaccount() {
		return this.tmaccount;
	}

	public void setTmaccount(String tmaccount) {
		this.tmaccount = tmaccount;
	}

	@Column(name="tmaccountid")
	public Integer getTmaccountid() {
		return this.tmaccountid;
	}

	public void setTmaccountid(Integer tmaccountid) {
		this.tmaccountid = tmaccountid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servtransferid")
	public List<RelServTransferTmContactView> getRelServTransferTmContacts() {
		return this.relServTransferTmContacts;
	}

	public void setRelServTransferTmContacts(List<RelServTransferTmContactView> relServTransferTmContacts) {
		this.relServTransferTmContacts = relServTransferTmContacts;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servtransferid")
	public List<ServTransferRouteView> getServTransferRoutes() {
		return this.servTransferRoutes;
	}

	public void setServTransferRoutes(List<ServTransferRouteView> servTransferRoutes) {
		this.servTransferRoutes = servTransferRoutes;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServTransferView))
			return false;
		ServTransferView castOther = (ServTransferView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getDatefrom() == castOther.getDatefrom()) || (this
						.getDatefrom() != null
						&& castOther.getDatefrom() != null && this
						.getDatefrom().equals(castOther.getDatefrom())))
				&& ((this.getDateto() == castOther.getDateto()) || (this
						.getDateto() != null && castOther.getDateto() != null && this
						.getDateto().equals(castOther.getDateto())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getPassengersphones() == castOther
						.getPassengersphones()) || (this.getPassengersphones() != null
						&& castOther.getPassengersphones() != null && this
						.getPassengersphones().equals(
								castOther.getPassengersphones())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getTransfername() == castOther.getTransfername()) || (this
						.getTransfername() != null
						&& castOther.getTransfername() != null && this
						.getTransfername().equals(castOther.getTransfername())))
				&& ((this.getVisittable() == castOther.getVisittable()) || (this
						.getVisittable() != null
						&& castOther.getVisittable() != null && this
						.getVisittable().equals(castOther.getVisittable())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getCurrcurrency() == castOther.getCurrcurrency()) || (this
						.getCurrcurrency() != null
						&& castOther.getCurrcurrency() != null && this
						.getCurrcurrency().equals(castOther.getCurrcurrency())))
				&& ((this.getCurrcurrencyid() == castOther.getCurrcurrencyid()) || (this
						.getCurrcurrencyid() != null
						&& castOther.getCurrcurrencyid() != null && this
						.getCurrcurrencyid().equals(
								castOther.getCurrcurrencyid())))
				&& ((this.getDictglobalbypaymenttype() == castOther
						.getDictglobalbypaymenttype()) || (this
						.getDictglobalbypaymenttype() != null
						&& castOther.getDictglobalbypaymenttype() != null && this
						.getDictglobalbypaymenttype().equals(
								castOther.getDictglobalbypaymenttype())))
				&& ((this.getDictglobalbypaymenttypeid() == castOther
						.getDictglobalbypaymenttypeid()) || (this
						.getDictglobalbypaymenttypeid() != null
						&& castOther.getDictglobalbypaymenttypeid() != null && this
						.getDictglobalbypaymenttypeid().equals(
								castOther.getDictglobalbypaymenttypeid())))
				&& ((this.getDictglobalbytypetransfer() == castOther
						.getDictglobalbytypetransfer()) || (this
						.getDictglobalbytypetransfer() != null
						&& castOther.getDictglobalbytypetransfer() != null && this
						.getDictglobalbytypetransfer().equals(
								castOther.getDictglobalbytypetransfer())))
				&& ((this.getDictglobalbytypetransferid() == castOther
						.getDictglobalbytypetransferid()) || (this
						.getDictglobalbytypetransferid() != null
						&& castOther.getDictglobalbytypetransferid() != null && this
						.getDictglobalbytypetransferid().equals(
								castOther.getDictglobalbytypetransferid())))
				&& ((this.getDictglobalbytransport() == castOther
						.getDictglobalbytransport()) || (this
						.getDictglobalbytransport() != null
						&& castOther.getDictglobalbytransport() != null && this
						.getDictglobalbytransport().equals(
								castOther.getDictglobalbytransport())))
				&& ((this.getDictglobalbytransportid() == castOther
						.getDictglobalbytransportid()) || (this
						.getDictglobalbytransportid() != null
						&& castOther.getDictglobalbytransportid() != null && this
						.getDictglobalbytransportid().equals(
								castOther.getDictglobalbytransportid())))
				&& ((this.getLocationcities() == castOther.getLocationcities()) || (this
						.getLocationcities() != null
						&& castOther.getLocationcities() != null && this
						.getLocationcities().equals(
								castOther.getLocationcities())))
				&& ((this.getLocationcitiesid() == castOther
						.getLocationcitiesid()) || (this.getLocationcitiesid() != null
						&& castOther.getLocationcitiesid() != null && this
						.getLocationcitiesid().equals(
								castOther.getLocationcitiesid())))
				&& ((this.getLocationcountries() == castOther
						.getLocationcountries()) || (this
						.getLocationcountries() != null
						&& castOther.getLocationcountries() != null && this
						.getLocationcountries().equals(
								castOther.getLocationcountries())))
				&& ((this.getLocationcountriesid() == castOther
						.getLocationcountriesid()) || (this
						.getLocationcountriesid() != null
						&& castOther.getLocationcountriesid() != null && this
						.getLocationcountriesid().equals(
								castOther.getLocationcountriesid())))
				&& ((this.getTmaccount() == castOther.getTmaccount()) || (this
						.getTmaccount() != null
						&& castOther.getTmaccount() != null && this
						.getTmaccount().equals(castOther.getTmaccount())))
				&& ((this.getTmaccountid() == castOther.getTmaccountid()) || (this
						.getTmaccountid() != null
						&& castOther.getTmaccountid() != null && this
						.getTmaccountid().equals(castOther.getTmaccountid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getDatefrom() == null ? 0 : this.getDatefrom().hashCode());
		result = 37 * result
				+ (getDateto() == null ? 0 : this.getDateto().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getPassengersphones() == null ? 0 : this
						.getPassengersphones().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37
				* result
				+ (getTransfername() == null ? 0 : this.getTransfername()
						.hashCode());
		result = 37
				* result
				+ (getVisittable() == null ? 0 : this.getVisittable()
						.hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getCurrcurrency() == null ? 0 : this.getCurrcurrency()
						.hashCode());
		result = 37
				* result
				+ (getCurrcurrencyid() == null ? 0 : this.getCurrcurrencyid()
						.hashCode());
		result = 37
				* result
				+ (getDictglobalbypaymenttype() == null ? 0 : this
						.getDictglobalbypaymenttype().hashCode());
		result = 37
				* result
				+ (getDictglobalbypaymenttypeid() == null ? 0 : this
						.getDictglobalbypaymenttypeid().hashCode());
		result = 37
				* result
				+ (getDictglobalbytypetransfer() == null ? 0 : this
						.getDictglobalbytypetransfer().hashCode());
		result = 37
				* result
				+ (getDictglobalbytypetransferid() == null ? 0 : this
						.getDictglobalbytypetransferid().hashCode());
		result = 37
				* result
				+ (getDictglobalbytransport() == null ? 0 : this
						.getDictglobalbytransport().hashCode());
		result = 37
				* result
				+ (getDictglobalbytransportid() == null ? 0 : this
						.getDictglobalbytransportid().hashCode());
		result = 37
				* result
				+ (getLocationcities() == null ? 0 : this.getLocationcities()
						.hashCode());
		result = 37
				* result
				+ (getLocationcitiesid() == null ? 0 : this
						.getLocationcitiesid().hashCode());
		result = 37
				* result
				+ (getLocationcountries() == null ? 0 : this
						.getLocationcountries().hashCode());
		result = 37
				* result
				+ (getLocationcountriesid() == null ? 0 : this
						.getLocationcountriesid().hashCode());
		result = 37 * result
				+ (getTmaccount() == null ? 0 : this.getTmaccount().hashCode());
		result = 37
				* result
				+ (getTmaccountid() == null ? 0 : this.getTmaccountid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ServTransferView specialInit() {
	
		
		return this;
	}
	public ServTransferView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ServTransferView customInitList(List<String> list) {
		if (list.contains("relServTransferTmContacts")) {
			initLists(relServTransferTmContacts);
		}
		if (list.contains("servTransferRoutes")) {
			initLists(servTransferRoutes);
		}
		return this;
	}
	
	public ServTransferView initList() {
		initLists(relServTransferTmContacts);
		initLists(servTransferRoutes);

		return this;
	}
	
	public ServTransferView initDicts() {
		return this;
	}
	
	
}