/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ServTransferRouteView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "currcurrencyid"
			, "servtransferid" 
})
@Entity
@Table(name="serv_transfer_route_view")
public class ServTransferRouteView extends SView  {

	private static final long serialVersionUID = 6569998691767368L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private String descr;
	private String driver;
	private String driverphone;
	private BigDecimal fixedallowance;
	private Boolean free;
	private BigDecimal percentageofallowances;
	private Integer sum;
	private Integer popularity;
	private String currcurrency;
	private Integer currcurrencyid;
	private String servtransfer;
	private Integer servtransferid;

	private List<ServTransferRoutePointView> servTransferRoutePoints = new LinkedList<ServTransferRoutePointView>();
	
	public ServTransferRouteView() {
	}

	public ServTransferRouteView(Integer id, Integer version,
			String createdby, Date createon, Integer firm,
			String lastmodifiedby, Date modifyon, String serieskey,
			String label, String descr, String driver, String driverphone,
			BigDecimal fixedallowance, Boolean free,
			BigDecimal percentageofallowances, Integer sum, Integer popularity,
			String currcurrency, Integer currcurrencyid, String servtransfer,
			Integer servtransferid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.descr = descr;
		this.driver = driver;
		this.driverphone = driverphone;
		this.fixedallowance = fixedallowance;
		this.free = free;
		this.percentageofallowances = percentageofallowances;
		this.sum = sum;
		this.popularity = popularity;
		this.currcurrency = currcurrency;
		this.currcurrencyid = currcurrencyid;
		this.servtransfer = servtransfer;
		this.servtransferid = servtransferid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="driver")
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	@Column(name="driverphone")
	public String getDriverphone() {
		return this.driverphone;
	}

	public void setDriverphone(String driverphone) {
		this.driverphone = driverphone;
	}

	@Column(name="fixedallowance", precision = 17, scale = 3)
	public BigDecimal getFixedallowance() {
		return this.fixedallowance;
	}

	public void setFixedallowance(BigDecimal fixedallowance) {
		this.fixedallowance = fixedallowance;
	}

	@Column(name="free")
	public Boolean getFree() {
		return this.free;
	}

	public void setFree(Boolean free) {
		this.free = free;
	}

	@Column(name="percentageofallowances", precision = 17, scale = 3)
	public BigDecimal getPercentageofallowances() {
		return this.percentageofallowances;
	}

	public void setPercentageofallowances(BigDecimal percentageofallowances) {
		this.percentageofallowances = percentageofallowances;
	}

	@Column(name="sum")
	public Integer getSum() {
		return this.sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="currcurrency")
	public String getCurrcurrency() {
		return this.currcurrency;
	}

	public void setCurrcurrency(String currcurrency) {
		this.currcurrency = currcurrency;
	}

	@Column(name="currcurrencyid")
	public Integer getCurrcurrencyid() {
		return this.currcurrencyid;
	}

	public void setCurrcurrencyid(Integer currcurrencyid) {
		this.currcurrencyid = currcurrencyid;
	}

	@Column(name="servtransfer")
	public String getServtransfer() {
		return this.servtransfer;
	}

	public void setServtransfer(String servtransfer) {
		this.servtransfer = servtransfer;
	}

	@Column(name="servtransferid")
	public Integer getServtransferid() {
		return this.servtransferid;
	}

	public void setServtransferid(Integer servtransferid) {
		this.servtransferid = servtransferid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servtransferrouteid")
	public List<ServTransferRoutePointView> getServTransferRoutePoints() {
		return this.servTransferRoutePoints;
	}

	public void setServTransferRoutePoints(List<ServTransferRoutePointView> servTransferRoutePoints) {
		this.servTransferRoutePoints = servTransferRoutePoints;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServTransferRouteView))
			return false;
		ServTransferRouteView castOther = (ServTransferRouteView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getDriver() == castOther.getDriver()) || (this
						.getDriver() != null && castOther.getDriver() != null && this
						.getDriver().equals(castOther.getDriver())))
				&& ((this.getDriverphone() == castOther.getDriverphone()) || (this
						.getDriverphone() != null
						&& castOther.getDriverphone() != null && this
						.getDriverphone().equals(castOther.getDriverphone())))
				&& ((this.getFixedallowance() == castOther.getFixedallowance()) || (this
						.getFixedallowance() != null
						&& castOther.getFixedallowance() != null && this
						.getFixedallowance().equals(
								castOther.getFixedallowance())))
				&& ((this.getFree() == castOther.getFree()) || (this.getFree() != null
						&& castOther.getFree() != null && this.getFree()
						.equals(castOther.getFree())))
				&& ((this.getPercentageofallowances() == castOther
						.getPercentageofallowances()) || (this
						.getPercentageofallowances() != null
						&& castOther.getPercentageofallowances() != null && this
						.getPercentageofallowances().equals(
								castOther.getPercentageofallowances())))
				&& ((this.getSum() == castOther.getSum()) || (this.getSum() != null
						&& castOther.getSum() != null && this.getSum().equals(
						castOther.getSum())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getCurrcurrency() == castOther.getCurrcurrency()) || (this
						.getCurrcurrency() != null
						&& castOther.getCurrcurrency() != null && this
						.getCurrcurrency().equals(castOther.getCurrcurrency())))
				&& ((this.getCurrcurrencyid() == castOther.getCurrcurrencyid()) || (this
						.getCurrcurrencyid() != null
						&& castOther.getCurrcurrencyid() != null && this
						.getCurrcurrencyid().equals(
								castOther.getCurrcurrencyid())))
				&& ((this.getServtransfer() == castOther.getServtransfer()) || (this
						.getServtransfer() != null
						&& castOther.getServtransfer() != null && this
						.getServtransfer().equals(castOther.getServtransfer())))
				&& ((this.getServtransferid() == castOther.getServtransferid()) || (this
						.getServtransferid() != null
						&& castOther.getServtransferid() != null && this
						.getServtransferid().equals(
								castOther.getServtransferid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37 * result
				+ (getDriver() == null ? 0 : this.getDriver().hashCode());
		result = 37
				* result
				+ (getDriverphone() == null ? 0 : this.getDriverphone()
						.hashCode());
		result = 37
				* result
				+ (getFixedallowance() == null ? 0 : this.getFixedallowance()
						.hashCode());
		result = 37 * result
				+ (getFree() == null ? 0 : this.getFree().hashCode());
		result = 37
				* result
				+ (getPercentageofallowances() == null ? 0 : this
						.getPercentageofallowances().hashCode());
		result = 37 * result
				+ (getSum() == null ? 0 : this.getSum().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getCurrcurrency() == null ? 0 : this.getCurrcurrency()
						.hashCode());
		result = 37
				* result
				+ (getCurrcurrencyid() == null ? 0 : this.getCurrcurrencyid()
						.hashCode());
		result = 37
				* result
				+ (getServtransfer() == null ? 0 : this.getServtransfer()
						.hashCode());
		result = 37
				* result
				+ (getServtransferid() == null ? 0 : this.getServtransferid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ServTransferRouteView specialInit() {
	
		
		return this;
	}
	public ServTransferRouteView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ServTransferRouteView customInitList(List<String> list) {
		if (list.contains("servTransferRoutePoints")) {
			initLists(servTransferRoutePoints);
		}
		return this;
	}
	
	public ServTransferRouteView initList() {
		initLists(servTransferRoutePoints);

		return this;
	}
	
	public ServTransferRouteView initDicts() {
		return this;
	}
	
	
}