/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ServHotelSimpleView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="serv_hotel_simple_view")
public class ServHotelSimpleView extends SView  {

	private static final long serialVersionUID = 7186415384859225L;

	private Integer id;
	private Integer firmid;
	private Date modifyon;
	private String label;
	private String conditionText;
	private String descr;
	private String synopsis;
	private Boolean favorite;
	private Boolean freesale;
	private Boolean showonline;
	private Integer starcount;
	private String timedeparture;
	private String timerace;
	private String timeearlyrace;
	private String timelatedeparture;
	private Integer locationcitiesId;
	private Integer locationcountriesId;
	private Integer addressId;
	private BigDecimal price;
	private Integer humannumber;
	private BigDecimal cost;

	public ServHotelSimpleView() {
	}

	public ServHotelSimpleView(Integer id, Integer firmid, Date modifyon,
			String label, String conditionText, String descr, String synopsis,
			Boolean favorite, Boolean freesale, Boolean showonline,
			Integer starcount, String timedeparture, String timerace,
			String timeearlyrace, String timelatedeparture,
			Integer locationcitiesId, Integer locationcountriesId,
			Integer addressId, BigDecimal price, Integer humannumber,
			BigDecimal cost) {
		this.id = id;
		this.firmid = firmid;
		this.modifyon = modifyon;
		this.label = label;
		this.conditionText = conditionText;
		this.descr = descr;
		this.synopsis = synopsis;
		this.favorite = favorite;
		this.freesale = freesale;
		this.showonline = showonline;
		this.starcount = starcount;
		this.timedeparture = timedeparture;
		this.timerace = timerace;
		this.timeearlyrace = timeearlyrace;
		this.timelatedeparture = timelatedeparture;
		this.locationcitiesId = locationcitiesId;
		this.locationcountriesId = locationcountriesId;
		this.addressId = addressId;
		this.price = price;
		this.humannumber = humannumber;
		this.cost = cost;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="firmid")
	public Integer getFirmid() {
		return this.firmid;
	}

	public void setFirmid(Integer firmid) {
		this.firmid = firmid;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="condition_text", length = 2000)
	public String getConditionText() {
		return this.conditionText;
	}

	public void setConditionText(String conditionText) {
		this.conditionText = conditionText;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="synopsis", length = 500)
	public String getSynopsis() {
		return this.synopsis;
	}

	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}

	@Column(name="favorite")
	public Boolean getFavorite() {
		return this.favorite;
	}

	public void setFavorite(Boolean favorite) {
		this.favorite = favorite;
	}

	@Column(name="freesale")
	public Boolean getFreesale() {
		return this.freesale;
	}

	public void setFreesale(Boolean freesale) {
		this.freesale = freesale;
	}

	@Column(name="showonline")
	public Boolean getShowonline() {
		return this.showonline;
	}

	public void setShowonline(Boolean showonline) {
		this.showonline = showonline;
	}

	@Column(name="starcount")
	public Integer getStarcount() {
		return this.starcount;
	}

	public void setStarcount(Integer starcount) {
		this.starcount = starcount;
	}

	@Column(name="timedeparture")
	public String getTimedeparture() {
		return this.timedeparture;
	}

	public void setTimedeparture(String timedeparture) {
		this.timedeparture = timedeparture;
	}

	@Column(name="timerace")
	public String getTimerace() {
		return this.timerace;
	}

	public void setTimerace(String timerace) {
		this.timerace = timerace;
	}

	@Column(name="timeearlyrace")
	public String getTimeearlyrace() {
		return this.timeearlyrace;
	}

	public void setTimeearlyrace(String timeearlyrace) {
		this.timeearlyrace = timeearlyrace;
	}

	@Column(name="timelatedeparture")
	public String getTimelatedeparture() {
		return this.timelatedeparture;
	}

	public void setTimelatedeparture(String timelatedeparture) {
		this.timelatedeparture = timelatedeparture;
	}

	@Column(name="locationcities_id")
	public Integer getLocationcitiesId() {
		return this.locationcitiesId;
	}

	public void setLocationcitiesId(Integer locationcitiesId) {
		this.locationcitiesId = locationcitiesId;
	}

	@Column(name="locationcountries_id")
	public Integer getLocationcountriesId() {
		return this.locationcountriesId;
	}

	public void setLocationcountriesId(Integer locationcountriesId) {
		this.locationcountriesId = locationcountriesId;
	}

	@Column(name="address_id")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name="price", precision = 131089, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name="humannumber")
	public Integer getHumannumber() {
		return this.humannumber;
	}

	public void setHumannumber(Integer humannumber) {
		this.humannumber = humannumber;
	}

	@Column(name="cost", precision = 131089, scale = 0)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServHotelSimpleView))
			return false;
		ServHotelSimpleView castOther = (ServHotelSimpleView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getFirmid() == castOther.getFirmid()) || (this
						.getFirmid() != null && castOther.getFirmid() != null && this
						.getFirmid().equals(castOther.getFirmid())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getConditionText() == castOther.getConditionText()) || (this
						.getConditionText() != null
						&& castOther.getConditionText() != null && this
						.getConditionText()
						.equals(castOther.getConditionText())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getSynopsis() == castOther.getSynopsis()) || (this
						.getSynopsis() != null
						&& castOther.getSynopsis() != null && this
						.getSynopsis().equals(castOther.getSynopsis())))
				&& ((this.getFavorite() == castOther.getFavorite()) || (this
						.getFavorite() != null
						&& castOther.getFavorite() != null && this
						.getFavorite().equals(castOther.getFavorite())))
				&& ((this.getFreesale() == castOther.getFreesale()) || (this
						.getFreesale() != null
						&& castOther.getFreesale() != null && this
						.getFreesale().equals(castOther.getFreesale())))
				&& ((this.getShowonline() == castOther.getShowonline()) || (this
						.getShowonline() != null
						&& castOther.getShowonline() != null && this
						.getShowonline().equals(castOther.getShowonline())))
				&& ((this.getStarcount() == castOther.getStarcount()) || (this
						.getStarcount() != null
						&& castOther.getStarcount() != null && this
						.getStarcount().equals(castOther.getStarcount())))
				&& ((this.getTimedeparture() == castOther.getTimedeparture()) || (this
						.getTimedeparture() != null
						&& castOther.getTimedeparture() != null && this
						.getTimedeparture()
						.equals(castOther.getTimedeparture())))
				&& ((this.getTimerace() == castOther.getTimerace()) || (this
						.getTimerace() != null
						&& castOther.getTimerace() != null && this
						.getTimerace().equals(castOther.getTimerace())))
				&& ((this.getTimeearlyrace() == castOther.getTimeearlyrace()) || (this
						.getTimeearlyrace() != null
						&& castOther.getTimeearlyrace() != null && this
						.getTimeearlyrace()
						.equals(castOther.getTimeearlyrace())))
				&& ((this.getTimelatedeparture() == castOther
						.getTimelatedeparture()) || (this
						.getTimelatedeparture() != null
						&& castOther.getTimelatedeparture() != null && this
						.getTimelatedeparture().equals(
								castOther.getTimelatedeparture())))
				&& ((this.getLocationcitiesId() == castOther
						.getLocationcitiesId()) || (this.getLocationcitiesId() != null
						&& castOther.getLocationcitiesId() != null && this
						.getLocationcitiesId().equals(
								castOther.getLocationcitiesId())))
				&& ((this.getLocationcountriesId() == castOther
						.getLocationcountriesId()) || (this
						.getLocationcountriesId() != null
						&& castOther.getLocationcountriesId() != null && this
						.getLocationcountriesId().equals(
								castOther.getLocationcountriesId())))
				&& ((this.getAddressId() == castOther.getAddressId()) || (this
						.getAddressId() != null
						&& castOther.getAddressId() != null && this
						.getAddressId().equals(castOther.getAddressId())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getHumannumber() == castOther.getHumannumber()) || (this
						.getHumannumber() != null
						&& castOther.getHumannumber() != null && this
						.getHumannumber().equals(castOther.getHumannumber())))
				&& ((this.getCost() == castOther.getCost()) || (this.getCost() != null
						&& castOther.getCost() != null && this.getCost()
						.equals(castOther.getCost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getFirmid() == null ? 0 : this.getFirmid().hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37
				* result
				+ (getConditionText() == null ? 0 : this.getConditionText()
						.hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37 * result
				+ (getSynopsis() == null ? 0 : this.getSynopsis().hashCode());
		result = 37 * result
				+ (getFavorite() == null ? 0 : this.getFavorite().hashCode());
		result = 37 * result
				+ (getFreesale() == null ? 0 : this.getFreesale().hashCode());
		result = 37
				* result
				+ (getShowonline() == null ? 0 : this.getShowonline()
						.hashCode());
		result = 37 * result
				+ (getStarcount() == null ? 0 : this.getStarcount().hashCode());
		result = 37
				* result
				+ (getTimedeparture() == null ? 0 : this.getTimedeparture()
						.hashCode());
		result = 37 * result
				+ (getTimerace() == null ? 0 : this.getTimerace().hashCode());
		result = 37
				* result
				+ (getTimeearlyrace() == null ? 0 : this.getTimeearlyrace()
						.hashCode());
		result = 37
				* result
				+ (getTimelatedeparture() == null ? 0 : this
						.getTimelatedeparture().hashCode());
		result = 37
				* result
				+ (getLocationcitiesId() == null ? 0 : this
						.getLocationcitiesId().hashCode());
		result = 37
				* result
				+ (getLocationcountriesId() == null ? 0 : this
						.getLocationcountriesId().hashCode());
		result = 37 * result
				+ (getAddressId() == null ? 0 : this.getAddressId().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37
				* result
				+ (getHumannumber() == null ? 0 : this.getHumannumber()
						.hashCode());
		result = 37 * result
				+ (getCost() == null ? 0 : this.getCost().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ServHotelSimpleView specialInit() {
	
		
		return this;
	}
	public ServHotelSimpleView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ServHotelSimpleView customInitList(List<String> list) {
		
		return this;
	}
	
	public ServHotelSimpleView initList() {

		return this;
	}
	
	public ServHotelSimpleView initDicts() {
		return this;
	}
	
	
}