/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ShopPermissionView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="shop_permission_view")
public class ShopPermissionView extends SView  {

	private static final long serialVersionUID = 6572265298532249L;

	private Integer id;
	private Integer version;
	private Integer allocatedfirm;
	private Boolean physicalperson;
	private Boolean corporatecustomer;
	private Boolean travelagency;
	private Boolean traveloperator;
	private Boolean partner;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private Integer popularity;
	private String serieskey;
	private String label;

	private List<RelShopPermissionView> relShopPermissions = new LinkedList<RelShopPermissionView>();
	
	public ShopPermissionView() {
	}

	public ShopPermissionView(Integer id, Integer version,
			Integer allocatedfirm, Boolean physicalperson,
			Boolean corporatecustomer, Boolean travelagency,
			Boolean traveloperator, Boolean partner, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			Integer popularity, String serieskey, String label) {
		this.id = id;
		this.version = version;
		this.allocatedfirm = allocatedfirm;
		this.physicalperson = physicalperson;
		this.corporatecustomer = corporatecustomer;
		this.travelagency = travelagency;
		this.traveloperator = traveloperator;
		this.partner = partner;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.popularity = popularity;
		this.serieskey = serieskey;
		this.label = label;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="allocatedfirm")
	public Integer getAllocatedfirm() {
		return this.allocatedfirm;
	}

	public void setAllocatedfirm(Integer allocatedfirm) {
		this.allocatedfirm = allocatedfirm;
	}

	@Column(name="physicalperson")
	public Boolean getPhysicalperson() {
		return this.physicalperson;
	}

	public void setPhysicalperson(Boolean physicalperson) {
		this.physicalperson = physicalperson;
	}

	@Column(name="corporatecustomer")
	public Boolean getCorporatecustomer() {
		return this.corporatecustomer;
	}

	public void setCorporatecustomer(Boolean corporatecustomer) {
		this.corporatecustomer = corporatecustomer;
	}

	@Column(name="travelagency")
	public Boolean getTravelagency() {
		return this.travelagency;
	}

	public void setTravelagency(Boolean travelagency) {
		this.travelagency = travelagency;
	}

	@Column(name="traveloperator")
	public Boolean getTraveloperator() {
		return this.traveloperator;
	}

	public void setTraveloperator(Boolean traveloperator) {
		this.traveloperator = traveloperator;
	}

	@Column(name="partner")
	public Boolean getPartner() {
		return this.partner;
	}

	public void setPartner(Boolean partner) {
		this.partner = partner;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="shoppermissionid")
	public List<RelShopPermissionView> getRelShopPermissions() {
		return this.relShopPermissions;
	}

	public void setRelShopPermissions(List<RelShopPermissionView> relShopPermissions) {
		this.relShopPermissions = relShopPermissions;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopPermissionView))
			return false;
		ShopPermissionView castOther = (ShopPermissionView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getAllocatedfirm() == castOther.getAllocatedfirm()) || (this
						.getAllocatedfirm() != null
						&& castOther.getAllocatedfirm() != null && this
						.getAllocatedfirm()
						.equals(castOther.getAllocatedfirm())))
				&& ((this.getPhysicalperson() == castOther.getPhysicalperson()) || (this
						.getPhysicalperson() != null
						&& castOther.getPhysicalperson() != null && this
						.getPhysicalperson().equals(
								castOther.getPhysicalperson())))
				&& ((this.getCorporatecustomer() == castOther
						.getCorporatecustomer()) || (this
						.getCorporatecustomer() != null
						&& castOther.getCorporatecustomer() != null && this
						.getCorporatecustomer().equals(
								castOther.getCorporatecustomer())))
				&& ((this.getTravelagency() == castOther.getTravelagency()) || (this
						.getTravelagency() != null
						&& castOther.getTravelagency() != null && this
						.getTravelagency().equals(castOther.getTravelagency())))
				&& ((this.getTraveloperator() == castOther.getTraveloperator()) || (this
						.getTraveloperator() != null
						&& castOther.getTraveloperator() != null && this
						.getTraveloperator().equals(
								castOther.getTraveloperator())))
				&& ((this.getPartner() == castOther.getPartner()) || (this
						.getPartner() != null && castOther.getPartner() != null && this
						.getPartner().equals(castOther.getPartner())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37
				* result
				+ (getAllocatedfirm() == null ? 0 : this.getAllocatedfirm()
						.hashCode());
		result = 37
				* result
				+ (getPhysicalperson() == null ? 0 : this.getPhysicalperson()
						.hashCode());
		result = 37
				* result
				+ (getCorporatecustomer() == null ? 0 : this
						.getCorporatecustomer().hashCode());
		result = 37
				* result
				+ (getTravelagency() == null ? 0 : this.getTravelagency()
						.hashCode());
		result = 37
				* result
				+ (getTraveloperator() == null ? 0 : this.getTraveloperator()
						.hashCode());
		result = 37 * result
				+ (getPartner() == null ? 0 : this.getPartner().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ShopPermissionView specialInit() {
	
		
		return this;
	}
	public ShopPermissionView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ShopPermissionView customInitList(List<String> list) {
		if (list.contains("relShopPermissions")) {
			initLists(relShopPermissions);
		}
		return this;
	}
	
	public ShopPermissionView initList() {
		initLists(relShopPermissions);

		return this;
	}
	
	public ShopPermissionView initDicts() {
		return this;
	}
	
	
}