/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import javax.persistence.Transient;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ShopHotelImagesView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "path" 
})
@Entity
@Table(name="shop_hotel_images_view")
public class ShopHotelImagesView extends SView  {

	private static final long serialVersionUID = 4482391963426777L;

	private Integer servHotelId;
	private Integer id;
	private String createdby;
	private Date createon;
	private Integer firmid;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private Integer version;
	private String contenttype;
	private String extension;
	private String name;
	private String originalfilename;
	private String path;
	private String size;
	private String image;

	public ShopHotelImagesView() {
	}

	public ShopHotelImagesView(Integer servHotelId, Integer id,
			String createdby, Date createon, Integer firmid,
			String lastmodifiedby, Date modifyon, String serieskey,
			Integer version, String contenttype, String extension, String name,
			String originalfilename, String path, String size, String image) {
		this.servHotelId = servHotelId;
		this.id = id;
		this.createdby = createdby;
		this.createon = createon;
		this.firmid = firmid;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.version = version;
		this.contenttype = contenttype;
		this.extension = extension;
		this.name=name;
		this.originalfilename=originalfilename;
		this.path = path;
		this.size = size;
		this.image = image;
	}

	@Column(name="serv_hotel_id")
	public Integer getServHotelId() {
		return this.servHotelId;
	}

	public void setServHotelId(Integer servHotelId) {
		this.servHotelId = servHotelId;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firmid")
	public Integer getFirmid() {
		return this.firmid;
	}

	public void setFirmid(Integer firmid) {
		this.firmid = firmid;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="contenttype")
	public String getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(String contenttype) {
		this.contenttype = contenttype;
	}

	@Column(name="extension")
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name="name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name=name;
	}

	@Column(name="originalfilename")
	public String getOriginalfilename() {
		return this.originalfilename;
	}

	public void setOriginalfilename(String originalfilename) {
		this.originalfilename=originalfilename;
	}

	@Column(name="path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name="size")
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name="image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopHotelImagesView))
			return false;
		ShopHotelImagesView castOther = (ShopHotelImagesView) other;

		return ((this.getServHotelId() == castOther.getServHotelId()) || (this
				.getServHotelId() != null && castOther.getServHotelId() != null && this
				.getServHotelId().equals(castOther.getServHotelId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirmid() == castOther.getFirmid()) || (this
						.getFirmid() != null && castOther.getFirmid() != null && this
						.getFirmid().equals(castOther.getFirmid())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getContenttype() == castOther.getContenttype()) || (this
						.getContenttype() != null
						&& castOther.getContenttype() != null && this
						.getContenttype().equals(castOther.getContenttype())))
				&& ((this.getExtension() == castOther.getExtension()) || (this
						.getExtension() != null
						&& castOther.getExtension() != null && this
						.getExtension().equals(castOther.getExtension())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getOriginalfilename() == castOther
						.getOriginalfilename()) || (this.getOriginalfilename() != null
						&& castOther.getOriginalfilename() != null && this
						.getOriginalfilename().equals(
								castOther.getOriginalfilename())))
				&& ((this.getPath() == castOther.getPath()) || (this.getPath() != null
						&& castOther.getPath() != null && this.getPath()
						.equals(castOther.getPath())))
				&& ((this.getSize() == castOther.getSize()) || (this.getSize() != null
						&& castOther.getSize() != null && this.getSize()
						.equals(castOther.getSize())))
				&& ((this.getImage() == castOther.getImage()) || (this
						.getImage() != null && castOther.getImage() != null && this
						.getImage().equals(castOther.getImage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServHotelId() == null ? 0 : this.getServHotelId()
						.hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirmid() == null ? 0 : this.getFirmid().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37
				* result
				+ (getContenttype() == null ? 0 : this.getContenttype()
						.hashCode());
		result = 37 * result
				+ (getExtension() == null ? 0 : this.getExtension().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getOriginalfilename() == null ? 0 : this
						.getOriginalfilename().hashCode());
		result = 37 * result
				+ (getPath() == null ? 0 : this.getPath().hashCode());
		result = 37 * result
				+ (getSize() == null ? 0 : this.getSize().hashCode());
		result = 37 * result
				+ (getImage() == null ? 0 : this.getImage().hashCode());
		return result;
	}
// #SETTER_AND_GETTER

	@Transient
	public String getLabel() {
		return originalfilename;
	}

	public void setLabel(String label) {
		
	}
	
	@Transient
	public String getUrl() {
		return name + "." + extension;
	}

	public void setUrl(String url) {
		
	}
	
	
// ------------------ Logic part ------------------
	
	public ShopHotelImagesView specialInit() {
	
		
		return this;
	}
	public ShopHotelImagesView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ShopHotelImagesView customInitList(List<String> list) {
		
		return this;
	}
	
	public ShopHotelImagesView initList() {

		return this;
	}
	
	public ShopHotelImagesView initDicts() {
		return this;
	}
	
	
}