/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import javax.persistence.OrderBy;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import java.util.LinkedList;
import javax.persistence.Transient;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import org.test.shop.model.domain.SView;
import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;


/**
 * ShopServHotel2View generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "currencyid" 
})
@Entity
@Table(name="shop_serv_hotel_2_view")
public class ShopServHotel2View extends SView  {

	private static final long serialVersionUID = 6294536331394399L;

	private Integer id;
	private Date modifyon;
	private String label;
	private String conditionText;
	private String descr;
	private String synopsis;
	private Boolean favorite;
	private Boolean freesale;
	private Boolean showonline;
	private Integer starcount;
	private String timedeparture;
	private String timerace;
	private String timeearlyrace;
	private String timelatedeparture;
	private BigDecimal price;
	private Integer humannumber;
	private BigDecimal cost;
	private String cityname;
	private String countryname;
	private String image;
	private Integer currencyid;
	private String currencyname;
	private String currencysign;
	private String usdcurrencysign;
	private BigDecimal usdcost;
	private String addressname;
	private String yandexmappointx;
	private String yandexmappointy;

	public ShopServHotel2View() {
	}

	public ShopServHotel2View(Integer id, Date modifyon, String label,
			String conditionText, String descr, String synopsis,
			Boolean favorite, Boolean freesale, Boolean showonline,
			Integer starcount, String timedeparture, String timerace,
			String timeearlyrace, String timelatedeparture, BigDecimal price,
			Integer humannumber, BigDecimal cost, String cityname,
			String countryname, String image, Integer currencyid,
			String currencyname, String currencysign, String usdcurrencysign,
			BigDecimal usdcost, String addressname, String yandexmappointx,
			String yandexmappointy) {
		this.id = id;
		this.modifyon = modifyon;
		this.label = label;
		this.conditionText = conditionText;
		this.descr = descr;
		this.synopsis = synopsis;
		this.favorite = favorite;
		this.freesale = freesale;
		this.showonline = showonline;
		this.starcount = starcount;
		this.timedeparture = timedeparture;
		this.timerace = timerace;
		this.timeearlyrace = timeearlyrace;
		this.timelatedeparture = timelatedeparture;
		this.price = price;
		this.humannumber = humannumber;
		this.cost = cost;
		this.cityname=cityname;
		this.countryname=countryname;
		this.image = image;
		this.currencyid = currencyid;
		this.currencyname=currencyname;
		this.currencysign = currencysign;
		this.usdcurrencysign = usdcurrencysign;
		this.usdcost = usdcost;
		this.addressname=addressname;
		this.yandexmappointx = yandexmappointx;
		this.yandexmappointy = yandexmappointy;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="condition_text", length = 2000)
	public String getConditionText() {
		return this.conditionText;
	}

	public void setConditionText(String conditionText) {
		this.conditionText = conditionText;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="synopsis", length = 500)
	public String getSynopsis() {
		return this.synopsis;
	}

	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}

	@Column(name="favorite")
	public Boolean getFavorite() {
		return this.favorite;
	}

	public void setFavorite(Boolean favorite) {
		this.favorite = favorite;
	}

	@Column(name="freesale")
	public Boolean getFreesale() {
		return this.freesale;
	}

	public void setFreesale(Boolean freesale) {
		this.freesale = freesale;
	}

	@Column(name="showonline")
	public Boolean getShowonline() {
		return this.showonline;
	}

	public void setShowonline(Boolean showonline) {
		this.showonline = showonline;
	}

	@Column(name="starcount")
	public Integer getStarcount() {
		return this.starcount;
	}

	public void setStarcount(Integer starcount) {
		this.starcount = starcount;
	}

	@Column(name="timedeparture")
	public String getTimedeparture() {
		return this.timedeparture;
	}

	public void setTimedeparture(String timedeparture) {
		this.timedeparture = timedeparture;
	}

	@Column(name="timerace")
	public String getTimerace() {
		return this.timerace;
	}

	public void setTimerace(String timerace) {
		this.timerace = timerace;
	}

	@Column(name="timeearlyrace")
	public String getTimeearlyrace() {
		return this.timeearlyrace;
	}

	public void setTimeearlyrace(String timeearlyrace) {
		this.timeearlyrace = timeearlyrace;
	}

	@Column(name="timelatedeparture")
	public String getTimelatedeparture() {
		return this.timelatedeparture;
	}

	public void setTimelatedeparture(String timelatedeparture) {
		this.timelatedeparture = timelatedeparture;
	}

	@Column(name="price", precision = 131089, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name="humannumber")
	public Integer getHumannumber() {
		return this.humannumber;
	}

	public void setHumannumber(Integer humannumber) {
		this.humannumber = humannumber;
	}

	@Column(name="cost", precision = 131089, scale = 0)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name="cityname")
	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname=cityname;
	}

	@Column(name="countryname")
	public String getCountryname() {
		return this.countryname;
	}

	public void setCountryname(String countryname) {
		this.countryname=countryname;
	}

	@Column(name="image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name="currencyid")
	public Integer getCurrencyid() {
		return this.currencyid;
	}

	public void setCurrencyid(Integer currencyid) {
		this.currencyid = currencyid;
	}

	@Column(name="currencyname")
	public String getCurrencyname() {
		return this.currencyname;
	}

	public void setCurrencyname(String currencyname) {
		this.currencyname=currencyname;
	}

	@Column(name="currencysign")
	public String getCurrencysign() {
		return this.currencysign;
	}

	public void setCurrencysign(String currencysign) {
		this.currencysign = currencysign;
	}

	@Column(name="usdcurrencysign")
	public String getUsdcurrencysign() {
		return this.usdcurrencysign;
	}

	public void setUsdcurrencysign(String usdcurrencysign) {
		this.usdcurrencysign = usdcurrencysign;
	}

	@Column(name="usdcost", precision = 131089, scale = 0)
	public BigDecimal getUsdcost() {
		return this.usdcost;
	}

	public void setUsdcost(BigDecimal usdcost) {
		this.usdcost = usdcost;
	}

	@Column(name="addressname")
	public String getAddressname() {
		return this.addressname;
	}

	public void setAddressname(String addressname) {
		this.addressname=addressname;
	}

	@Column(name="yandexmappointx")
	public String getYandexmappointx() {
		return this.yandexmappointx;
	}

	public void setYandexmappointx(String yandexmappointx) {
		this.yandexmappointx = yandexmappointx;
	}

	@Column(name="yandexmappointy")
	public String getYandexmappointy() {
		return this.yandexmappointy;
	}

	public void setYandexmappointy(String yandexmappointy) {
		this.yandexmappointy = yandexmappointy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopServHotel2View))
			return false;
		ShopServHotel2View castOther = (ShopServHotel2View) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getConditionText() == castOther.getConditionText()) || (this
						.getConditionText() != null
						&& castOther.getConditionText() != null && this
						.getConditionText()
						.equals(castOther.getConditionText())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getSynopsis() == castOther.getSynopsis()) || (this
						.getSynopsis() != null
						&& castOther.getSynopsis() != null && this
						.getSynopsis().equals(castOther.getSynopsis())))
				&& ((this.getFavorite() == castOther.getFavorite()) || (this
						.getFavorite() != null
						&& castOther.getFavorite() != null && this
						.getFavorite().equals(castOther.getFavorite())))
				&& ((this.getFreesale() == castOther.getFreesale()) || (this
						.getFreesale() != null
						&& castOther.getFreesale() != null && this
						.getFreesale().equals(castOther.getFreesale())))
				&& ((this.getShowonline() == castOther.getShowonline()) || (this
						.getShowonline() != null
						&& castOther.getShowonline() != null && this
						.getShowonline().equals(castOther.getShowonline())))
				&& ((this.getStarcount() == castOther.getStarcount()) || (this
						.getStarcount() != null
						&& castOther.getStarcount() != null && this
						.getStarcount().equals(castOther.getStarcount())))
				&& ((this.getTimedeparture() == castOther.getTimedeparture()) || (this
						.getTimedeparture() != null
						&& castOther.getTimedeparture() != null && this
						.getTimedeparture()
						.equals(castOther.getTimedeparture())))
				&& ((this.getTimerace() == castOther.getTimerace()) || (this
						.getTimerace() != null
						&& castOther.getTimerace() != null && this
						.getTimerace().equals(castOther.getTimerace())))
				&& ((this.getTimeearlyrace() == castOther.getTimeearlyrace()) || (this
						.getTimeearlyrace() != null
						&& castOther.getTimeearlyrace() != null && this
						.getTimeearlyrace()
						.equals(castOther.getTimeearlyrace())))
				&& ((this.getTimelatedeparture() == castOther
						.getTimelatedeparture()) || (this
						.getTimelatedeparture() != null
						&& castOther.getTimelatedeparture() != null && this
						.getTimelatedeparture().equals(
								castOther.getTimelatedeparture())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getHumannumber() == castOther.getHumannumber()) || (this
						.getHumannumber() != null
						&& castOther.getHumannumber() != null && this
						.getHumannumber().equals(castOther.getHumannumber())))
				&& ((this.getCost() == castOther.getCost()) || (this.getCost() != null
						&& castOther.getCost() != null && this.getCost()
						.equals(castOther.getCost())))
				&& ((this.getCityname() == castOther.getCityname()) || (this
						.getCityname() != null
						&& castOther.getCityname() != null && this
						.getCityname().equals(castOther.getCityname())))
				&& ((this.getCountryname() == castOther.getCountryname()) || (this
						.getCountryname() != null
						&& castOther.getCountryname() != null && this
						.getCountryname().equals(castOther.getCountryname())))
				&& ((this.getImage() == castOther.getImage()) || (this
						.getImage() != null && castOther.getImage() != null && this
						.getImage().equals(castOther.getImage())))
				&& ((this.getCurrencyid() == castOther.getCurrencyid()) || (this
						.getCurrencyid() != null
						&& castOther.getCurrencyid() != null && this
						.getCurrencyid().equals(castOther.getCurrencyid())))
				&& ((this.getCurrencyname() == castOther.getCurrencyname()) || (this
						.getCurrencyname() != null
						&& castOther.getCurrencyname() != null && this
						.getCurrencyname().equals(castOther.getCurrencyname())))
				&& ((this.getCurrencysign() == castOther.getCurrencysign()) || (this
						.getCurrencysign() != null
						&& castOther.getCurrencysign() != null && this
						.getCurrencysign().equals(castOther.getCurrencysign())))
				&& ((this.getUsdcurrencysign() == castOther
						.getUsdcurrencysign()) || (this.getUsdcurrencysign() != null
						&& castOther.getUsdcurrencysign() != null && this
						.getUsdcurrencysign().equals(
								castOther.getUsdcurrencysign())))
				&& ((this.getUsdcost() == castOther.getUsdcost()) || (this
						.getUsdcost() != null && castOther.getUsdcost() != null && this
						.getUsdcost().equals(castOther.getUsdcost())))
				&& ((this.getAddressname() == castOther.getAddressname()) || (this
						.getAddressname() != null
						&& castOther.getAddressname() != null && this
						.getAddressname().equals(castOther.getAddressname())))
				&& ((this.getYandexmappointx() == castOther
						.getYandexmappointx()) || (this.getYandexmappointx() != null
						&& castOther.getYandexmappointx() != null && this
						.getYandexmappointx().equals(
								castOther.getYandexmappointx())))
				&& ((this.getYandexmappointy() == castOther
						.getYandexmappointy()) || (this.getYandexmappointy() != null
						&& castOther.getYandexmappointy() != null && this
						.getYandexmappointy().equals(
								castOther.getYandexmappointy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37
				* result
				+ (getConditionText() == null ? 0 : this.getConditionText()
						.hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37 * result
				+ (getSynopsis() == null ? 0 : this.getSynopsis().hashCode());
		result = 37 * result
				+ (getFavorite() == null ? 0 : this.getFavorite().hashCode());
		result = 37 * result
				+ (getFreesale() == null ? 0 : this.getFreesale().hashCode());
		result = 37
				* result
				+ (getShowonline() == null ? 0 : this.getShowonline()
						.hashCode());
		result = 37 * result
				+ (getStarcount() == null ? 0 : this.getStarcount().hashCode());
		result = 37
				* result
				+ (getTimedeparture() == null ? 0 : this.getTimedeparture()
						.hashCode());
		result = 37 * result
				+ (getTimerace() == null ? 0 : this.getTimerace().hashCode());
		result = 37
				* result
				+ (getTimeearlyrace() == null ? 0 : this.getTimeearlyrace()
						.hashCode());
		result = 37
				* result
				+ (getTimelatedeparture() == null ? 0 : this
						.getTimelatedeparture().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37
				* result
				+ (getHumannumber() == null ? 0 : this.getHumannumber()
						.hashCode());
		result = 37 * result
				+ (getCost() == null ? 0 : this.getCost().hashCode());
		result = 37 * result
				+ (getCityname() == null ? 0 : this.getCityname().hashCode());
		result = 37
				* result
				+ (getCountryname() == null ? 0 : this.getCountryname()
						.hashCode());
		result = 37 * result
				+ (getImage() == null ? 0 : this.getImage().hashCode());
		result = 37
				* result
				+ (getCurrencyid() == null ? 0 : this.getCurrencyid()
						.hashCode());
		result = 37
				* result
				+ (getCurrencyname() == null ? 0 : this.getCurrencyname()
						.hashCode());
		result = 37
				* result
				+ (getCurrencysign() == null ? 0 : this.getCurrencysign()
						.hashCode());
		result = 37
				* result
				+ (getUsdcurrencysign() == null ? 0 : this.getUsdcurrencysign()
						.hashCode());
		result = 37 * result
				+ (getUsdcost() == null ? 0 : this.getUsdcost().hashCode());
		result = 37
				* result
				+ (getAddressname() == null ? 0 : this.getAddressname()
						.hashCode());
		result = 37
				* result
				+ (getYandexmappointx() == null ? 0 : this.getYandexmappointx()
						.hashCode());
		result = 37
				* result
				+ (getYandexmappointy() == null ? 0 : this.getYandexmappointy()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER

	private List<ShopRoomView> rooms = new LinkedList<ShopRoomView>();
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="servhotelid")
	@OrderBy("cost ASC")
	public List<ShopRoomView> getRooms() {
		return rooms;
	}

	public void setRooms(List<ShopRoomView> rooms) {
		this.rooms = rooms;
	}
	
	private List<ShopHotelImagesView> images = new LinkedList<ShopHotelImagesView>();
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="serv_hotel_id")
	public List<ShopHotelImagesView> getImages() {
		return images;
	}

	public void setImages(List<ShopHotelImagesView> images) {
		this.images = images;
	}
	
	
// ------------------ Logic part ------------------
	
	public ShopServHotel2View specialInit() {
	
		
		return this;
	}
	public ShopServHotel2View init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ShopServHotel2View customInitList(List<String> list) {
		
		return this;
	}
	
	public ShopServHotel2View initList() {

		try {
			getRooms().size();
			rooms.parallelStream().forEach(it -> {
				it.initList();
			});
			getImages().size();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	

		return this;
	}
	
	public ShopServHotel2View initDicts() {
		return this;
	}
	
	
}