/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.math.BigDecimal;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * ShopRoomTarriffGeneralRateView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "corporateRateCurrcurrencyid"
			, "originalRateCurrcurrencyid" 
})
@Entity
@Table(name="shop_room_tarriff_general_rate_view")
public class ShopRoomTarriffGeneralRateView extends SView  {

	private static final long serialVersionUID = 8459846161194971L;

	private Integer id;
	private Integer paymentTariffId;
	private Integer paymentTariffVersion;
	private Integer priceVersion;
	private Integer humannumber;
	private Integer roomId;
	private BigDecimal corporateRateCost;
	private BigDecimal corporateRateCostNationalCurrency;
	private BigDecimal corporateRateCostUsdCurrency;
	private String corporateRateCostUsdcurrencysign;
	private Integer corporateRateCurrcurrencyid;
	private Integer corporateRateCurrcurrencyversion;
	private String corporateRateCurrencyname;
	private BigDecimal originalRateCost;
	private BigDecimal originalRateCostNationalCurrency;
	private BigDecimal originalRateCostUsdCurrency;
	private String originalRateCostUsdcurrencysign;
	private Integer originalRateCurrcurrencyid;
	private Integer originalRateCurrcurrencyversion;
	private String originalRateCurrencyname;

	public ShopRoomTarriffGeneralRateView() {
	}

	public ShopRoomTarriffGeneralRateView(Integer id,
			Integer paymentTariffId, Integer paymentTariffVersion,
			Integer priceVersion, Integer humannumber, Integer roomId,
			BigDecimal corporateRateCost,
			BigDecimal corporateRateCostNationalCurrency,
			BigDecimal corporateRateCostUsdCurrency,
			String corporateRateCostUsdcurrencysign,
			Integer corporateRateCurrcurrencyid,
			Integer corporateRateCurrcurrencyversion,
			String corporateRateCurrencyname, BigDecimal originalRateCost,
			BigDecimal originalRateCostNationalCurrency,
			BigDecimal originalRateCostUsdCurrency,
			String originalRateCostUsdcurrencysign,
			Integer originalRateCurrcurrencyid,
			Integer originalRateCurrcurrencyversion,
			String originalRateCurrencyname) {
		this.id = id;
		this.paymentTariffId = paymentTariffId;
		this.paymentTariffVersion = paymentTariffVersion;
		this.priceVersion = priceVersion;
		this.humannumber = humannumber;
		this.roomId = roomId;
		this.corporateRateCost = corporateRateCost;
		this.corporateRateCostNationalCurrency = corporateRateCostNationalCurrency;
		this.corporateRateCostUsdCurrency = corporateRateCostUsdCurrency;
		this.corporateRateCostUsdcurrencysign = corporateRateCostUsdcurrencysign;
		this.corporateRateCurrcurrencyid = corporateRateCurrcurrencyid;
		this.corporateRateCurrcurrencyversion = corporateRateCurrcurrencyversion;
		this.corporateRateCurrencyname=corporateRateCurrencyname;
		this.originalRateCost = originalRateCost;
		this.originalRateCostNationalCurrency = originalRateCostNationalCurrency;
		this.originalRateCostUsdCurrency = originalRateCostUsdCurrency;
		this.originalRateCostUsdcurrencysign = originalRateCostUsdcurrencysign;
		this.originalRateCurrcurrencyid = originalRateCurrcurrencyid;
		this.originalRateCurrcurrencyversion = originalRateCurrcurrencyversion;
		this.originalRateCurrencyname=originalRateCurrencyname;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="payment_tariff_id")
	public Integer getPaymentTariffId() {
		return this.paymentTariffId;
	}

	public void setPaymentTariffId(Integer paymentTariffId) {
		this.paymentTariffId = paymentTariffId;
	}

	@Column(name="payment_tariff_version")
	public Integer getPaymentTariffVersion() {
		return this.paymentTariffVersion;
	}

	public void setPaymentTariffVersion(Integer paymentTariffVersion) {
		this.paymentTariffVersion = paymentTariffVersion;
	}

	@Column(name="price_version")
	public Integer getPriceVersion() {
		return this.priceVersion;
	}

	public void setPriceVersion(Integer priceVersion) {
		this.priceVersion = priceVersion;
	}

	@Column(name="humannumber")
	public Integer getHumannumber() {
		return this.humannumber;
	}

	public void setHumannumber(Integer humannumber) {
		this.humannumber = humannumber;
	}

	@Column(name="room_id")
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@Column(name="corporate_rate_cost", precision = 131089, scale = 0)
	public BigDecimal getCorporateRateCost() {
		return this.corporateRateCost;
	}

	public void setCorporateRateCost(BigDecimal corporateRateCost) {
		this.corporateRateCost = corporateRateCost;
	}

	@Column(name="corporate_rate_cost_national_currency", precision = 131089, scale = 0)
	public BigDecimal getCorporateRateCostNationalCurrency() {
		return this.corporateRateCostNationalCurrency;
	}

	public void setCorporateRateCostNationalCurrency(
			BigDecimal corporateRateCostNationalCurrency) {
		this.corporateRateCostNationalCurrency = corporateRateCostNationalCurrency;
	}

	@Column(name="corporate_rate_cost_usd_currency", precision = 131089, scale = 0)
	public BigDecimal getCorporateRateCostUsdCurrency() {
		return this.corporateRateCostUsdCurrency;
	}

	public void setCorporateRateCostUsdCurrency(
			BigDecimal corporateRateCostUsdCurrency) {
		this.corporateRateCostUsdCurrency = corporateRateCostUsdCurrency;
	}

	@Column(name="corporate_rate_cost_usdcurrencysign")
	public String getCorporateRateCostUsdcurrencysign() {
		return this.corporateRateCostUsdcurrencysign;
	}

	public void setCorporateRateCostUsdcurrencysign(
			String corporateRateCostUsdcurrencysign) {
		this.corporateRateCostUsdcurrencysign = corporateRateCostUsdcurrencysign;
	}

	@Column(name="corporate_rate_currcurrencyid")
	public Integer getCorporateRateCurrcurrencyid() {
		return this.corporateRateCurrcurrencyid;
	}

	public void setCorporateRateCurrcurrencyid(
			Integer corporateRateCurrcurrencyid) {
		this.corporateRateCurrcurrencyid = corporateRateCurrcurrencyid;
	}

	@Column(name="corporate_rate_currcurrencyversion")
	public Integer getCorporateRateCurrcurrencyversion() {
		return this.corporateRateCurrcurrencyversion;
	}

	public void setCorporateRateCurrcurrencyversion(
			Integer corporateRateCurrcurrencyversion) {
		this.corporateRateCurrcurrencyversion = corporateRateCurrcurrencyversion;
	}

	@Column(name="corporate_rate_currencyname")
	public String getCorporateRateCurrencyname() {
		return this.corporateRateCurrencyname;
	}

	public void setCorporateRateCurrencyname(String corporateRateCurrencyname) {
		this.corporateRateCurrencyname=corporateRateCurrencyname;
	}

	@Column(name="original_rate_cost", precision = 131089, scale = 0)
	public BigDecimal getOriginalRateCost() {
		return this.originalRateCost;
	}

	public void setOriginalRateCost(BigDecimal originalRateCost) {
		this.originalRateCost = originalRateCost;
	}

	@Column(name="original_rate_cost_national_currency", precision = 131089, scale = 0)
	public BigDecimal getOriginalRateCostNationalCurrency() {
		return this.originalRateCostNationalCurrency;
	}

	public void setOriginalRateCostNationalCurrency(
			BigDecimal originalRateCostNationalCurrency) {
		this.originalRateCostNationalCurrency = originalRateCostNationalCurrency;
	}

	@Column(name="original_rate_cost_usd_currency", precision = 131089, scale = 0)
	public BigDecimal getOriginalRateCostUsdCurrency() {
		return this.originalRateCostUsdCurrency;
	}

	public void setOriginalRateCostUsdCurrency(
			BigDecimal originalRateCostUsdCurrency) {
		this.originalRateCostUsdCurrency = originalRateCostUsdCurrency;
	}

	@Column(name="original_rate_cost_usdcurrencysign")
	public String getOriginalRateCostUsdcurrencysign() {
		return this.originalRateCostUsdcurrencysign;
	}

	public void setOriginalRateCostUsdcurrencysign(
			String originalRateCostUsdcurrencysign) {
		this.originalRateCostUsdcurrencysign = originalRateCostUsdcurrencysign;
	}

	@Column(name="original_rate_currcurrencyid")
	public Integer getOriginalRateCurrcurrencyid() {
		return this.originalRateCurrcurrencyid;
	}

	public void setOriginalRateCurrcurrencyid(Integer originalRateCurrcurrencyid) {
		this.originalRateCurrcurrencyid = originalRateCurrcurrencyid;
	}

	@Column(name="original_rate_currcurrencyversion")
	public Integer getOriginalRateCurrcurrencyversion() {
		return this.originalRateCurrcurrencyversion;
	}

	public void setOriginalRateCurrcurrencyversion(
			Integer originalRateCurrcurrencyversion) {
		this.originalRateCurrcurrencyversion = originalRateCurrcurrencyversion;
	}

	@Column(name="original_rate_currencyname")
	public String getOriginalRateCurrencyname() {
		return this.originalRateCurrencyname;
	}

	public void setOriginalRateCurrencyname(String originalRateCurrencyname) {
		this.originalRateCurrencyname=originalRateCurrencyname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopRoomTarriffGeneralRateView))
			return false;
		ShopRoomTarriffGeneralRateView castOther = (ShopRoomTarriffGeneralRateView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getPaymentTariffId() == castOther
						.getPaymentTariffId()) || (this.getPaymentTariffId() != null
						&& castOther.getPaymentTariffId() != null && this
						.getPaymentTariffId().equals(
								castOther.getPaymentTariffId())))
				&& ((this.getPaymentTariffVersion() == castOther
						.getPaymentTariffVersion()) || (this
						.getPaymentTariffVersion() != null
						&& castOther.getPaymentTariffVersion() != null && this
						.getPaymentTariffVersion().equals(
								castOther.getPaymentTariffVersion())))
				&& ((this.getPriceVersion() == castOther.getPriceVersion()) || (this
						.getPriceVersion() != null
						&& castOther.getPriceVersion() != null && this
						.getPriceVersion().equals(castOther.getPriceVersion())))
				&& ((this.getHumannumber() == castOther.getHumannumber()) || (this
						.getHumannumber() != null
						&& castOther.getHumannumber() != null && this
						.getHumannumber().equals(castOther.getHumannumber())))
				&& ((this.getRoomId() == castOther.getRoomId()) || (this
						.getRoomId() != null && castOther.getRoomId() != null && this
						.getRoomId().equals(castOther.getRoomId())))
				&& ((this.getCorporateRateCost() == castOther
						.getCorporateRateCost()) || (this
						.getCorporateRateCost() != null
						&& castOther.getCorporateRateCost() != null && this
						.getCorporateRateCost().equals(
								castOther.getCorporateRateCost())))
				&& ((this.getCorporateRateCostNationalCurrency() == castOther
						.getCorporateRateCostNationalCurrency()) || (this
						.getCorporateRateCostNationalCurrency() != null
						&& castOther.getCorporateRateCostNationalCurrency() != null && this
						.getCorporateRateCostNationalCurrency()
						.equals(castOther
								.getCorporateRateCostNationalCurrency())))
				&& ((this.getCorporateRateCostUsdCurrency() == castOther
						.getCorporateRateCostUsdCurrency()) || (this
						.getCorporateRateCostUsdCurrency() != null
						&& castOther.getCorporateRateCostUsdCurrency() != null && this
						.getCorporateRateCostUsdCurrency().equals(
								castOther.getCorporateRateCostUsdCurrency())))
				&& ((this.getCorporateRateCostUsdcurrencysign() == castOther
						.getCorporateRateCostUsdcurrencysign()) || (this
						.getCorporateRateCostUsdcurrencysign() != null
						&& castOther.getCorporateRateCostUsdcurrencysign() != null && this
						.getCorporateRateCostUsdcurrencysign()
						.equals(castOther.getCorporateRateCostUsdcurrencysign())))
				&& ((this.getCorporateRateCurrcurrencyid() == castOther
						.getCorporateRateCurrcurrencyid()) || (this
						.getCorporateRateCurrcurrencyid() != null
						&& castOther.getCorporateRateCurrcurrencyid() != null && this
						.getCorporateRateCurrcurrencyid().equals(
								castOther.getCorporateRateCurrcurrencyid())))
				&& ((this.getCorporateRateCurrcurrencyversion() == castOther
						.getCorporateRateCurrcurrencyversion()) || (this
						.getCorporateRateCurrcurrencyversion() != null
						&& castOther.getCorporateRateCurrcurrencyversion() != null && this
						.getCorporateRateCurrcurrencyversion()
						.equals(castOther.getCorporateRateCurrcurrencyversion())))
				&& ((this.getCorporateRateCurrencyname() == castOther
						.getCorporateRateCurrencyname()) || (this
						.getCorporateRateCurrencyname() != null
						&& castOther.getCorporateRateCurrencyname() != null && this
						.getCorporateRateCurrencyname().equals(
								castOther.getCorporateRateCurrencyname())))
				&& ((this.getOriginalRateCost() == castOther
						.getOriginalRateCost()) || (this.getOriginalRateCost() != null
						&& castOther.getOriginalRateCost() != null && this
						.getOriginalRateCost().equals(
								castOther.getOriginalRateCost())))
				&& ((this.getOriginalRateCostNationalCurrency() == castOther
						.getOriginalRateCostNationalCurrency()) || (this
						.getOriginalRateCostNationalCurrency() != null
						&& castOther.getOriginalRateCostNationalCurrency() != null && this
						.getOriginalRateCostNationalCurrency()
						.equals(castOther.getOriginalRateCostNationalCurrency())))
				&& ((this.getOriginalRateCostUsdCurrency() == castOther
						.getOriginalRateCostUsdCurrency()) || (this
						.getOriginalRateCostUsdCurrency() != null
						&& castOther.getOriginalRateCostUsdCurrency() != null && this
						.getOriginalRateCostUsdCurrency().equals(
								castOther.getOriginalRateCostUsdCurrency())))
				&& ((this.getOriginalRateCostUsdcurrencysign() == castOther
						.getOriginalRateCostUsdcurrencysign()) || (this
						.getOriginalRateCostUsdcurrencysign() != null
						&& castOther.getOriginalRateCostUsdcurrencysign() != null && this
						.getOriginalRateCostUsdcurrencysign().equals(
								castOther.getOriginalRateCostUsdcurrencysign())))
				&& ((this.getOriginalRateCurrcurrencyid() == castOther
						.getOriginalRateCurrcurrencyid()) || (this
						.getOriginalRateCurrcurrencyid() != null
						&& castOther.getOriginalRateCurrcurrencyid() != null && this
						.getOriginalRateCurrcurrencyid().equals(
								castOther.getOriginalRateCurrcurrencyid())))
				&& ((this.getOriginalRateCurrcurrencyversion() == castOther
						.getOriginalRateCurrcurrencyversion()) || (this
						.getOriginalRateCurrcurrencyversion() != null
						&& castOther.getOriginalRateCurrcurrencyversion() != null && this
						.getOriginalRateCurrcurrencyversion().equals(
								castOther.getOriginalRateCurrcurrencyversion())))
				&& ((this.getOriginalRateCurrencyname() == castOther
						.getOriginalRateCurrencyname()) || (this
						.getOriginalRateCurrencyname() != null
						&& castOther.getOriginalRateCurrencyname() != null && this
						.getOriginalRateCurrencyname().equals(
								castOther.getOriginalRateCurrencyname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getPaymentTariffId() == null ? 0 : this.getPaymentTariffId()
						.hashCode());
		result = 37
				* result
				+ (getPaymentTariffVersion() == null ? 0 : this
						.getPaymentTariffVersion().hashCode());
		result = 37
				* result
				+ (getPriceVersion() == null ? 0 : this.getPriceVersion()
						.hashCode());
		result = 37
				* result
				+ (getHumannumber() == null ? 0 : this.getHumannumber()
						.hashCode());
		result = 37 * result
				+ (getRoomId() == null ? 0 : this.getRoomId().hashCode());
		result = 37
				* result
				+ (getCorporateRateCost() == null ? 0 : this
						.getCorporateRateCost().hashCode());
		result = 37
				* result
				+ (getCorporateRateCostNationalCurrency() == null ? 0 : this
						.getCorporateRateCostNationalCurrency().hashCode());
		result = 37
				* result
				+ (getCorporateRateCostUsdCurrency() == null ? 0 : this
						.getCorporateRateCostUsdCurrency().hashCode());
		result = 37
				* result
				+ (getCorporateRateCostUsdcurrencysign() == null ? 0 : this
						.getCorporateRateCostUsdcurrencysign().hashCode());
		result = 37
				* result
				+ (getCorporateRateCurrcurrencyid() == null ? 0 : this
						.getCorporateRateCurrcurrencyid().hashCode());
		result = 37
				* result
				+ (getCorporateRateCurrcurrencyversion() == null ? 0 : this
						.getCorporateRateCurrcurrencyversion().hashCode());
		result = 37
				* result
				+ (getCorporateRateCurrencyname() == null ? 0 : this
						.getCorporateRateCurrencyname().hashCode());
		result = 37
				* result
				+ (getOriginalRateCost() == null ? 0 : this
						.getOriginalRateCost().hashCode());
		result = 37
				* result
				+ (getOriginalRateCostNationalCurrency() == null ? 0 : this
						.getOriginalRateCostNationalCurrency().hashCode());
		result = 37
				* result
				+ (getOriginalRateCostUsdCurrency() == null ? 0 : this
						.getOriginalRateCostUsdCurrency().hashCode());
		result = 37
				* result
				+ (getOriginalRateCostUsdcurrencysign() == null ? 0 : this
						.getOriginalRateCostUsdcurrencysign().hashCode());
		result = 37
				* result
				+ (getOriginalRateCurrcurrencyid() == null ? 0 : this
						.getOriginalRateCurrcurrencyid().hashCode());
		result = 37
				* result
				+ (getOriginalRateCurrcurrencyversion() == null ? 0 : this
						.getOriginalRateCurrcurrencyversion().hashCode());
		result = 37
				* result
				+ (getOriginalRateCurrencyname() == null ? 0 : this
						.getOriginalRateCurrencyname().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public ShopRoomTarriffGeneralRateView specialInit() {
	
		
		return this;
	}
	public ShopRoomTarriffGeneralRateView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ShopRoomTarriffGeneralRateView customInitList(List<String> list) {
		
		return this;
	}
	
	public ShopRoomTarriffGeneralRateView initList() {

		return this;
	}
	
	public ShopRoomTarriffGeneralRateView initDicts() {
		return this;
	}
	
	
}