/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import java.util.LinkedList;
import javax.persistence.Transient;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import org.test.shop.model.domain.SView;
import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;


/**
 * ShopRoomView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "dictglobalbyroomtypeid"
			 
})
@Entity
@Table(name="shop_room_view")
public class ShopRoomView extends SView  {

	private static final long serialVersionUID = 7326265353739734L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private Boolean breakfast;
	private String descr;
	private Integer guestnumber;
	private Integer roomnumber;
	private String dictglobalbyroomtype;
	private Integer dictglobalbyroomtypeid;
	private String servhotel;
	private Integer servhotelid;
	private Integer servhotelversion;
	private String image;
	private BigDecimal cost;

	public ShopRoomView() {
	}

	public ShopRoomView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String label, Boolean breakfast, String descr,
			Integer guestnumber, Integer roomnumber,
			String dictglobalbyroomtype, Integer dictglobalbyroomtypeid,
			String servhotel, Integer servhotelid, Integer servhotelversion,
			String image, BigDecimal cost) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.breakfast = breakfast;
		this.descr = descr;
		this.guestnumber = guestnumber;
		this.roomnumber = roomnumber;
		this.dictglobalbyroomtype = dictglobalbyroomtype;
		this.dictglobalbyroomtypeid = dictglobalbyroomtypeid;
		this.servhotel = servhotel;
		this.servhotelid = servhotelid;
		this.servhotelversion = servhotelversion;
		this.image = image;
		this.cost = cost;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="breakfast")
	public Boolean getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(Boolean breakfast) {
		this.breakfast = breakfast;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="guestnumber")
	public Integer getGuestnumber() {
		return this.guestnumber;
	}

	public void setGuestnumber(Integer guestnumber) {
		this.guestnumber = guestnumber;
	}

	@Column(name="roomnumber")
	public Integer getRoomnumber() {
		return this.roomnumber;
	}

	public void setRoomnumber(Integer roomnumber) {
		this.roomnumber = roomnumber;
	}

	@Column(name="dictglobalbyroomtype")
	public String getDictglobalbyroomtype() {
		return this.dictglobalbyroomtype;
	}

	public void setDictglobalbyroomtype(String dictglobalbyroomtype) {
		this.dictglobalbyroomtype = dictglobalbyroomtype;
	}

	@Column(name="dictglobalbyroomtypeid")
	public Integer getDictglobalbyroomtypeid() {
		return this.dictglobalbyroomtypeid;
	}

	public void setDictglobalbyroomtypeid(Integer dictglobalbyroomtypeid) {
		this.dictglobalbyroomtypeid = dictglobalbyroomtypeid;
	}

	@Column(name="servhotel")
	public String getServhotel() {
		return this.servhotel;
	}

	public void setServhotel(String servhotel) {
		this.servhotel = servhotel;
	}

	@Column(name="servhotelid")
	public Integer getServhotelid() {
		return this.servhotelid;
	}

	public void setServhotelid(Integer servhotelid) {
		this.servhotelid = servhotelid;
	}

	@Column(name="servhotelversion")
	public Integer getServhotelversion() {
		return this.servhotelversion;
	}

	public void setServhotelversion(Integer servhotelversion) {
		this.servhotelversion = servhotelversion;
	}

	@Column(name="image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name="cost", precision = 131089, scale = 0)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopRoomView))
			return false;
		ShopRoomView castOther = (ShopRoomView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getBreakfast() == castOther.getBreakfast()) || (this
						.getBreakfast() != null
						&& castOther.getBreakfast() != null && this
						.getBreakfast().equals(castOther.getBreakfast())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getGuestnumber() == castOther.getGuestnumber()) || (this
						.getGuestnumber() != null
						&& castOther.getGuestnumber() != null && this
						.getGuestnumber().equals(castOther.getGuestnumber())))
				&& ((this.getRoomnumber() == castOther.getRoomnumber()) || (this
						.getRoomnumber() != null
						&& castOther.getRoomnumber() != null && this
						.getRoomnumber().equals(castOther.getRoomnumber())))
				&& ((this.getDictglobalbyroomtype() == castOther
						.getDictglobalbyroomtype()) || (this
						.getDictglobalbyroomtype() != null
						&& castOther.getDictglobalbyroomtype() != null && this
						.getDictglobalbyroomtype().equals(
								castOther.getDictglobalbyroomtype())))
				&& ((this.getDictglobalbyroomtypeid() == castOther
						.getDictglobalbyroomtypeid()) || (this
						.getDictglobalbyroomtypeid() != null
						&& castOther.getDictglobalbyroomtypeid() != null && this
						.getDictglobalbyroomtypeid().equals(
								castOther.getDictglobalbyroomtypeid())))
				&& ((this.getServhotel() == castOther.getServhotel()) || (this
						.getServhotel() != null
						&& castOther.getServhotel() != null && this
						.getServhotel().equals(castOther.getServhotel())))
				&& ((this.getServhotelid() == castOther.getServhotelid()) || (this
						.getServhotelid() != null
						&& castOther.getServhotelid() != null && this
						.getServhotelid().equals(castOther.getServhotelid())))
				&& ((this.getServhotelversion() == castOther
						.getServhotelversion()) || (this.getServhotelversion() != null
						&& castOther.getServhotelversion() != null && this
						.getServhotelversion().equals(
								castOther.getServhotelversion())))
				&& ((this.getImage() == castOther.getImage()) || (this
						.getImage() != null && castOther.getImage() != null && this
						.getImage().equals(castOther.getImage())))
				&& ((this.getCost() == castOther.getCost()) || (this.getCost() != null
						&& castOther.getCost() != null && this.getCost()
						.equals(castOther.getCost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getBreakfast() == null ? 0 : this.getBreakfast().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getGuestnumber() == null ? 0 : this.getGuestnumber()
						.hashCode());
		result = 37
				* result
				+ (getRoomnumber() == null ? 0 : this.getRoomnumber()
						.hashCode());
		result = 37
				* result
				+ (getDictglobalbyroomtype() == null ? 0 : this
						.getDictglobalbyroomtype().hashCode());
		result = 37
				* result
				+ (getDictglobalbyroomtypeid() == null ? 0 : this
						.getDictglobalbyroomtypeid().hashCode());
		result = 37 * result
				+ (getServhotel() == null ? 0 : this.getServhotel().hashCode());
		result = 37
				* result
				+ (getServhotelid() == null ? 0 : this.getServhotelid()
						.hashCode());
		result = 37
				* result
				+ (getServhotelversion() == null ? 0 : this
						.getServhotelversion().hashCode());
		result = 37 * result
				+ (getImage() == null ? 0 : this.getImage().hashCode());
		result = 37 * result
				+ (getCost() == null ? 0 : this.getCost().hashCode());
		return result;
	}
// #SETTER_AND_GETTER

	private Boolean tarriffcollapsed = true;
	
	@Transient
	public Boolean getTarriffcollapsed() {
		return tarriffcollapsed;
	}

	public void setTarriffcollapsed(Boolean tarriffcollapsed) {
		this.tarriffcollapsed = tarriffcollapsed;
	}
	
	private List<ShopRoomTarriffGeneralRateView> tariffGeneralRate = new LinkedList<ShopRoomTarriffGeneralRateView>();
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="room_id")
	public List<ShopRoomTarriffGeneralRateView> getTariffGeneralRate() {
		return tariffGeneralRate;
	}

	public void setTariffGeneralRate(
			List<ShopRoomTarriffGeneralRateView> tariffGeneralRate) {
		this.tariffGeneralRate = tariffGeneralRate;
	}
	
	private List<ShopHotelRoomImagesView> images = new LinkedList<ShopHotelRoomImagesView>();
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="serv_hotel_room_id")
	public List<ShopHotelRoomImagesView> getImages() {
		return images;
	}

	public void setImages(List<ShopHotelRoomImagesView> images) {
		this.images = images;
	}
	
	
// ------------------ Logic part ------------------
	
	public ShopRoomView specialInit() {
	
		
		return this;
	}
	public ShopRoomView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public ShopRoomView customInitList(List<String> list) {
		
		return this;
	}
	
	public ShopRoomView initList() {

		getTariffGeneralRate().size();
		tariffGeneralRate.parallelStream().forEach(it -> {
			it.initList();
		});
		getImages().size();

		return this;
	}
	
	public ShopRoomView initDicts() {
		return this;
	}
	
	
}