/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * TmContactEasyView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "locationcountriesid"
			, "reqservhotelid" 
})
@Entity
@Table(name="tm_contact_easy_view")
public class TmContactEasyView extends SView  {

	private static final long serialVersionUID = 7766944615965933L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private String descr;
	private String email;
	private Boolean manfoman;
	private String phone;
	private Boolean card;
	private String entitynumber;
	private Boolean passport;
	private Integer popularity;
	private String locationcountries;
	private Integer locationcountriesid;
	private String reqservhotel;
	private Integer reqservhotelid;

	public TmContactEasyView() {
	}

	public TmContactEasyView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String label, String descr, String email,
			Boolean manfoman, String phone, Boolean card, String entitynumber,
			Boolean passport, Integer popularity, String locationcountries,
			Integer locationcountriesid, String reqservhotel,
			Integer reqservhotelid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.descr = descr;
		this.email = email;
		this.manfoman = manfoman;
		this.phone = phone;
		this.card = card;
		this.entitynumber = entitynumber;
		this.passport = passport;
		this.popularity = popularity;
		this.locationcountries = locationcountries;
		this.locationcountriesid = locationcountriesid;
		this.reqservhotel = reqservhotel;
		this.reqservhotelid = reqservhotelid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name="manfoman")
	public Boolean getManfoman() {
		return this.manfoman;
	}

	public void setManfoman(Boolean manfoman) {
		this.manfoman = manfoman;
	}

	@Column(name="phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name="card")
	public Boolean getCard() {
		return this.card;
	}

	public void setCard(Boolean card) {
		this.card = card;
	}

	@Column(name="entitynumber")
	public String getEntitynumber() {
		return this.entitynumber;
	}

	public void setEntitynumber(String entitynumber) {
		this.entitynumber = entitynumber;
	}

	@Column(name="passport")
	public Boolean getPassport() {
		return this.passport;
	}

	public void setPassport(Boolean passport) {
		this.passport = passport;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="locationcountries")
	public String getLocationcountries() {
		return this.locationcountries;
	}

	public void setLocationcountries(String locationcountries) {
		this.locationcountries = locationcountries;
	}

	@Column(name="locationcountriesid")
	public Integer getLocationcountriesid() {
		return this.locationcountriesid;
	}

	public void setLocationcountriesid(Integer locationcountriesid) {
		this.locationcountriesid = locationcountriesid;
	}

	@Column(name="reqservhotel")
	public String getReqservhotel() {
		return this.reqservhotel;
	}

	public void setReqservhotel(String reqservhotel) {
		this.reqservhotel = reqservhotel;
	}

	@Column(name="reqservhotelid")
	public Integer getReqservhotelid() {
		return this.reqservhotelid;
	}

	public void setReqservhotelid(Integer reqservhotelid) {
		this.reqservhotelid = reqservhotelid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmContactEasyView))
			return false;
		TmContactEasyView castOther = (TmContactEasyView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getManfoman() == castOther.getManfoman()) || (this
						.getManfoman() != null
						&& castOther.getManfoman() != null && this
						.getManfoman().equals(castOther.getManfoman())))
				&& ((this.getPhone() == castOther.getPhone()) || (this
						.getPhone() != null && castOther.getPhone() != null && this
						.getPhone().equals(castOther.getPhone())))
				&& ((this.getCard() == castOther.getCard()) || (this.getCard() != null
						&& castOther.getCard() != null && this.getCard()
						.equals(castOther.getCard())))
				&& ((this.getEntitynumber() == castOther.getEntitynumber()) || (this
						.getEntitynumber() != null
						&& castOther.getEntitynumber() != null && this
						.getEntitynumber().equals(castOther.getEntitynumber())))
				&& ((this.getPassport() == castOther.getPassport()) || (this
						.getPassport() != null
						&& castOther.getPassport() != null && this
						.getPassport().equals(castOther.getPassport())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getLocationcountries() == castOther
						.getLocationcountries()) || (this
						.getLocationcountries() != null
						&& castOther.getLocationcountries() != null && this
						.getLocationcountries().equals(
								castOther.getLocationcountries())))
				&& ((this.getLocationcountriesid() == castOther
						.getLocationcountriesid()) || (this
						.getLocationcountriesid() != null
						&& castOther.getLocationcountriesid() != null && this
						.getLocationcountriesid().equals(
								castOther.getLocationcountriesid())))
				&& ((this.getReqservhotel() == castOther.getReqservhotel()) || (this
						.getReqservhotel() != null
						&& castOther.getReqservhotel() != null && this
						.getReqservhotel().equals(castOther.getReqservhotel())))
				&& ((this.getReqservhotelid() == castOther.getReqservhotelid()) || (this
						.getReqservhotelid() != null
						&& castOther.getReqservhotelid() != null && this
						.getReqservhotelid().equals(
								castOther.getReqservhotelid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getManfoman() == null ? 0 : this.getManfoman().hashCode());
		result = 37 * result
				+ (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result
				+ (getCard() == null ? 0 : this.getCard().hashCode());
		result = 37
				* result
				+ (getEntitynumber() == null ? 0 : this.getEntitynumber()
						.hashCode());
		result = 37 * result
				+ (getPassport() == null ? 0 : this.getPassport().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getLocationcountries() == null ? 0 : this
						.getLocationcountries().hashCode());
		result = 37
				* result
				+ (getLocationcountriesid() == null ? 0 : this
						.getLocationcountriesid().hashCode());
		result = 37
				* result
				+ (getReqservhotel() == null ? 0 : this.getReqservhotel()
						.hashCode());
		result = 37
				* result
				+ (getReqservhotelid() == null ? 0 : this.getReqservhotelid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public TmContactEasyView specialInit() {
	
		
		return this;
	}
	public TmContactEasyView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmContactEasyView customInitList(List<String> list) {
		
		return this;
	}
	
	public TmContactEasyView initList() {

		return this;
	}
	
	public TmContactEasyView initDicts() {
		return this;
	}
	
	
}