/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * TmContactView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "locationcountriesid" 
})
@Entity
@Table(name="tm_contact_view")
public class TmContactView extends SView  {

	private static final long serialVersionUID = 8157429713823959L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private Date birthday;
	private String contactname;
	private String contactpatronymic;
	private String contactsurname;
	private String descr;
	private Date passportenddate;
	private String passportnumber;
	private Date passportstartdate;
	private Integer popularity;
	private String locationcountries;
	private Integer locationcountriesid;

	private List<RelServTransferTmContactView> relServTransferTmContacts = new LinkedList<RelServTransferTmContactView>();
	
	public TmContactView() {
	}

	public TmContactView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, Date birthday, String contactname,
			String contactpatronymic, String contactsurname, String descr,
			Date passportenddate, String passportnumber,
			Date passportstartdate, Integer popularity,
			String locationcountries, Integer locationcountriesid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.birthday = birthday;
		this.contactname=contactname;
		this.contactpatronymic = contactpatronymic;
		this.contactsurname=contactsurname;
		this.descr = descr;
		this.passportenddate = passportenddate;
		this.passportnumber = passportnumber;
		this.passportstartdate = passportstartdate;
		this.popularity = popularity;
		this.locationcountries = locationcountries;
		this.locationcountriesid = locationcountriesid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="birthday", length = 29)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name="contactname")
	public String getContactname() {
		return this.contactname;
	}

	public void setContactname(String contactname) {
		this.contactname=contactname;
	}

	@Column(name="contactpatronymic")
	public String getContactpatronymic() {
		return this.contactpatronymic;
	}

	public void setContactpatronymic(String contactpatronymic) {
		this.contactpatronymic = contactpatronymic;
	}

	@Column(name="contactsurname")
	public String getContactsurname() {
		return this.contactsurname;
	}

	public void setContactsurname(String contactsurname) {
		this.contactsurname=contactsurname;
	}

	@Column(name="descr", length = 2000)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name="passportenddate", length = 29)
	public Date getPassportenddate() {
		return this.passportenddate;
	}

	public void setPassportenddate(Date passportenddate) {
		this.passportenddate = passportenddate;
	}

	@Column(name="passportnumber")
	public String getPassportnumber() {
		return this.passportnumber;
	}

	public void setPassportnumber(String passportnumber) {
		this.passportnumber = passportnumber;
	}

	@Column(name="passportstartdate", length = 29)
	public Date getPassportstartdate() {
		return this.passportstartdate;
	}

	public void setPassportstartdate(Date passportstartdate) {
		this.passportstartdate = passportstartdate;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="locationcountries")
	public String getLocationcountries() {
		return this.locationcountries;
	}

	public void setLocationcountries(String locationcountries) {
		this.locationcountries = locationcountries;
	}

	@Column(name="locationcountriesid")
	public Integer getLocationcountriesid() {
		return this.locationcountriesid;
	}

	public void setLocationcountriesid(Integer locationcountriesid) {
		this.locationcountriesid = locationcountriesid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="tmcontactid")
	public List<RelServTransferTmContactView> getRelServTransferTmContacts() {
		return this.relServTransferTmContacts;
	}

	public void setRelServTransferTmContacts(List<RelServTransferTmContactView> relServTransferTmContacts) {
		this.relServTransferTmContacts = relServTransferTmContacts;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmContactView))
			return false;
		TmContactView castOther = (TmContactView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getBirthday() == castOther.getBirthday()) || (this
						.getBirthday() != null
						&& castOther.getBirthday() != null && this
						.getBirthday().equals(castOther.getBirthday())))
				&& ((this.getContactname() == castOther.getContactname()) || (this
						.getContactname() != null
						&& castOther.getContactname() != null && this
						.getContactname().equals(castOther.getContactname())))
				&& ((this.getContactpatronymic() == castOther
						.getContactpatronymic()) || (this
						.getContactpatronymic() != null
						&& castOther.getContactpatronymic() != null && this
						.getContactpatronymic().equals(
								castOther.getContactpatronymic())))
				&& ((this.getContactsurname() == castOther.getContactsurname()) || (this
						.getContactsurname() != null
						&& castOther.getContactsurname() != null && this
						.getContactsurname().equals(
								castOther.getContactsurname())))
				&& ((this.getDescr() == castOther.getDescr()) || (this
						.getDescr() != null && castOther.getDescr() != null && this
						.getDescr().equals(castOther.getDescr())))
				&& ((this.getPassportenddate() == castOther
						.getPassportenddate()) || (this.getPassportenddate() != null
						&& castOther.getPassportenddate() != null && this
						.getPassportenddate().equals(
								castOther.getPassportenddate())))
				&& ((this.getPassportnumber() == castOther.getPassportnumber()) || (this
						.getPassportnumber() != null
						&& castOther.getPassportnumber() != null && this
						.getPassportnumber().equals(
								castOther.getPassportnumber())))
				&& ((this.getPassportstartdate() == castOther
						.getPassportstartdate()) || (this
						.getPassportstartdate() != null
						&& castOther.getPassportstartdate() != null && this
						.getPassportstartdate().equals(
								castOther.getPassportstartdate())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getLocationcountries() == castOther
						.getLocationcountries()) || (this
						.getLocationcountries() != null
						&& castOther.getLocationcountries() != null && this
						.getLocationcountries().equals(
								castOther.getLocationcountries())))
				&& ((this.getLocationcountriesid() == castOther
						.getLocationcountriesid()) || (this
						.getLocationcountriesid() != null
						&& castOther.getLocationcountriesid() != null && this
						.getLocationcountriesid().equals(
								castOther.getLocationcountriesid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getBirthday() == null ? 0 : this.getBirthday().hashCode());
		result = 37
				* result
				+ (getContactname() == null ? 0 : this.getContactname()
						.hashCode());
		result = 37
				* result
				+ (getContactpatronymic() == null ? 0 : this
						.getContactpatronymic().hashCode());
		result = 37
				* result
				+ (getContactsurname() == null ? 0 : this.getContactsurname()
						.hashCode());
		result = 37 * result
				+ (getDescr() == null ? 0 : this.getDescr().hashCode());
		result = 37
				* result
				+ (getPassportenddate() == null ? 0 : this.getPassportenddate()
						.hashCode());
		result = 37
				* result
				+ (getPassportnumber() == null ? 0 : this.getPassportnumber()
						.hashCode());
		result = 37
				* result
				+ (getPassportstartdate() == null ? 0 : this
						.getPassportstartdate().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37
				* result
				+ (getLocationcountries() == null ? 0 : this
						.getLocationcountries().hashCode());
		result = 37
				* result
				+ (getLocationcountriesid() == null ? 0 : this
						.getLocationcountriesid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER

	@Transient
	public String getLabel() {
		return contactsurname + " " + contactname;
	}
 
	public void setLabel(String label) {
		
	}
	
	
// ------------------ Logic part ------------------
	
	public TmContactView specialInit() {
	
		
		return this;
	}
	public TmContactView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmContactView customInitList(List<String> list) {
		if (list.contains("relServTransferTmContacts")) {
			initLists(relServTransferTmContacts);
		}
		return this;
	}
	
	public TmContactView initList() {
		initLists(relServTransferTmContacts);

		return this;
	}
	
	public TmContactView initDicts() {
		return this;
	}
	
	
}