/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * TmFirmSettingsView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "docdocumentsid" 
})
@Entity
@Table(name="tm_firm_settings_view")
public class TmFirmSettingsView extends SView  {

	private static final long serialVersionUID = 6154633891974446L;

	private Integer id;
	private Integer version;
	private Integer logo;
	private String brand;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private Integer popularity;
	private String serieskey;
	private String docdocuments;
	private Integer docdocumentsid;

	public TmFirmSettingsView() {
	}

	public TmFirmSettingsView(Integer id, Integer version, Integer logo,
			String brand, String createdby, Date createon, Integer firm,
			String lastmodifiedby, Date modifyon, Integer popularity,
			String serieskey, String docdocuments, Integer docdocumentsid) {
		this.id = id;
		this.version = version;
		this.logo = logo;
		this.brand = brand;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.popularity = popularity;
		this.serieskey = serieskey;
		this.docdocuments = docdocuments;
		this.docdocumentsid = docdocumentsid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="logo")
	public Integer getLogo() {
		return this.logo;
	}

	public void setLogo(Integer logo) {
		this.logo = logo;
	}

	@Column(name="brand")
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="docdocuments")
	public String getDocdocuments() {
		return this.docdocuments;
	}

	public void setDocdocuments(String docdocuments) {
		this.docdocuments = docdocuments;
	}

	@Column(name="docdocumentsid")
	public Integer getDocdocumentsid() {
		return this.docdocumentsid;
	}

	public void setDocdocumentsid(Integer docdocumentsid) {
		this.docdocumentsid = docdocumentsid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmFirmSettingsView))
			return false;
		TmFirmSettingsView castOther = (TmFirmSettingsView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getLogo() == castOther.getLogo()) || (this.getLogo() != null
						&& castOther.getLogo() != null && this.getLogo()
						.equals(castOther.getLogo())))
				&& ((this.getBrand() == castOther.getBrand()) || (this
						.getBrand() != null && castOther.getBrand() != null && this
						.getBrand().equals(castOther.getBrand())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getDocdocuments() == castOther.getDocdocuments()) || (this
						.getDocdocuments() != null
						&& castOther.getDocdocuments() != null && this
						.getDocdocuments().equals(castOther.getDocdocuments())))
				&& ((this.getDocdocumentsid() == castOther.getDocdocumentsid()) || (this
						.getDocdocumentsid() != null
						&& castOther.getDocdocumentsid() != null && this
						.getDocdocumentsid().equals(
								castOther.getDocdocumentsid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getLogo() == null ? 0 : this.getLogo().hashCode());
		result = 37 * result
				+ (getBrand() == null ? 0 : this.getBrand().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37
				* result
				+ (getDocdocuments() == null ? 0 : this.getDocdocuments()
						.hashCode());
		result = 37
				* result
				+ (getDocdocumentsid() == null ? 0 : this.getDocdocumentsid()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public TmFirmSettingsView specialInit() {
	
		
		return this;
	}
	public TmFirmSettingsView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmFirmSettingsView customInitList(List<String> list) {
		
		return this;
	}
	
	public TmFirmSettingsView initList() {

		return this;
	}
	
	public TmFirmSettingsView initDicts() {
		return this;
	}
	
	
}