/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.shop.model.domain.entity.view;

// Generated 30.08.2015 21:00:08 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;

import java.util.Date;

import javax.persistence.Column;

import org.test.shop.model.domain.SView;


/**
 * TmUserInfoView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "createon"
			, "modifyon"
			, "popularity" 
})
@Entity
@Table(name="tm_user_info_view")
public class TmUserInfoView extends SView  {

	private static final long serialVersionUID = 8632237393578975L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private String browser;
	private String browserversion;
	private Date lastlogin;
	private String platform;
	private String platformversion;
	private String proxycontent;
	private String remotehost;
	private String useragent;
	private String useripaddress;
	private String username;
	private Integer popularity;

	public TmUserInfoView() {
	}

	public TmUserInfoView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, String label, String browser,
			String browserversion, Date lastlogin, String platform,
			String platformversion, String proxycontent, String remotehost,
			String useragent, String useripaddress, String username,
			Integer popularity) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.label = label;
		this.browser = browser;
		this.browserversion = browserversion;
		this.lastlogin = lastlogin;
		this.platform = platform;
		this.platformversion = platformversion;
		this.proxycontent = proxycontent;
		this.remotehost = remotehost;
		this.useragent = useragent;
		this.useripaddress = useripaddress;
		this.username=username;
		this.popularity = popularity;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name="browser")
	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	@Column(name="browserversion")
	public String getBrowserversion() {
		return this.browserversion;
	}

	public void setBrowserversion(String browserversion) {
		this.browserversion = browserversion;
	}

	@Column(name="lastlogin", length = 29)
	public Date getLastlogin() {
		return this.lastlogin;
	}

	public void setLastlogin(Date lastlogin) {
		this.lastlogin = lastlogin;
	}

	@Column(name="platform")
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name="platformversion")
	public String getPlatformversion() {
		return this.platformversion;
	}

	public void setPlatformversion(String platformversion) {
		this.platformversion = platformversion;
	}

	@Column(name="proxycontent")
	public String getProxycontent() {
		return this.proxycontent;
	}

	public void setProxycontent(String proxycontent) {
		this.proxycontent = proxycontent;
	}

	@Column(name="remotehost")
	public String getRemotehost() {
		return this.remotehost;
	}

	public void setRemotehost(String remotehost) {
		this.remotehost = remotehost;
	}

	@Column(name="useragent")
	public String getUseragent() {
		return this.useragent;
	}

	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}

	@Column(name="useripaddress")
	public String getUseripaddress() {
		return this.useripaddress;
	}

	public void setUseripaddress(String useripaddress) {
		this.useripaddress = useripaddress;
	}

	@Column(name="username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username=username;
	}

	@Column(name="popularity")
	public Integer getPopularity() {
		return this.popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmUserInfoView))
			return false;
		TmUserInfoView castOther = (TmUserInfoView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getBrowser() == castOther.getBrowser()) || (this
						.getBrowser() != null && castOther.getBrowser() != null && this
						.getBrowser().equals(castOther.getBrowser())))
				&& ((this.getBrowserversion() == castOther.getBrowserversion()) || (this
						.getBrowserversion() != null
						&& castOther.getBrowserversion() != null && this
						.getBrowserversion().equals(
								castOther.getBrowserversion())))
				&& ((this.getLastlogin() == castOther.getLastlogin()) || (this
						.getLastlogin() != null
						&& castOther.getLastlogin() != null && this
						.getLastlogin().equals(castOther.getLastlogin())))
				&& ((this.getPlatform() == castOther.getPlatform()) || (this
						.getPlatform() != null
						&& castOther.getPlatform() != null && this
						.getPlatform().equals(castOther.getPlatform())))
				&& ((this.getPlatformversion() == castOther
						.getPlatformversion()) || (this.getPlatformversion() != null
						&& castOther.getPlatformversion() != null && this
						.getPlatformversion().equals(
								castOther.getPlatformversion())))
				&& ((this.getProxycontent() == castOther.getProxycontent()) || (this
						.getProxycontent() != null
						&& castOther.getProxycontent() != null && this
						.getProxycontent().equals(castOther.getProxycontent())))
				&& ((this.getRemotehost() == castOther.getRemotehost()) || (this
						.getRemotehost() != null
						&& castOther.getRemotehost() != null && this
						.getRemotehost().equals(castOther.getRemotehost())))
				&& ((this.getUseragent() == castOther.getUseragent()) || (this
						.getUseragent() != null
						&& castOther.getUseragent() != null && this
						.getUseragent().equals(castOther.getUseragent())))
				&& ((this.getUseripaddress() == castOther.getUseripaddress()) || (this
						.getUseripaddress() != null
						&& castOther.getUseripaddress() != null && this
						.getUseripaddress()
						.equals(castOther.getUseripaddress())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getPopularity() == castOther.getPopularity()) || (this
						.getPopularity() != null
						&& castOther.getPopularity() != null && this
						.getPopularity().equals(castOther.getPopularity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getBrowser() == null ? 0 : this.getBrowser().hashCode());
		result = 37
				* result
				+ (getBrowserversion() == null ? 0 : this.getBrowserversion()
						.hashCode());
		result = 37 * result
				+ (getLastlogin() == null ? 0 : this.getLastlogin().hashCode());
		result = 37 * result
				+ (getPlatform() == null ? 0 : this.getPlatform().hashCode());
		result = 37
				* result
				+ (getPlatformversion() == null ? 0 : this.getPlatformversion()
						.hashCode());
		result = 37
				* result
				+ (getProxycontent() == null ? 0 : this.getProxycontent()
						.hashCode());
		result = 37
				* result
				+ (getRemotehost() == null ? 0 : this.getRemotehost()
						.hashCode());
		result = 37 * result
				+ (getUseragent() == null ? 0 : this.getUseragent().hashCode());
		result = 37
				* result
				+ (getUseripaddress() == null ? 0 : this.getUseripaddress()
						.hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37
				* result
				+ (getPopularity() == null ? 0 : this.getPopularity()
						.hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public TmUserInfoView specialInit() {
	
		
		return this;
	}
	public TmUserInfoView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public TmUserInfoView customInitList(List<String> list) {
		
		return this;
	}
	
	public TmUserInfoView initList() {

		return this;
	}
	
	public TmUserInfoView initDicts() {
		return this;
	}
	
	
}